language: c
compiler:
  - gcc
#  - clang
branches:
  except:
    - artwork
    - debian
    - gh-pages
    - packaging
    - valamang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install update-manager-core software-properties-common
  - sudo sed -i 's/^\(Prompt=\).*/\1lts/' /etc/update-manager/release-upgrades
  - sudo do-release-upgrade -d -f DistUpgradeViewNonInteractive
  - sudo add-apt-repository -y ppa:vala-team/ppa
  - sudo apt-get update -qq
  - eval $(sed -n '/^On Debian based systems install/{n;n;p}' README.md) valadoc
script: ./autogen && make
