/* view-custom.c generated by valac 0.30.0, the Vala compiler
 * generated from view-custom.vala, do not modify */

/*
 * Copyright (C) 2010 Michal Hruby <michal.mhr@gmail.com>
 * Copyright (C) 2010 Alberto Aldegheri <albyrock87+dev@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by Alberto Aldegheri <albyrock87+dev@gmail.com>
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <synapse-core.h>
#include <gee.h>
#include <gdk/gdk.h>
#include <cairo.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <glib/gi18n-lib.h>


#define SYNAPSE_GUI_TYPE_IVIEW (synapse_gui_iview_get_type ())
#define SYNAPSE_GUI_IVIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_IVIEW, SynapseGuiIView))
#define SYNAPSE_GUI_IS_IVIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_IVIEW))
#define SYNAPSE_GUI_IVIEW_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYNAPSE_GUI_TYPE_IVIEW, SynapseGuiIViewIface))

typedef struct _SynapseGuiIView SynapseGuiIView;
typedef struct _SynapseGuiIViewIface SynapseGuiIViewIface;

#define SYNAPSE_GUI_TYPE_ENTRY (synapse_gui_entry_get_type ())
#define SYNAPSE_GUI_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_ENTRY, SynapseGuiEntry))
#define SYNAPSE_GUI_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_ENTRY, SynapseGuiEntryClass))
#define SYNAPSE_GUI_IS_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_ENTRY))
#define SYNAPSE_GUI_IS_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_ENTRY))
#define SYNAPSE_GUI_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_ENTRY, SynapseGuiEntryClass))

typedef struct _SynapseGuiEntry SynapseGuiEntry;
typedef struct _SynapseGuiEntryClass SynapseGuiEntryClass;

#define SYNAPSE_GUI_TYPE_MODEL (synapse_gui_model_get_type ())
#define SYNAPSE_GUI_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_MODEL, SynapseGuiModel))
#define SYNAPSE_GUI_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_MODEL, SynapseGuiModelClass))
#define SYNAPSE_GUI_IS_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_MODEL))
#define SYNAPSE_GUI_IS_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_MODEL))
#define SYNAPSE_GUI_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_MODEL, SynapseGuiModelClass))

typedef struct _SynapseGuiModel SynapseGuiModel;
typedef struct _SynapseGuiModelClass SynapseGuiModelClass;

#define SYNAPSE_GUI_TYPE_ICONTROLLER (synapse_gui_icontroller_get_type ())
#define SYNAPSE_GUI_ICONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_ICONTROLLER, SynapseGuiIController))
#define SYNAPSE_GUI_IS_ICONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_ICONTROLLER))
#define SYNAPSE_GUI_ICONTROLLER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYNAPSE_GUI_TYPE_ICONTROLLER, SynapseGuiIControllerIface))

typedef struct _SynapseGuiIController SynapseGuiIController;
typedef struct _SynapseGuiIControllerIface SynapseGuiIControllerIface;

#define SYNAPSE_GUI_TYPE_KEY_COMBO_CONFIG (synapse_gui_key_combo_config_get_type ())
#define SYNAPSE_GUI_KEY_COMBO_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_KEY_COMBO_CONFIG, SynapseGuiKeyComboConfig))
#define SYNAPSE_GUI_KEY_COMBO_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_KEY_COMBO_CONFIG, SynapseGuiKeyComboConfigClass))
#define SYNAPSE_GUI_IS_KEY_COMBO_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_KEY_COMBO_CONFIG))
#define SYNAPSE_GUI_IS_KEY_COMBO_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_KEY_COMBO_CONFIG))
#define SYNAPSE_GUI_KEY_COMBO_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_KEY_COMBO_CONFIG, SynapseGuiKeyComboConfigClass))

typedef struct _SynapseGuiKeyComboConfig SynapseGuiKeyComboConfig;
typedef struct _SynapseGuiKeyComboConfigClass SynapseGuiKeyComboConfigClass;

#define SYNAPSE_GUI_TYPE_CATEGORY_CONFIG (synapse_gui_category_config_get_type ())
#define SYNAPSE_GUI_CATEGORY_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_CATEGORY_CONFIG, SynapseGuiCategoryConfig))
#define SYNAPSE_GUI_CATEGORY_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_CATEGORY_CONFIG, SynapseGuiCategoryConfigClass))
#define SYNAPSE_GUI_IS_CATEGORY_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_CATEGORY_CONFIG))
#define SYNAPSE_GUI_IS_CATEGORY_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_CATEGORY_CONFIG))
#define SYNAPSE_GUI_CATEGORY_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_CATEGORY_CONFIG, SynapseGuiCategoryConfigClass))

typedef struct _SynapseGuiCategoryConfig SynapseGuiCategoryConfig;
typedef struct _SynapseGuiCategoryConfigClass SynapseGuiCategoryConfigClass;

#define SYNAPSE_GUI_TYPE_VIEW (synapse_gui_view_get_type ())
#define SYNAPSE_GUI_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_VIEW, SynapseGuiView))
#define SYNAPSE_GUI_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_VIEW, SynapseGuiViewClass))
#define SYNAPSE_GUI_IS_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_VIEW))
#define SYNAPSE_GUI_IS_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_VIEW))
#define SYNAPSE_GUI_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_VIEW, SynapseGuiViewClass))

typedef struct _SynapseGuiView SynapseGuiView;
typedef struct _SynapseGuiViewClass SynapseGuiViewClass;
typedef struct _SynapseGuiViewPrivate SynapseGuiViewPrivate;

#define SYNAPSE_GUI_TYPE_SELECTION_CONTAINER (synapse_gui_selection_container_get_type ())
#define SYNAPSE_GUI_SELECTION_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_SELECTION_CONTAINER, SynapseGuiSelectionContainer))
#define SYNAPSE_GUI_SELECTION_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_SELECTION_CONTAINER, SynapseGuiSelectionContainerClass))
#define SYNAPSE_GUI_IS_SELECTION_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_SELECTION_CONTAINER))
#define SYNAPSE_GUI_IS_SELECTION_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_SELECTION_CONTAINER))
#define SYNAPSE_GUI_SELECTION_CONTAINER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_SELECTION_CONTAINER, SynapseGuiSelectionContainerClass))

typedef struct _SynapseGuiSelectionContainer SynapseGuiSelectionContainer;
typedef struct _SynapseGuiSelectionContainerClass SynapseGuiSelectionContainerClass;

#define SYNAPSE_GUI_TYPE_RESULT_BOX (synapse_gui_result_box_get_type ())
#define SYNAPSE_GUI_RESULT_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_RESULT_BOX, SynapseGuiResultBox))
#define SYNAPSE_GUI_RESULT_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_RESULT_BOX, SynapseGuiResultBoxClass))
#define SYNAPSE_GUI_IS_RESULT_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_RESULT_BOX))
#define SYNAPSE_GUI_IS_RESULT_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_RESULT_BOX))
#define SYNAPSE_GUI_RESULT_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_RESULT_BOX, SynapseGuiResultBoxClass))

typedef struct _SynapseGuiResultBox SynapseGuiResultBox;
typedef struct _SynapseGuiResultBoxClass SynapseGuiResultBoxClass;

#define SYNAPSE_GUI_UTILS_TYPE_COLOR_HELPER (synapse_gui_utils_color_helper_get_type ())
#define SYNAPSE_GUI_UTILS_COLOR_HELPER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_UTILS_TYPE_COLOR_HELPER, SynapseGuiUtilsColorHelper))
#define SYNAPSE_GUI_UTILS_COLOR_HELPER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_UTILS_TYPE_COLOR_HELPER, SynapseGuiUtilsColorHelperClass))
#define SYNAPSE_GUI_UTILS_IS_COLOR_HELPER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_UTILS_TYPE_COLOR_HELPER))
#define SYNAPSE_GUI_UTILS_IS_COLOR_HELPER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_UTILS_TYPE_COLOR_HELPER))
#define SYNAPSE_GUI_UTILS_COLOR_HELPER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_UTILS_TYPE_COLOR_HELPER, SynapseGuiUtilsColorHelperClass))

typedef struct _SynapseGuiUtilsColorHelper SynapseGuiUtilsColorHelper;
typedef struct _SynapseGuiUtilsColorHelperClass SynapseGuiUtilsColorHelperClass;

#define SYNAPSE_GUI_TYPE_HTEXT_SELECTOR (synapse_gui_htext_selector_get_type ())
#define SYNAPSE_GUI_HTEXT_SELECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_HTEXT_SELECTOR, SynapseGuiHTextSelector))
#define SYNAPSE_GUI_HTEXT_SELECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_HTEXT_SELECTOR, SynapseGuiHTextSelectorClass))
#define SYNAPSE_GUI_IS_HTEXT_SELECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_HTEXT_SELECTOR))
#define SYNAPSE_GUI_IS_HTEXT_SELECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_HTEXT_SELECTOR))
#define SYNAPSE_GUI_HTEXT_SELECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_HTEXT_SELECTOR, SynapseGuiHTextSelectorClass))

typedef struct _SynapseGuiHTextSelector SynapseGuiHTextSelector;
typedef struct _SynapseGuiHTextSelectorClass SynapseGuiHTextSelectorClass;

#define SYNAPSE_GUI_TYPE_FAKE_BUTTON (synapse_gui_fake_button_get_type ())
#define SYNAPSE_GUI_FAKE_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_FAKE_BUTTON, SynapseGuiFakeButton))
#define SYNAPSE_GUI_FAKE_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_FAKE_BUTTON, SynapseGuiFakeButtonClass))
#define SYNAPSE_GUI_IS_FAKE_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_FAKE_BUTTON))
#define SYNAPSE_GUI_IS_FAKE_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_FAKE_BUTTON))
#define SYNAPSE_GUI_FAKE_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_FAKE_BUTTON, SynapseGuiFakeButtonClass))

typedef struct _SynapseGuiFakeButton SynapseGuiFakeButton;
typedef struct _SynapseGuiFakeButtonClass SynapseGuiFakeButtonClass;

#define SYNAPSE_GUI_TYPE_MENU_BUTTON (synapse_gui_menu_button_get_type ())
#define SYNAPSE_GUI_MENU_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_MENU_BUTTON, SynapseGuiMenuButton))
#define SYNAPSE_GUI_MENU_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_MENU_BUTTON, SynapseGuiMenuButtonClass))
#define SYNAPSE_GUI_IS_MENU_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_MENU_BUTTON))
#define SYNAPSE_GUI_IS_MENU_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_MENU_BUTTON))
#define SYNAPSE_GUI_MENU_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_MENU_BUTTON, SynapseGuiMenuButtonClass))

typedef struct _SynapseGuiMenuButton SynapseGuiMenuButton;
typedef struct _SynapseGuiMenuButtonClass SynapseGuiMenuButtonClass;

#define SYNAPSE_GUI_TYPE_VIEW_CUSTOM (synapse_gui_view_custom_get_type ())
#define SYNAPSE_GUI_VIEW_CUSTOM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_VIEW_CUSTOM, SynapseGuiViewCustom))
#define SYNAPSE_GUI_VIEW_CUSTOM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_VIEW_CUSTOM, SynapseGuiViewCustomClass))
#define SYNAPSE_GUI_IS_VIEW_CUSTOM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_VIEW_CUSTOM))
#define SYNAPSE_GUI_IS_VIEW_CUSTOM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_VIEW_CUSTOM))
#define SYNAPSE_GUI_VIEW_CUSTOM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_VIEW_CUSTOM, SynapseGuiViewCustomClass))

typedef struct _SynapseGuiViewCustom SynapseGuiViewCustom;
typedef struct _SynapseGuiViewCustomClass SynapseGuiViewCustomClass;
typedef struct _SynapseGuiViewCustomPrivate SynapseGuiViewCustomPrivate;

#define SYNAPSE_GUI_TYPE_SMART_LABEL (synapse_gui_smart_label_get_type ())
#define SYNAPSE_GUI_SMART_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_SMART_LABEL, SynapseGuiSmartLabel))
#define SYNAPSE_GUI_SMART_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_SMART_LABEL, SynapseGuiSmartLabelClass))
#define SYNAPSE_GUI_IS_SMART_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_SMART_LABEL))
#define SYNAPSE_GUI_IS_SMART_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_SMART_LABEL))
#define SYNAPSE_GUI_SMART_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_SMART_LABEL, SynapseGuiSmartLabelClass))

typedef struct _SynapseGuiSmartLabel SynapseGuiSmartLabel;
typedef struct _SynapseGuiSmartLabelClass SynapseGuiSmartLabelClass;

#define SYNAPSE_GUI_TYPE_MATCH_LIST_VIEW (synapse_gui_match_list_view_get_type ())
#define SYNAPSE_GUI_MATCH_LIST_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_MATCH_LIST_VIEW, SynapseGuiMatchListView))
#define SYNAPSE_GUI_MATCH_LIST_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_MATCH_LIST_VIEW, SynapseGuiMatchListViewClass))
#define SYNAPSE_GUI_IS_MATCH_LIST_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_MATCH_LIST_VIEW))
#define SYNAPSE_GUI_IS_MATCH_LIST_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_MATCH_LIST_VIEW))
#define SYNAPSE_GUI_MATCH_LIST_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_MATCH_LIST_VIEW, SynapseGuiMatchListViewClass))

typedef struct _SynapseGuiMatchListView SynapseGuiMatchListView;
typedef struct _SynapseGuiMatchListViewClass SynapseGuiMatchListViewClass;

#define SYNAPSE_GUI_TYPE_SPECIFIC_MATCH_LIST (synapse_gui_specific_match_list_get_type ())
#define SYNAPSE_GUI_SPECIFIC_MATCH_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_SPECIFIC_MATCH_LIST, SynapseGuiSpecificMatchList))
#define SYNAPSE_GUI_SPECIFIC_MATCH_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_SPECIFIC_MATCH_LIST, SynapseGuiSpecificMatchListClass))
#define SYNAPSE_GUI_IS_SPECIFIC_MATCH_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_SPECIFIC_MATCH_LIST))
#define SYNAPSE_GUI_IS_SPECIFIC_MATCH_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_SPECIFIC_MATCH_LIST))
#define SYNAPSE_GUI_SPECIFIC_MATCH_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_SPECIFIC_MATCH_LIST, SynapseGuiSpecificMatchListClass))

typedef struct _SynapseGuiSpecificMatchList SynapseGuiSpecificMatchList;
typedef struct _SynapseGuiSpecificMatchListClass SynapseGuiSpecificMatchListClass;

#define SYNAPSE_GUI_TYPE_MENU_THROBBER (synapse_gui_menu_throbber_get_type ())
#define SYNAPSE_GUI_MENU_THROBBER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_MENU_THROBBER, SynapseGuiMenuThrobber))
#define SYNAPSE_GUI_MENU_THROBBER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_MENU_THROBBER, SynapseGuiMenuThrobberClass))
#define SYNAPSE_GUI_IS_MENU_THROBBER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_MENU_THROBBER))
#define SYNAPSE_GUI_IS_MENU_THROBBER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_MENU_THROBBER))
#define SYNAPSE_GUI_MENU_THROBBER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_MENU_THROBBER, SynapseGuiMenuThrobberClass))

typedef struct _SynapseGuiMenuThrobber SynapseGuiMenuThrobber;
typedef struct _SynapseGuiMenuThrobberClass SynapseGuiMenuThrobberClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define SYNAPSE_GUI_MATCH_LIST_VIEW_TYPE_MATCH_VIEW_RENDERER_BASE (synapse_gui_match_list_view_match_view_renderer_base_get_type ())
#define SYNAPSE_GUI_MATCH_LIST_VIEW_MATCH_VIEW_RENDERER_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_MATCH_LIST_VIEW_TYPE_MATCH_VIEW_RENDERER_BASE, SynapseGuiMatchListViewMatchViewRendererBase))
#define SYNAPSE_GUI_MATCH_LIST_VIEW_MATCH_VIEW_RENDERER_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_MATCH_LIST_VIEW_TYPE_MATCH_VIEW_RENDERER_BASE, SynapseGuiMatchListViewMatchViewRendererBaseClass))
#define SYNAPSE_GUI_MATCH_LIST_VIEW_IS_MATCH_VIEW_RENDERER_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_MATCH_LIST_VIEW_TYPE_MATCH_VIEW_RENDERER_BASE))
#define SYNAPSE_GUI_MATCH_LIST_VIEW_IS_MATCH_VIEW_RENDERER_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_MATCH_LIST_VIEW_TYPE_MATCH_VIEW_RENDERER_BASE))
#define SYNAPSE_GUI_MATCH_LIST_VIEW_MATCH_VIEW_RENDERER_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_MATCH_LIST_VIEW_TYPE_MATCH_VIEW_RENDERER_BASE, SynapseGuiMatchListViewMatchViewRendererBaseClass))

typedef struct _SynapseGuiMatchListViewMatchViewRendererBase SynapseGuiMatchListViewMatchViewRendererBase;
typedef struct _SynapseGuiMatchListViewMatchViewRendererBaseClass SynapseGuiMatchListViewMatchViewRendererBaseClass;

#define SYNAPSE_GUI_TYPE_MATCH_VIEW_RENDERER (synapse_gui_match_view_renderer_get_type ())
#define SYNAPSE_GUI_MATCH_VIEW_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_MATCH_VIEW_RENDERER, SynapseGuiMatchViewRenderer))
#define SYNAPSE_GUI_MATCH_VIEW_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_MATCH_VIEW_RENDERER, SynapseGuiMatchViewRendererClass))
#define SYNAPSE_GUI_IS_MATCH_VIEW_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_MATCH_VIEW_RENDERER))
#define SYNAPSE_GUI_IS_MATCH_VIEW_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_MATCH_VIEW_RENDERER))
#define SYNAPSE_GUI_MATCH_VIEW_RENDERER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_MATCH_VIEW_RENDERER, SynapseGuiMatchViewRendererClass))

typedef struct _SynapseGuiMatchViewRenderer SynapseGuiMatchViewRenderer;
typedef struct _SynapseGuiMatchViewRendererClass SynapseGuiMatchViewRendererClass;
#define _g_free0(var) (var = (g_free (var), NULL))

#define SYNAPSE_GUI_TYPE_SEARCHING_FOR (synapse_gui_searching_for_get_type ())
typedef struct _SynapseGuiModelPrivate SynapseGuiModelPrivate;
#define _synapse_gui_entry_unref0(var) ((var == NULL) ? NULL : (var = (synapse_gui_entry_unref (var), NULL)))
#define _g_param_spec_unref0(var) ((var == NULL) ? NULL : (var = (g_param_spec_unref (var), NULL)))

struct _SynapseGuiIControllerIface {
	GTypeInterface parent_iface;
	void (*key_press_event) (SynapseGuiIController* self, GdkEventKey* event);
	void (*category_changed_event) (SynapseGuiIController* self, gint category_index);
	void (*fire_focus) (SynapseGuiIController* self);
	void (*selected_index_changed_event) (SynapseGuiIController* self, gint focus_index);
	void (*set_view) (SynapseGuiIController* self, GType view_type);
	void (*summon_or_vanish) (SynapseGuiIController* self);
	gboolean (*is_in_initial_state) (SynapseGuiIController* self);
	gboolean (*searched_for_recent) (SynapseGuiIController* self);
	SynapseDataSink* (*get_data_sink) (SynapseGuiIController* self);
	void (*set_data_sink) (SynapseGuiIController* self, SynapseDataSink* value);
	SynapseGuiKeyComboConfig* (*get_key_combo_config) (SynapseGuiIController* self);
	void (*set_key_combo_config) (SynapseGuiIController* self, SynapseGuiKeyComboConfig* value);
	SynapseGuiCategoryConfig* (*get_category_config) (SynapseGuiIController* self);
	void (*set_category_config) (SynapseGuiIController* self, SynapseGuiCategoryConfig* value);
};

struct _SynapseGuiIViewIface {
	GTypeInterface parent_iface;
	void (*summon) (SynapseGuiIView* self);
	void (*vanish) (SynapseGuiIView* self);
	void (*summon_or_vanish) (SynapseGuiIView* self);
	void (*update_focused_source) (SynapseGuiIView* self, SynapseGuiEntry* m);
	void (*update_focused_action) (SynapseGuiIView* self, SynapseGuiEntry* m);
	void (*update_focused_target) (SynapseGuiIView* self, SynapseGuiEntry* m);
	void (*update_sources) (SynapseGuiIView* self, GeeList* list);
	void (*update_actions) (SynapseGuiIView* self, GeeList* list);
	void (*update_targets) (SynapseGuiIView* self, GeeList* list);
	void (*update_selected_category) (SynapseGuiIView* self);
	void (*update_searching_for) (SynapseGuiIView* self);
	gboolean (*is_list_visible) (SynapseGuiIView* self);
	void (*set_list_visible) (SynapseGuiIView* self, gboolean visible);
	void (*set_throbber_visible) (SynapseGuiIView* self, gboolean visible);
	SynapseGuiModel* (*get_controller_model) (SynapseGuiIView* self);
	void (*set_controller_model) (SynapseGuiIView* self, SynapseGuiModel* value);
	SynapseGuiIController* (*get_controller) (SynapseGuiIView* self);
	void (*set_controller) (SynapseGuiIView* self, SynapseGuiIController* value);
};

struct _SynapseGuiView {
	GtkWindow parent_instance;
	SynapseGuiViewPrivate * priv;
	gboolean is_kwin;
	SynapseGuiUtilsColorHelper* ch;
	SynapseGuiHTextSelector* flag_selector;
	SynapseGuiMenuButton* menu;
	GtkLabel* spacer;
	gint BORDER_RADIUS;
	gint SHADOW_SIZE;
	GtkStateFlags bg_state;
	gboolean cache_enabled;
	GeeMap* bg_cache;
	SynapseGuiModel* model;
};

struct _SynapseGuiViewClass {
	GtkWindowClass parent_class;
	void (*build_ui) (SynapseGuiView* self);
	void (*prepare_results_container) (SynapseGuiView* self, SynapseGuiSelectionContainer** results_container, SynapseGuiResultBox** results_sources, SynapseGuiResultBox** results_actions, SynapseGuiResultBox** results_targets, GtkStateFlags state_type, gboolean add_to_container);
	void (*paint_background) (SynapseGuiView* self, cairo_t* ctx);
	void (*summon) (SynapseGuiView* self);
	void (*vanish) (SynapseGuiView* self);
	void (*summon_or_vanish) (SynapseGuiView* self);
	void (*update_focused_source) (SynapseGuiView* self, SynapseGuiEntry* m);
	void (*update_focused_action) (SynapseGuiView* self, SynapseGuiEntry* m);
	void (*update_focused_target) (SynapseGuiView* self, SynapseGuiEntry* m);
	void (*update_sources) (SynapseGuiView* self, GeeList* list);
	void (*update_actions) (SynapseGuiView* self, GeeList* list);
	void (*update_targets) (SynapseGuiView* self, GeeList* list);
	void (*update_selected_category) (SynapseGuiView* self);
	void (*update_searching_for) (SynapseGuiView* self);
	gboolean (*is_list_visible) (SynapseGuiView* self);
	void (*set_list_visible) (SynapseGuiView* self, gboolean visible);
	void (*set_throbber_visible) (SynapseGuiView* self, gboolean visible);
};

struct _SynapseGuiViewCustom {
	SynapseGuiView parent_instance;
	SynapseGuiViewCustomPrivate * priv;
};

struct _SynapseGuiViewCustomClass {
	SynapseGuiViewClass parent_class;
};

struct _SynapseGuiViewCustomPrivate {
	GtkBox* container;
	GtkBox* action_box;
	GtkBox* target_box;
	SynapseGuiSmartLabel* status;
	SynapseGuiSmartLabel* logo;
	SynapseGuiSmartLabel* search;
	SynapseGuiSpecificMatchList* results_sources;
	SynapseGuiSpecificMatchList* results_actions;
	SynapseGuiSpecificMatchList* results_targets;
	SynapseGuiMenuThrobber* menuthrobber;
};

typedef enum  {
	SYNAPSE_GUI_SEARCHING_FOR_SOURCES,
	SYNAPSE_GUI_SEARCHING_FOR_ACTIONS,
	SYNAPSE_GUI_SEARCHING_FOR_TARGETS,
	SYNAPSE_GUI_SEARCHING_FOR_COUNT
} SynapseGuiSearchingFor;

struct _SynapseGuiModel {
	GObject parent_instance;
	SynapseGuiModelPrivate * priv;
	gchar** query;
	gint query_length1;
	GeeList** results;
	gint results_length1;
	SynapseGuiEntry** focus;
	gint focus_length1;
	gint selected_category;
	SynapseGuiSearchingFor searching_for;
};

struct _SynapseGuiModelClass {
	GObjectClass parent_class;
};


static gpointer synapse_gui_view_custom_parent_class = NULL;

gpointer synapse_gui_entry_ref (gpointer instance);
void synapse_gui_entry_unref (gpointer instance);
GParamSpec* synapse_gui_param_spec_entry (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void synapse_gui_value_set_entry (GValue* value, gpointer v_object);
void synapse_gui_value_take_entry (GValue* value, gpointer v_object);
gpointer synapse_gui_value_get_entry (const GValue* value);
GType synapse_gui_entry_get_type (void) G_GNUC_CONST;
GType synapse_gui_model_get_type (void) G_GNUC_CONST;
GType synapse_gui_key_combo_config_get_type (void) G_GNUC_CONST;
GType synapse_gui_category_config_get_type (void) G_GNUC_CONST;
GType synapse_gui_icontroller_get_type (void) G_GNUC_CONST;
GType synapse_gui_iview_get_type (void) G_GNUC_CONST;
GType synapse_gui_view_get_type (void) G_GNUC_CONST;
GType synapse_gui_selection_container_get_type (void) G_GNUC_CONST;
GType synapse_gui_result_box_get_type (void) G_GNUC_CONST;
gpointer synapse_gui_utils_color_helper_ref (gpointer instance);
void synapse_gui_utils_color_helper_unref (gpointer instance);
GParamSpec* synapse_gui_utils_param_spec_color_helper (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void synapse_gui_utils_value_set_color_helper (GValue* value, gpointer v_object);
void synapse_gui_utils_value_take_color_helper (GValue* value, gpointer v_object);
gpointer synapse_gui_utils_value_get_color_helper (const GValue* value);
GType synapse_gui_utils_color_helper_get_type (void) G_GNUC_CONST;
GType synapse_gui_htext_selector_get_type (void) G_GNUC_CONST;
GType synapse_gui_fake_button_get_type (void) G_GNUC_CONST;
GType synapse_gui_menu_button_get_type (void) G_GNUC_CONST;
GType synapse_gui_view_custom_get_type (void) G_GNUC_CONST;
GType synapse_gui_smart_label_get_type (void) G_GNUC_CONST;
GType synapse_gui_match_list_view_get_type (void) G_GNUC_CONST;
GType synapse_gui_specific_match_list_get_type (void) G_GNUC_CONST;
GType synapse_gui_menu_throbber_get_type (void) G_GNUC_CONST;
#define SYNAPSE_GUI_VIEW_CUSTOM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYNAPSE_GUI_TYPE_VIEW_CUSTOM, SynapseGuiViewCustomPrivate))
enum  {
	SYNAPSE_GUI_VIEW_CUSTOM_DUMMY_PROPERTY
};
static void synapse_gui_view_custom_real_style_updated (GtkWidget* base);
GType synapse_gui_match_list_view_match_view_renderer_base_get_type (void) G_GNUC_CONST;
GType synapse_gui_match_view_renderer_get_type (void) G_GNUC_CONST;
static void synapse_gui_view_custom_fix_listview_size (SynapseGuiViewCustom* self, SynapseGuiMatchViewRenderer* rend, gint iconsize, const gchar* title, const gchar* desc);
SynapseGuiMatchViewRenderer* synapse_gui_specific_match_list_get_match_renderer (SynapseGuiSpecificMatchList* self);
static void synapse_gui_view_custom_real_build_ui (SynapseGuiView* base);
SynapseGuiSmartLabel* synapse_gui_smart_label_new (void);
SynapseGuiSmartLabel* synapse_gui_smart_label_construct (GType object_type);
SynapseGuiMenuThrobber* synapse_gui_menu_throbber_new (void);
SynapseGuiMenuThrobber* synapse_gui_menu_throbber_construct (GType object_type);
static GtkWidget* synapse_gui_view_custom_create_separator (SynapseGuiViewCustom* self);
SynapseGuiIController* synapse_gui_iview_get_controller (SynapseGuiIView* self);
GType synapse_gui_searching_for_get_type (void) G_GNUC_CONST;
SynapseGuiSpecificMatchList* synapse_gui_specific_match_list_new (SynapseGuiIController* controller, SynapseGuiModel* model, SynapseGuiSearchingFor sf);
SynapseGuiSpecificMatchList* synapse_gui_specific_match_list_construct (GType object_type, SynapseGuiIController* controller, SynapseGuiModel* model, SynapseGuiSearchingFor sf);
void synapse_gui_match_list_view_set_use_base_colors (SynapseGuiMatchListView* self, gboolean value);
static gboolean synapse_gui_view_custom_draw_separator (SynapseGuiViewCustom* self, GtkWidget* separator, cairo_t* ctx);
static gboolean _synapse_gui_view_custom_draw_separator_gtk_widget_draw (GtkWidget* _sender, cairo_t* cr, gpointer self);
void synapse_gui_match_view_renderer_set_icon_size (SynapseGuiMatchViewRenderer* self, gint value);
void synapse_gui_match_view_renderer_set_title_markup (SynapseGuiMatchViewRenderer* self, const gchar* value);
void synapse_gui_match_view_renderer_set_description_markup (SynapseGuiMatchViewRenderer* self, const gchar* value);
static gboolean synapse_gui_view_custom_real_is_list_visible (SynapseGuiView* base);
static void synapse_gui_view_custom_real_set_list_visible (SynapseGuiView* base, gboolean visible);
void synapse_gui_match_list_view_set_min_visible_rows (SynapseGuiMatchListView* self, gint value);
static void synapse_gui_view_custom_real_set_throbber_visible (SynapseGuiView* base, gboolean visible);
void synapse_gui_menu_throbber_set_active (SynapseGuiMenuThrobber* self, gboolean value);
static void synapse_gui_view_custom_real_update_searching_for (SynapseGuiView* base);
void synapse_gui_specific_match_list_update_searching_for (SynapseGuiSpecificMatchList* self);
gint synapse_gui_match_list_view_get_min_visible_rows (SynapseGuiMatchListView* self);
static void synapse_gui_view_custom_update_labels (SynapseGuiViewCustom* self);
gboolean synapse_gui_model_has_results (SynapseGuiModel* self);
void synapse_gui_smart_label_set_markup (SynapseGuiSmartLabel* self, const gchar* m);
SynapseGuiEntry* synapse_gui_model_get_actual_focus (SynapseGuiModel* self);
gconstpointer synapse_gui_entry_get_key (SynapseGuiEntry* self);
void synapse_gui_smart_label_set_text (SynapseGuiSmartLabel* self, const gchar* s);
static void synapse_gui_view_custom_real_update_selected_category (SynapseGuiView* base);
void synapse_gui_htext_selector_set_selected (SynapseGuiHTextSelector* self, gint value);
static void synapse_gui_view_custom_real_paint_background (SynapseGuiView* base, cairo_t* ctx);
void synapse_gui_utils_cairo_make_shadow_for_rect (cairo_t* ctx, gdouble x1, gdouble y1, gdouble w, gdouble h, gdouble rad, gdouble r, gdouble g, gdouble b, gdouble size);
void synapse_gui_utils_cairo_rounded_rect (cairo_t* ctx, gdouble x, gdouble y, gdouble w, gdouble h, gdouble r);
static void synapse_gui_view_custom_real_update_focused_source (SynapseGuiView* base, SynapseGuiEntry* m);
gconstpointer synapse_gui_entry_get_value (SynapseGuiEntry* self);
void synapse_gui_match_list_view_set_indexes (SynapseGuiMatchListView* self, gint targetted, gint selected);
static void synapse_gui_view_custom_real_update_focused_action (SynapseGuiView* base, SynapseGuiEntry* m);
static void synapse_gui_view_custom_real_update_focused_target (SynapseGuiView* base, SynapseGuiEntry* m);
static void synapse_gui_view_custom_real_update_sources (SynapseGuiView* base, GeeList* list);
void synapse_gui_match_list_view_set_list (SynapseGuiMatchListView* self, GeeList* list, gint targetted_index, gint selected_index);
gboolean synapse_gui_icontroller_is_in_initial_state (SynapseGuiIController* self);
static void synapse_gui_view_custom_real_update_actions (SynapseGuiView* base, GeeList* list);
static void synapse_gui_view_custom_real_update_targets (SynapseGuiView* base, GeeList* list);
SynapseGuiViewCustom* synapse_gui_view_custom_new (void);
SynapseGuiViewCustom* synapse_gui_view_custom_construct (GType object_type);
SynapseGuiView* synapse_gui_view_new (void);
SynapseGuiView* synapse_gui_view_construct (GType object_type);
static GObject * synapse_gui_view_custom_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void synapse_gui_view_custom_finalize (GObject* obj);


static void synapse_gui_view_custom_real_style_updated (GtkWidget* base) {
	SynapseGuiViewCustom * self;
	gint width = 0;
	gint icon_size = 0;
	gchar* tmax = NULL;
	gchar* dmax = NULL;
	GtkBox* _tmp0_ = NULL;
	SynapseGuiSpecificMatchList* _tmp1_ = NULL;
	SynapseGuiMatchViewRenderer* _tmp2_ = NULL;
	SynapseGuiMatchViewRenderer* _tmp3_ = NULL;
	SynapseGuiSpecificMatchList* _tmp4_ = NULL;
	SynapseGuiMatchViewRenderer* _tmp5_ = NULL;
	SynapseGuiMatchViewRenderer* _tmp6_ = NULL;
	SynapseGuiSpecificMatchList* _tmp7_ = NULL;
	SynapseGuiMatchViewRenderer* _tmp8_ = NULL;
	SynapseGuiMatchViewRenderer* _tmp9_ = NULL;
#line 59 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = (SynapseGuiViewCustom*) base;
#line 61 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	GTK_WIDGET_CLASS (synapse_gui_view_custom_parent_class)->style_updated ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, SYNAPSE_GUI_TYPE_VIEW, SynapseGuiView));
#line 65 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_widget_style_get ((GtkWidget*) self, "ui-width", &width, "icon-size", &icon_size, "title-size", &tmax, "description-size", &dmax, NULL);
#line 68 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = self->priv->container;
#line 68 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_widget_set_size_request ((GtkWidget*) _tmp0_, width, -1);
#line 69 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = self->priv->results_sources;
#line 69 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp2_ = synapse_gui_specific_match_list_get_match_renderer (_tmp1_);
#line 69 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp3_ = _tmp2_;
#line 69 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_view_custom_fix_listview_size (self, _tmp3_, icon_size, tmax, dmax);
#line 69 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (_tmp3_);
#line 70 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp4_ = self->priv->results_actions;
#line 70 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp5_ = synapse_gui_specific_match_list_get_match_renderer (_tmp4_);
#line 70 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp6_ = _tmp5_;
#line 70 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_view_custom_fix_listview_size (self, _tmp6_, icon_size, tmax, dmax);
#line 70 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (_tmp6_);
#line 71 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp7_ = self->priv->results_targets;
#line 71 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp8_ = synapse_gui_specific_match_list_get_match_renderer (_tmp7_);
#line 71 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp9_ = _tmp8_;
#line 71 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_view_custom_fix_listview_size (self, _tmp9_, icon_size, tmax, dmax);
#line 71 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (_tmp9_);
#line 59 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_free0 (dmax);
#line 59 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_free0 (tmax);
#line 523 "view-custom.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 110 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	return self ? g_object_ref (self) : NULL;
#line 530 "view-custom.c"
}


static void synapse_gui_view_custom_real_build_ui (SynapseGuiView* base) {
	SynapseGuiViewCustom * self;
	GtkBox* _tmp0_ = NULL;
	SynapseGuiSmartLabel* _tmp1_ = NULL;
	SynapseGuiSmartLabel* _tmp2_ = NULL;
	SynapseGuiSmartLabel* _tmp3_ = NULL;
	SynapseGuiSmartLabel* _tmp4_ = NULL;
	SynapseGuiSmartLabel* _tmp5_ = NULL;
	SynapseGuiSmartLabel* _tmp6_ = NULL;
	GtkBox* hb_status = NULL;
	GtkBox* _tmp7_ = NULL;
	SynapseGuiSmartLabel* _tmp8_ = NULL;
	SynapseGuiSmartLabel* _tmp9_ = NULL;
	SynapseGuiSmartLabel* _tmp10_ = NULL;
	GtkBox* categories_hbox = NULL;
	GtkBox* _tmp11_ = NULL;
	SynapseGuiMenuThrobber* _tmp12_ = NULL;
	SynapseGuiMenuThrobber* _tmp13_ = NULL;
	SynapseGuiMenuButton* _tmp14_ = NULL;
	SynapseGuiMenuThrobber* _tmp15_ = NULL;
	SynapseGuiHTextSelector* _tmp16_ = NULL;
	SynapseGuiMenuThrobber* _tmp17_ = NULL;
	GtkBox* _tmp18_ = NULL;
	GtkBox* _tmp19_ = NULL;
	GtkWidget* _tmp20_ = NULL;
	GtkWidget* _tmp21_ = NULL;
	SynapseGuiIController* _tmp22_ = NULL;
	SynapseGuiIController* _tmp23_ = NULL;
	SynapseGuiModel* _tmp24_ = NULL;
	SynapseGuiSpecificMatchList* _tmp25_ = NULL;
	SynapseGuiIController* _tmp26_ = NULL;
	SynapseGuiIController* _tmp27_ = NULL;
	SynapseGuiModel* _tmp28_ = NULL;
	SynapseGuiSpecificMatchList* _tmp29_ = NULL;
	SynapseGuiIController* _tmp30_ = NULL;
	SynapseGuiIController* _tmp31_ = NULL;
	SynapseGuiModel* _tmp32_ = NULL;
	SynapseGuiSpecificMatchList* _tmp33_ = NULL;
	SynapseGuiSpecificMatchList* _tmp34_ = NULL;
	SynapseGuiSpecificMatchList* _tmp35_ = NULL;
	SynapseGuiSpecificMatchList* _tmp36_ = NULL;
	SynapseGuiSpecificMatchList* _tmp37_ = NULL;
	SynapseGuiMatchViewRenderer* _tmp38_ = NULL;
	SynapseGuiMatchViewRenderer* _tmp39_ = NULL;
	SynapseGuiSpecificMatchList* _tmp40_ = NULL;
	SynapseGuiMatchViewRenderer* _tmp41_ = NULL;
	SynapseGuiMatchViewRenderer* _tmp42_ = NULL;
	SynapseGuiSpecificMatchList* _tmp43_ = NULL;
	SynapseGuiMatchViewRenderer* _tmp44_ = NULL;
	SynapseGuiMatchViewRenderer* _tmp45_ = NULL;
	GtkBox* _tmp46_ = NULL;
	SynapseGuiSpecificMatchList* _tmp47_ = NULL;
	GtkBox* _tmp48_ = NULL;
	GtkWidget* _tmp49_ = NULL;
	GtkWidget* _tmp50_ = NULL;
	GtkBox* _tmp51_ = NULL;
	GtkBox* _tmp52_ = NULL;
	SynapseGuiSpecificMatchList* _tmp53_ = NULL;
	GtkBox* _tmp54_ = NULL;
	GtkWidget* _tmp55_ = NULL;
	GtkWidget* _tmp56_ = NULL;
	GtkBox* _tmp57_ = NULL;
	GtkBox* _tmp58_ = NULL;
	GtkBox* _tmp59_ = NULL;
	GtkBox* _tmp60_ = NULL;
	SynapseGuiSpecificMatchList* _tmp61_ = NULL;
	GtkBox* _tmp62_ = NULL;
	GtkWidget* _tmp63_ = NULL;
	GtkWidget* _tmp64_ = NULL;
	GtkBox* _tmp65_ = NULL;
	GtkBox* _tmp66_ = NULL;
	GtkBox* _tmp67_ = NULL;
	GtkBox* _tmp68_ = NULL;
	GtkBox* _tmp69_ = NULL;
	GtkBox* _tmp70_ = NULL;
#line 88 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = (SynapseGuiViewCustom*) base;
#line 90 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
#line 90 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_ref_sink (_tmp0_);
#line 90 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->container);
#line 90 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self->priv->container = _tmp0_;
#line 92 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = synapse_gui_smart_label_new ();
#line 92 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_ref_sink (_tmp1_);
#line 92 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->status);
#line 92 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self->priv->status = _tmp1_;
#line 93 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp2_ = synapse_gui_smart_label_new ();
#line 93 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_ref_sink (_tmp2_);
#line 93 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->logo);
#line 93 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self->priv->logo = _tmp2_;
#line 94 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp3_ = synapse_gui_smart_label_new ();
#line 94 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_ref_sink (_tmp3_);
#line 94 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->search);
#line 94 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self->priv->search = _tmp3_;
#line 96 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp4_ = self->priv->search;
#line 96 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_set ((GtkMisc*) _tmp4_, "xalign", 0.5f, NULL);
#line 97 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp5_ = self->priv->logo;
#line 97 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_set ((GtkMisc*) _tmp5_, "xalign", 1.0f, NULL);
#line 98 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp6_ = self->priv->status;
#line 98 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_set ((GtkMisc*) _tmp6_, "xalign", 0.0f, NULL);
#line 100 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp7_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
#line 100 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_ref_sink (_tmp7_);
#line 100 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	hb_status = _tmp7_;
#line 101 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_set_homogeneous (hb_status, TRUE);
#line 102 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp8_ = self->priv->status;
#line 102 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_pack_start (hb_status, (GtkWidget*) _tmp8_, TRUE, TRUE, (guint) 0);
#line 103 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp9_ = self->priv->search;
#line 103 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_pack_start (hb_status, (GtkWidget*) _tmp9_, TRUE, TRUE, (guint) 0);
#line 104 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp10_ = self->priv->logo;
#line 104 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_pack_start (hb_status, (GtkWidget*) _tmp10_, TRUE, TRUE, (guint) 0);
#line 107 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp11_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
#line 107 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_ref_sink (_tmp11_);
#line 107 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	categories_hbox = _tmp11_;
#line 109 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp12_ = synapse_gui_menu_throbber_new ();
#line 109 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_ref_sink (_tmp12_);
#line 109 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->menuthrobber);
#line 109 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self->priv->menuthrobber = _tmp12_;
#line 110 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp13_ = self->priv->menuthrobber;
#line 110 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp14_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp13_, SYNAPSE_GUI_TYPE_MENU_BUTTON, SynapseGuiMenuButton));
#line 110 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (((SynapseGuiView*) self)->menu);
#line 110 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	((SynapseGuiView*) self)->menu = _tmp14_;
#line 111 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp15_ = self->priv->menuthrobber;
#line 111 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_widget_set_size_request ((GtkWidget*) _tmp15_, 14, 14);
#line 113 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp16_ = ((SynapseGuiView*) self)->flag_selector;
#line 113 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_pack_start (categories_hbox, (GtkWidget*) _tmp16_, TRUE, TRUE, (guint) 0);
#line 114 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp17_ = self->priv->menuthrobber;
#line 114 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_pack_start (categories_hbox, (GtkWidget*) _tmp17_, FALSE, TRUE, (guint) 0);
#line 116 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp18_ = self->priv->container;
#line 116 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_pack_start (_tmp18_, (GtkWidget*) categories_hbox, FALSE, FALSE, (guint) 2);
#line 117 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp19_ = self->priv->container;
#line 117 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp20_ = synapse_gui_view_custom_create_separator (self);
#line 117 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp21_ = _tmp20_;
#line 117 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_pack_start (_tmp19_, _tmp21_, FALSE, TRUE, (guint) 0);
#line 117 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (_tmp21_);
#line 120 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp22_ = synapse_gui_iview_get_controller ((SynapseGuiIView*) self);
#line 120 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp23_ = _tmp22_;
#line 120 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp24_ = ((SynapseGuiView*) self)->model;
#line 120 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp25_ = synapse_gui_specific_match_list_new (_tmp23_, _tmp24_, SYNAPSE_GUI_SEARCHING_FOR_SOURCES);
#line 120 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_ref_sink (_tmp25_);
#line 120 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->results_sources);
#line 120 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self->priv->results_sources = _tmp25_;
#line 121 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp26_ = synapse_gui_iview_get_controller ((SynapseGuiIView*) self);
#line 121 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp27_ = _tmp26_;
#line 121 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp28_ = ((SynapseGuiView*) self)->model;
#line 121 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp29_ = synapse_gui_specific_match_list_new (_tmp27_, _tmp28_, SYNAPSE_GUI_SEARCHING_FOR_ACTIONS);
#line 121 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_ref_sink (_tmp29_);
#line 121 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->results_actions);
#line 121 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self->priv->results_actions = _tmp29_;
#line 122 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp30_ = synapse_gui_iview_get_controller ((SynapseGuiIView*) self);
#line 122 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp31_ = _tmp30_;
#line 122 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp32_ = ((SynapseGuiView*) self)->model;
#line 122 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp33_ = synapse_gui_specific_match_list_new (_tmp31_, _tmp32_, SYNAPSE_GUI_SEARCHING_FOR_TARGETS);
#line 122 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_ref_sink (_tmp33_);
#line 122 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->results_targets);
#line 122 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self->priv->results_targets = _tmp33_;
#line 123 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp34_ = self->priv->results_sources;
#line 123 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_match_list_view_set_use_base_colors ((SynapseGuiMatchListView*) _tmp34_, FALSE);
#line 124 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp35_ = self->priv->results_actions;
#line 124 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_match_list_view_set_use_base_colors ((SynapseGuiMatchListView*) _tmp35_, FALSE);
#line 125 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp36_ = self->priv->results_targets;
#line 125 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_match_list_view_set_use_base_colors ((SynapseGuiMatchListView*) _tmp36_, FALSE);
#line 126 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp37_ = self->priv->results_sources;
#line 126 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp38_ = synapse_gui_specific_match_list_get_match_renderer (_tmp37_);
#line 126 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp39_ = _tmp38_;
#line 126 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_view_custom_fix_listview_size (self, _tmp39_, 48, "large", "medium");
#line 126 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (_tmp39_);
#line 127 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp40_ = self->priv->results_actions;
#line 127 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp41_ = synapse_gui_specific_match_list_get_match_renderer (_tmp40_);
#line 127 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp42_ = _tmp41_;
#line 127 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_view_custom_fix_listview_size (self, _tmp42_, 48, "large", "medium");
#line 127 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (_tmp42_);
#line 128 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp43_ = self->priv->results_targets;
#line 128 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp44_ = synapse_gui_specific_match_list_get_match_renderer (_tmp43_);
#line 128 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp45_ = _tmp44_;
#line 128 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_view_custom_fix_listview_size (self, _tmp45_, 48, "large", "medium");
#line 128 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (_tmp45_);
#line 130 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp46_ = self->priv->container;
#line 130 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp47_ = self->priv->results_sources;
#line 130 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_pack_start (_tmp46_, (GtkWidget*) _tmp47_, TRUE, TRUE, (guint) 0);
#line 131 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp48_ = self->priv->container;
#line 131 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp49_ = synapse_gui_view_custom_create_separator (self);
#line 131 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp50_ = _tmp49_;
#line 131 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_pack_start (_tmp48_, _tmp50_, FALSE, TRUE, (guint) 0);
#line 131 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (_tmp50_);
#line 133 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp51_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
#line 133 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_ref_sink (_tmp51_);
#line 133 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->action_box);
#line 133 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self->priv->action_box = _tmp51_;
#line 134 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp52_ = self->priv->action_box;
#line 134 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp53_ = self->priv->results_actions;
#line 134 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_pack_start (_tmp52_, (GtkWidget*) _tmp53_, FALSE, TRUE, (guint) 0);
#line 135 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp54_ = self->priv->action_box;
#line 135 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp55_ = synapse_gui_view_custom_create_separator (self);
#line 135 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp56_ = _tmp55_;
#line 135 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_pack_start (_tmp54_, _tmp56_, FALSE, TRUE, (guint) 0);
#line 135 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (_tmp56_);
#line 136 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp57_ = self->priv->container;
#line 136 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp58_ = self->priv->action_box;
#line 136 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_pack_start (_tmp57_, (GtkWidget*) _tmp58_, FALSE, TRUE, (guint) 0);
#line 138 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp59_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
#line 138 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_ref_sink (_tmp59_);
#line 138 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->target_box);
#line 138 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self->priv->target_box = _tmp59_;
#line 139 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp60_ = self->priv->target_box;
#line 139 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp61_ = self->priv->results_targets;
#line 139 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_pack_start (_tmp60_, (GtkWidget*) _tmp61_, FALSE, TRUE, (guint) 0);
#line 140 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp62_ = self->priv->target_box;
#line 140 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp63_ = synapse_gui_view_custom_create_separator (self);
#line 140 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp64_ = _tmp63_;
#line 140 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_pack_start (_tmp62_, _tmp64_, FALSE, TRUE, (guint) 0);
#line 140 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (_tmp64_);
#line 141 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp65_ = self->priv->container;
#line 141 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp66_ = self->priv->target_box;
#line 141 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_pack_start (_tmp65_, (GtkWidget*) _tmp66_, FALSE, TRUE, (guint) 0);
#line 143 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp67_ = self->priv->container;
#line 143 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_box_pack_start (_tmp67_, (GtkWidget*) hb_status, FALSE, FALSE, (guint) 2);
#line 145 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp68_ = self->priv->container;
#line 145 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp68_);
#line 147 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp69_ = self->priv->container;
#line 147 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_widget_set_size_request ((GtkWidget*) _tmp69_, 500, -1);
#line 148 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp70_ = self->priv->container;
#line 148 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp70_);
#line 88 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (categories_hbox);
#line 88 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (hb_status);
#line 903 "view-custom.c"
}


static gboolean _synapse_gui_view_custom_draw_separator_gtk_widget_draw (GtkWidget* _sender, cairo_t* cr, gpointer self) {
	gboolean result;
	result = synapse_gui_view_custom_draw_separator ((SynapseGuiViewCustom*) self, _sender, cr);
#line 159 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	return result;
#line 912 "view-custom.c"
}


static GtkWidget* synapse_gui_view_custom_create_separator (SynapseGuiViewCustom* self) {
	GtkWidget* result = NULL;
	GtkEventBox* separator = NULL;
	GtkEventBox* _tmp0_ = NULL;
	GtkStyleContext* _tmp1_ = NULL;
	GtkStyleContext* _tmp2_ = NULL;
#line 152 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 154 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = (GtkEventBox*) gtk_event_box_new ();
#line 154 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_ref_sink (_tmp0_);
#line 154 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	separator = _tmp0_;
#line 155 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_set ((GtkWidget*) separator, "height-request", 2, NULL);
#line 156 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_object_set ((GtkWidget*) separator, "width-request", 120, NULL);
#line 157 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = gtk_widget_get_style_context ((GtkWidget*) separator);
#line 157 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_style_context_add_class (_tmp1_, GTK_STYLE_CLASS_SEPARATOR);
#line 158 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp2_ = gtk_widget_get_style_context ((GtkWidget*) separator);
#line 158 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_style_context_add_class (_tmp2_, GTK_STYLE_CLASS_HORIZONTAL);
#line 159 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_signal_connect_object ((GtkWidget*) separator, "draw", (GCallback) _synapse_gui_view_custom_draw_separator_gtk_widget_draw, self, 0);
#line 160 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	result = (GtkWidget*) separator;
#line 160 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	return result;
#line 948 "view-custom.c"
}


static gboolean synapse_gui_view_custom_draw_separator (SynapseGuiViewCustom* self, GtkWidget* separator, cairo_t* ctx) {
	gboolean result = FALSE;
	GtkWidget* _tmp0_ = NULL;
	GtkStyleContext* _tmp1_ = NULL;
	cairo_t* _tmp2_ = NULL;
	GtkWidget* _tmp3_ = NULL;
	gint _tmp4_ = 0;
#line 163 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 163 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_return_val_if_fail (separator != NULL, FALSE);
#line 163 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_return_val_if_fail (ctx != NULL, FALSE);
#line 165 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = separator;
#line 165 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = gtk_widget_get_style_context (_tmp0_);
#line 165 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp2_ = ctx;
#line 165 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp3_ = separator;
#line 165 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp4_ = gtk_widget_get_allocated_width (_tmp3_);
#line 165 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_render_frame (_tmp1_, _tmp2_, (gdouble) 0, (gdouble) 0, (gdouble) _tmp4_, (gdouble) 2);
#line 166 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	result = FALSE;
#line 166 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	return result;
#line 981 "view-custom.c"
}


static void synapse_gui_view_custom_fix_listview_size (SynapseGuiViewCustom* self, SynapseGuiMatchViewRenderer* rend, gint iconsize, const gchar* title, const gchar* desc) {
	SynapseGuiMatchViewRenderer* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	SynapseGuiMatchViewRenderer* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	SynapseGuiMatchViewRenderer* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
#line 169 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_return_if_fail (self != NULL);
#line 169 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_return_if_fail (rend != NULL);
#line 169 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_return_if_fail (title != NULL);
#line 169 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_return_if_fail (desc != NULL);
#line 171 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = rend;
#line 171 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = iconsize;
#line 171 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_match_view_renderer_set_icon_size (_tmp0_, _tmp1_);
#line 172 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp2_ = rend;
#line 172 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp3_ = title;
#line 172 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp4_ = g_strdup_printf ("<span size=\"%s\"><b>%%s</b></span>", _tmp3_);
#line 172 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp5_ = _tmp4_;
#line 172 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_match_view_renderer_set_title_markup (_tmp2_, _tmp5_);
#line 172 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_free0 (_tmp5_);
#line 173 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp6_ = rend;
#line 173 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp7_ = desc;
#line 173 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp8_ = g_strdup_printf ("<span size=\"%s\">%%s</span>", _tmp7_);
#line 173 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp9_ = _tmp8_;
#line 173 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_match_view_renderer_set_description_markup (_tmp6_, _tmp9_);
#line 173 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_free0 (_tmp9_);
#line 1034 "view-custom.c"
}


static gboolean synapse_gui_view_custom_real_is_list_visible (SynapseGuiView* base) {
	SynapseGuiViewCustom * self;
	gboolean result = FALSE;
#line 176 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = (SynapseGuiViewCustom*) base;
#line 178 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	result = TRUE;
#line 178 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	return result;
#line 1047 "view-custom.c"
}


static void synapse_gui_view_custom_real_set_list_visible (SynapseGuiView* base, gboolean visible) {
	SynapseGuiViewCustom * self;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gint _tmp2_ = 0;
	gboolean _tmp3_ = FALSE;
	SynapseGuiSpecificMatchList* _tmp4_ = NULL;
#line 181 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = (SynapseGuiViewCustom*) base;
#line 183 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = gtk_widget_get_visible ((GtkWidget*) self);
#line 183 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = _tmp0_;
#line 183 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	if (_tmp1_) {
#line 183 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		return;
#line 1068 "view-custom.c"
	}
#line 184 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp3_ = visible;
#line 184 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	if (_tmp3_) {
#line 184 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp2_ = 7;
#line 1076 "view-custom.c"
	} else {
#line 184 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp2_ = 1;
#line 1080 "view-custom.c"
	}
#line 184 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp4_ = self->priv->results_sources;
#line 184 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_match_list_view_set_min_visible_rows ((SynapseGuiMatchListView*) _tmp4_, _tmp2_);
#line 1086 "view-custom.c"
}


static void synapse_gui_view_custom_real_set_throbber_visible (SynapseGuiView* base, gboolean visible) {
	SynapseGuiViewCustom * self;
	SynapseGuiMenuThrobber* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
#line 187 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = (SynapseGuiViewCustom*) base;
#line 189 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = self->priv->menuthrobber;
#line 189 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = visible;
#line 189 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_menu_throbber_set_active (_tmp0_, _tmp1_);
#line 1102 "view-custom.c"
}


static void synapse_gui_view_custom_real_update_searching_for (SynapseGuiView* base) {
	SynapseGuiViewCustom * self;
	SynapseGuiSpecificMatchList* _tmp0_ = NULL;
	SynapseGuiSpecificMatchList* _tmp1_ = NULL;
	SynapseGuiSpecificMatchList* _tmp2_ = NULL;
	GtkBox* _tmp3_ = NULL;
	SynapseGuiSpecificMatchList* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
#line 192 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = (SynapseGuiViewCustom*) base;
#line 194 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = self->priv->results_sources;
#line 194 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_specific_match_list_update_searching_for (_tmp0_);
#line 195 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = self->priv->results_actions;
#line 195 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_specific_match_list_update_searching_for (_tmp1_);
#line 196 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp2_ = self->priv->results_targets;
#line 196 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_specific_match_list_update_searching_for (_tmp2_);
#line 197 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp3_ = self->priv->target_box;
#line 197 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp4_ = self->priv->results_targets;
#line 197 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp5_ = synapse_gui_match_list_view_get_min_visible_rows ((SynapseGuiMatchListView*) _tmp4_);
#line 197 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp6_ = _tmp5_;
#line 197 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp3_, _tmp6_ > 0);
#line 198 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_view_custom_update_labels (self);
#line 1141 "view-custom.c"
}


static void synapse_gui_view_custom_update_labels (SynapseGuiViewCustom* self) {
	SynapseGuiModel* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	SynapseGuiSmartLabel* _tmp19_ = NULL;
	SynapseGuiModel* _tmp20_ = NULL;
	gchar** _tmp21_ = NULL;
	gint _tmp21__length1 = 0;
	SynapseGuiModel* _tmp22_ = NULL;
	SynapseGuiSearchingFor _tmp23_ = 0;
	const gchar* _tmp24_ = NULL;
#line 201 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_return_if_fail (self != NULL);
#line 203 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = ((SynapseGuiView*) self)->model;
#line 203 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = synapse_gui_model_has_results (_tmp0_);
#line 203 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	if (_tmp1_) {
#line 1163 "view-custom.c"
		SynapseGuiSmartLabel* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		SynapseGuiModel* _tmp4_ = NULL;
		SynapseGuiEntry* _tmp5_ = NULL;
		SynapseGuiEntry* _tmp6_ = NULL;
		gconstpointer _tmp7_ = NULL;
		gint _tmp8_ = 0;
		SynapseGuiModel* _tmp9_ = NULL;
		GeeList** _tmp10_ = NULL;
		gint _tmp10__length1 = 0;
		SynapseGuiModel* _tmp11_ = NULL;
		SynapseGuiSearchingFor _tmp12_ = 0;
		GeeList* _tmp13_ = NULL;
		gint _tmp14_ = 0;
		gint _tmp15_ = 0;
		gchar* _tmp16_ = NULL;
		gchar* _tmp17_ = NULL;
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp2_ = self->priv->status;
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp3_ = _ ("<b>%d of %d</b>");
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp4_ = ((SynapseGuiView*) self)->model;
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp5_ = synapse_gui_model_get_actual_focus (_tmp4_);
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp6_ = _tmp5_;
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp7_ = synapse_gui_entry_get_key (_tmp6_);
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp8_ = _tmp7_;
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp9_ = ((SynapseGuiView*) self)->model;
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp10_ = _tmp9_->results;
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp10__length1 = _tmp9_->results_length1;
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp11_ = ((SynapseGuiView*) self)->model;
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp12_ = _tmp11_->searching_for;
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp13_ = _tmp10_[_tmp12_];
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp14_ = gee_collection_get_size ((GeeCollection*) _tmp13_);
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp15_ = _tmp14_;
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp16_ = g_markup_printf_escaped (_tmp3_, ((gint) ((gintptr) _tmp8_)) + 1, _tmp15_);
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp17_ = _tmp16_;
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		synapse_gui_smart_label_set_markup (_tmp2_, _tmp17_);
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_g_free0 (_tmp17_);
#line 205 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_synapse_gui_entry_unref0 (_tmp6_);
#line 1221 "view-custom.c"
	} else {
		SynapseGuiSmartLabel* _tmp18_ = NULL;
#line 209 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp18_ = self->priv->status;
#line 209 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		synapse_gui_smart_label_set_text (_tmp18_, "");
#line 1228 "view-custom.c"
	}
#line 211 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp19_ = self->priv->search;
#line 211 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp20_ = ((SynapseGuiView*) self)->model;
#line 211 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp21_ = _tmp20_->query;
#line 211 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp21__length1 = _tmp20_->query_length1;
#line 211 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp22_ = ((SynapseGuiView*) self)->model;
#line 211 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp23_ = _tmp22_->searching_for;
#line 211 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp24_ = _tmp21_[_tmp23_];
#line 211 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_smart_label_set_text (_tmp19_, _tmp24_);
#line 1246 "view-custom.c"
}


static void synapse_gui_view_custom_real_update_selected_category (SynapseGuiView* base) {
	SynapseGuiViewCustom * self;
	SynapseGuiHTextSelector* _tmp0_ = NULL;
	SynapseGuiModel* _tmp1_ = NULL;
	gint _tmp2_ = 0;
#line 214 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = (SynapseGuiViewCustom*) base;
#line 216 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = ((SynapseGuiView*) self)->flag_selector;
#line 216 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = ((SynapseGuiView*) self)->model;
#line 216 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp2_ = _tmp1_->selected_category;
#line 216 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_htext_selector_set_selected (_tmp0_, _tmp2_);
#line 1265 "view-custom.c"
}


static void synapse_gui_view_custom_real_paint_background (SynapseGuiView* base, cairo_t* ctx) {
	SynapseGuiViewCustom * self;
	GtkAllocation container_allocation = {0};
	GtkBox* _tmp0_ = NULL;
	GtkAllocation _tmp1_ = {0};
	gint width = 0;
	GtkAllocation _tmp2_ = {0};
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint height = 0;
	GtkAllocation _tmp5_ = {0};
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	cairo_t* _tmp8_ = NULL;
	GtkAllocation _tmp9_ = {0};
	gint _tmp10_ = 0;
	gint _tmp11_ = 0;
	GtkAllocation _tmp12_ = {0};
	gint _tmp13_ = 0;
	gint _tmp14_ = 0;
	gboolean _tmp15_ = FALSE;
	cairo_t* _tmp22_ = NULL;
	cairo_t* _tmp23_ = NULL;
	gint _tmp24_ = 0;
	gint _tmp25_ = 0;
	cairo_t* _tmp26_ = NULL;
	cairo_t* _tmp27_ = NULL;
	cairo_t* _tmp28_ = NULL;
	cairo_t* _tmp29_ = NULL;
	cairo_t* _tmp30_ = NULL;
#line 219 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = (SynapseGuiViewCustom*) base;
#line 219 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_return_if_fail (ctx != NULL);
#line 222 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = self->priv->container;
#line 222 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_widget_get_allocation ((GtkWidget*) _tmp0_, &_tmp1_);
#line 222 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	container_allocation = _tmp1_;
#line 224 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp2_ = container_allocation;
#line 224 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp3_ = _tmp2_.width;
#line 224 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp4_ = ((SynapseGuiView*) self)->BORDER_RADIUS;
#line 224 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	width = _tmp3_ + (_tmp4_ * 2);
#line 225 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp5_ = container_allocation;
#line 225 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp6_ = _tmp5_.height;
#line 225 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp7_ = ((SynapseGuiView*) self)->BORDER_RADIUS;
#line 225 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	height = _tmp6_ + (_tmp7_ * 2);
#line 226 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp8_ = ctx;
#line 226 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp9_ = container_allocation;
#line 226 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp10_ = _tmp9_.x;
#line 226 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp11_ = ((SynapseGuiView*) self)->BORDER_RADIUS;
#line 226 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp12_ = container_allocation;
#line 226 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp13_ = _tmp12_.y;
#line 226 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp14_ = ((SynapseGuiView*) self)->BORDER_RADIUS;
#line 226 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	cairo_translate (_tmp8_, (gdouble) (_tmp10_ - _tmp11_), (gdouble) (_tmp13_ - _tmp14_));
#line 227 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp15_ = gtk_widget_is_composited ((GtkWidget*) self);
#line 227 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	if (_tmp15_) {
#line 1345 "view-custom.c"
		cairo_t* _tmp16_ = NULL;
		cairo_t* _tmp17_ = NULL;
		cairo_t* _tmp18_ = NULL;
		gint _tmp19_ = 0;
		gint _tmp20_ = 0;
		cairo_t* _tmp21_ = NULL;
#line 229 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp16_ = ctx;
#line 229 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		cairo_translate (_tmp16_, 0.5, 0.5);
#line 230 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp17_ = ctx;
#line 230 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		cairo_set_operator (_tmp17_, CAIRO_OPERATOR_OVER);
#line 231 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp18_ = ctx;
#line 231 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp19_ = width;
#line 231 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp20_ = height;
#line 231 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		synapse_gui_utils_cairo_make_shadow_for_rect (_tmp18_, (gdouble) 0, (gdouble) 0, (gdouble) (_tmp19_ - 1), (gdouble) (_tmp20_ - 1), (gdouble) 0, (gdouble) 0, (gdouble) 0, (gdouble) 0, (gdouble) 6);
#line 233 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp21_ = ctx;
#line 233 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		cairo_translate (_tmp21_, -0.5, -0.5);
#line 1372 "view-custom.c"
	}
#line 235 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp22_ = ctx;
#line 235 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	cairo_save (_tmp22_);
#line 241 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp23_ = ctx;
#line 241 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp24_ = width;
#line 241 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp25_ = height;
#line 241 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_utils_cairo_rounded_rect (_tmp23_, (gdouble) 0, (gdouble) 0, (gdouble) _tmp24_, (gdouble) _tmp25_, (gdouble) 0);
#line 243 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp26_ = ctx;
#line 243 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	cairo_set_source_rgba (_tmp26_, 0.95, 0.95, 0.95, 0.86);
#line 244 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp27_ = ctx;
#line 244 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	cairo_set_operator (_tmp27_, CAIRO_OPERATOR_SOURCE);
#line 245 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp28_ = ctx;
#line 245 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	cairo_clip (_tmp28_);
#line 246 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp29_ = ctx;
#line 246 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	cairo_paint (_tmp29_);
#line 247 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp30_ = ctx;
#line 247 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	cairo_restore (_tmp30_);
#line 1406 "view-custom.c"
}


static void synapse_gui_view_custom_real_update_focused_source (SynapseGuiView* base, SynapseGuiEntry* m) {
	SynapseGuiViewCustom * self;
	SynapseGuiEntry* _tmp0_ = NULL;
	gconstpointer _tmp1_ = NULL;
	SynapseMatch* _tmp2_ = NULL;
	SynapseGuiModel* _tmp10_ = NULL;
	SynapseGuiSearchingFor _tmp11_ = 0;
#line 250 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = (SynapseGuiViewCustom*) base;
#line 250 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_return_if_fail (m != NULL);
#line 252 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = m;
#line 252 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = synapse_gui_entry_get_value (_tmp0_);
#line 252 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp2_ = _tmp1_;
#line 252 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	if (((SynapseMatch*) _tmp2_) != NULL) {
#line 1429 "view-custom.c"
		SynapseGuiSpecificMatchList* _tmp3_ = NULL;
		SynapseGuiEntry* _tmp4_ = NULL;
		gconstpointer _tmp5_ = NULL;
		gint _tmp6_ = 0;
		SynapseGuiEntry* _tmp7_ = NULL;
		gconstpointer _tmp8_ = NULL;
		gint _tmp9_ = 0;
#line 252 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp3_ = self->priv->results_sources;
#line 252 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp4_ = m;
#line 252 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp5_ = synapse_gui_entry_get_key (_tmp4_);
#line 252 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp6_ = _tmp5_;
#line 252 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp7_ = m;
#line 252 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp8_ = synapse_gui_entry_get_key (_tmp7_);
#line 252 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp9_ = _tmp8_;
#line 252 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		synapse_gui_match_list_view_set_indexes ((SynapseGuiMatchListView*) _tmp3_, (gint) ((gintptr) _tmp6_), (gint) ((gintptr) _tmp9_));
#line 1453 "view-custom.c"
	}
#line 253 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp10_ = ((SynapseGuiView*) self)->model;
#line 253 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp11_ = _tmp10_->searching_for;
#line 253 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	if (_tmp11_ == SYNAPSE_GUI_SEARCHING_FOR_SOURCES) {
#line 253 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		synapse_gui_view_custom_update_labels (self);
#line 1463 "view-custom.c"
	}
}


static void synapse_gui_view_custom_real_update_focused_action (SynapseGuiView* base, SynapseGuiEntry* m) {
	SynapseGuiViewCustom * self;
	SynapseGuiEntry* _tmp0_ = NULL;
	gconstpointer _tmp1_ = NULL;
	SynapseMatch* _tmp2_ = NULL;
	SynapseGuiModel* _tmp10_ = NULL;
	SynapseGuiSearchingFor _tmp11_ = 0;
#line 256 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = (SynapseGuiViewCustom*) base;
#line 256 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_return_if_fail (m != NULL);
#line 258 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = m;
#line 258 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = synapse_gui_entry_get_value (_tmp0_);
#line 258 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp2_ = _tmp1_;
#line 258 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	if (((SynapseMatch*) _tmp2_) != NULL) {
#line 1487 "view-custom.c"
		SynapseGuiSpecificMatchList* _tmp3_ = NULL;
		SynapseGuiEntry* _tmp4_ = NULL;
		gconstpointer _tmp5_ = NULL;
		gint _tmp6_ = 0;
		SynapseGuiEntry* _tmp7_ = NULL;
		gconstpointer _tmp8_ = NULL;
		gint _tmp9_ = 0;
#line 260 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp3_ = self->priv->results_actions;
#line 260 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp4_ = m;
#line 260 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp5_ = synapse_gui_entry_get_key (_tmp4_);
#line 260 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp6_ = _tmp5_;
#line 260 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp7_ = m;
#line 260 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp8_ = synapse_gui_entry_get_key (_tmp7_);
#line 260 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp9_ = _tmp8_;
#line 260 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		synapse_gui_match_list_view_set_indexes ((SynapseGuiMatchListView*) _tmp3_, (gint) ((gintptr) _tmp6_), (gint) ((gintptr) _tmp9_));
#line 1511 "view-custom.c"
	}
#line 262 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp10_ = ((SynapseGuiView*) self)->model;
#line 262 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp11_ = _tmp10_->searching_for;
#line 262 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	if (_tmp11_ == SYNAPSE_GUI_SEARCHING_FOR_ACTIONS) {
#line 262 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		synapse_gui_view_custom_update_labels (self);
#line 1521 "view-custom.c"
	}
}


static void synapse_gui_view_custom_real_update_focused_target (SynapseGuiView* base, SynapseGuiEntry* m) {
	SynapseGuiViewCustom * self;
	SynapseGuiEntry* _tmp0_ = NULL;
	gconstpointer _tmp1_ = NULL;
	SynapseMatch* _tmp2_ = NULL;
	SynapseGuiModel* _tmp10_ = NULL;
	SynapseGuiSearchingFor _tmp11_ = 0;
#line 265 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = (SynapseGuiViewCustom*) base;
#line 265 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_return_if_fail (m != NULL);
#line 267 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = m;
#line 267 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = synapse_gui_entry_get_value (_tmp0_);
#line 267 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp2_ = _tmp1_;
#line 267 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	if (((SynapseMatch*) _tmp2_) != NULL) {
#line 1545 "view-custom.c"
		SynapseGuiSpecificMatchList* _tmp3_ = NULL;
		SynapseGuiEntry* _tmp4_ = NULL;
		gconstpointer _tmp5_ = NULL;
		gint _tmp6_ = 0;
		SynapseGuiEntry* _tmp7_ = NULL;
		gconstpointer _tmp8_ = NULL;
		gint _tmp9_ = 0;
#line 267 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp3_ = self->priv->results_targets;
#line 267 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp4_ = m;
#line 267 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp5_ = synapse_gui_entry_get_key (_tmp4_);
#line 267 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp6_ = _tmp5_;
#line 267 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp7_ = m;
#line 267 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp8_ = synapse_gui_entry_get_key (_tmp7_);
#line 267 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		_tmp9_ = _tmp8_;
#line 267 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		synapse_gui_match_list_view_set_indexes ((SynapseGuiMatchListView*) _tmp3_, (gint) ((gintptr) _tmp6_), (gint) ((gintptr) _tmp9_));
#line 1569 "view-custom.c"
	}
#line 268 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp10_ = ((SynapseGuiView*) self)->model;
#line 268 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp11_ = _tmp10_->searching_for;
#line 268 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	if (_tmp11_ == SYNAPSE_GUI_SEARCHING_FOR_TARGETS) {
#line 268 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
		synapse_gui_view_custom_update_labels (self);
#line 1579 "view-custom.c"
	}
}


static void synapse_gui_view_custom_real_update_sources (SynapseGuiView* base, GeeList* list) {
	SynapseGuiViewCustom * self;
	SynapseGuiSpecificMatchList* _tmp0_ = NULL;
	GeeList* _tmp1_ = NULL;
	GtkBox* _tmp2_ = NULL;
	SynapseGuiIController* _tmp3_ = NULL;
	SynapseGuiIController* _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
#line 271 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = (SynapseGuiViewCustom*) base;
#line 273 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = self->priv->results_sources;
#line 273 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = list;
#line 273 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_match_list_view_set_list ((SynapseGuiMatchListView*) _tmp0_, _tmp1_, 0, -1);
#line 274 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp2_ = self->priv->action_box;
#line 274 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp3_ = synapse_gui_iview_get_controller ((SynapseGuiIView*) self);
#line 274 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp4_ = _tmp3_;
#line 274 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp5_ = synapse_gui_icontroller_is_in_initial_state (_tmp4_);
#line 274 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp2_, !_tmp5_);
#line 1610 "view-custom.c"
}


static void synapse_gui_view_custom_real_update_actions (SynapseGuiView* base, GeeList* list) {
	SynapseGuiViewCustom * self;
	SynapseGuiSpecificMatchList* _tmp0_ = NULL;
	GeeList* _tmp1_ = NULL;
#line 276 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = (SynapseGuiViewCustom*) base;
#line 278 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = self->priv->results_actions;
#line 278 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = list;
#line 278 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_match_list_view_set_list ((SynapseGuiMatchListView*) _tmp0_, _tmp1_, 0, -1);
#line 1626 "view-custom.c"
}


static void synapse_gui_view_custom_real_update_targets (SynapseGuiView* base, GeeList* list) {
	SynapseGuiViewCustom * self;
	SynapseGuiSpecificMatchList* _tmp0_ = NULL;
	GeeList* _tmp1_ = NULL;
	SynapseGuiSpecificMatchList* _tmp2_ = NULL;
	GtkBox* _tmp3_ = NULL;
	SynapseGuiSpecificMatchList* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
#line 280 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = (SynapseGuiViewCustom*) base;
#line 282 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = self->priv->results_targets;
#line 282 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = list;
#line 282 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_match_list_view_set_list ((SynapseGuiMatchListView*) _tmp0_, _tmp1_, 0, -1);
#line 283 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp2_ = self->priv->results_targets;
#line 283 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_specific_match_list_update_searching_for (_tmp2_);
#line 284 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp3_ = self->priv->target_box;
#line 284 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp4_ = self->priv->results_targets;
#line 284 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp5_ = synapse_gui_match_list_view_get_min_visible_rows ((SynapseGuiMatchListView*) _tmp4_);
#line 284 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp6_ = _tmp5_;
#line 284 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp3_, _tmp6_ > 0);
#line 1661 "view-custom.c"
}


SynapseGuiViewCustom* synapse_gui_view_custom_construct (GType object_type) {
	SynapseGuiViewCustom * self = NULL;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = (SynapseGuiViewCustom*) synapse_gui_view_construct (object_type);
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	return self;
#line 1671 "view-custom.c"
}


SynapseGuiViewCustom* synapse_gui_view_custom_new (void) {
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	return synapse_gui_view_custom_construct (SYNAPSE_GUI_TYPE_VIEW_CUSTOM);
#line 1678 "view-custom.c"
}


static GObject * synapse_gui_view_custom_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	SynapseGuiViewCustom * self;
#line 30 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	parent_class = G_OBJECT_CLASS (synapse_gui_view_custom_parent_class);
#line 30 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 30 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYNAPSE_GUI_TYPE_VIEW_CUSTOM, SynapseGuiViewCustom);
#line 30 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	return obj;
#line 1694 "view-custom.c"
}


static void synapse_gui_view_custom_class_init (SynapseGuiViewCustomClass * klass) {
	GParamSpecInt* icon_size = NULL;
	GParamSpecInt* _tmp0_ = NULL;
	GParamSpecString* title_max = NULL;
	GParamSpecString* _tmp1_ = NULL;
	GParamSpecString* descr_max = NULL;
	GParamSpecString* _tmp2_ = NULL;
	GParamSpecInt* _tmp3_ = NULL;
	GParamSpecString* _tmp4_ = NULL;
	GParamSpecString* _tmp5_ = NULL;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	synapse_gui_view_custom_parent_class = g_type_class_peek_parent (klass);
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	g_type_class_add_private (klass, sizeof (SynapseGuiViewCustomPrivate));
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	((GtkWidgetClass *) klass)->style_updated = synapse_gui_view_custom_real_style_updated;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	((SynapseGuiViewClass *) klass)->build_ui = synapse_gui_view_custom_real_build_ui;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	((SynapseGuiViewClass *) klass)->is_list_visible = synapse_gui_view_custom_real_is_list_visible;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	((SynapseGuiViewClass *) klass)->set_list_visible = synapse_gui_view_custom_real_set_list_visible;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	((SynapseGuiViewClass *) klass)->set_throbber_visible = synapse_gui_view_custom_real_set_throbber_visible;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	((SynapseGuiViewClass *) klass)->update_searching_for = synapse_gui_view_custom_real_update_searching_for;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	((SynapseGuiViewClass *) klass)->update_selected_category = synapse_gui_view_custom_real_update_selected_category;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	((SynapseGuiViewClass *) klass)->paint_background = synapse_gui_view_custom_real_paint_background;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	((SynapseGuiViewClass *) klass)->update_focused_source = synapse_gui_view_custom_real_update_focused_source;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	((SynapseGuiViewClass *) klass)->update_focused_action = synapse_gui_view_custom_real_update_focused_action;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	((SynapseGuiViewClass *) klass)->update_focused_target = synapse_gui_view_custom_real_update_focused_target;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	((SynapseGuiViewClass *) klass)->update_sources = synapse_gui_view_custom_real_update_sources;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	((SynapseGuiViewClass *) klass)->update_actions = synapse_gui_view_custom_real_update_actions;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	((SynapseGuiViewClass *) klass)->update_targets = synapse_gui_view_custom_real_update_targets;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	G_OBJECT_CLASS (klass)->constructor = synapse_gui_view_custom_constructor;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	G_OBJECT_CLASS (klass)->finalize = synapse_gui_view_custom_finalize;
#line 37 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp0_ = g_param_spec_int ("icon-size", "Icon Size", "The size of focused icon in supported themes", 24, 64, 48, G_PARAM_READWRITE);
#line 37 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	icon_size = _tmp0_;
#line 42 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp1_ = g_param_spec_string ("title-size", "Title Font Size", "The standard size the match title in Pango absolute sizes (string)", "large", G_PARAM_READWRITE);
#line 42 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	title_max = _tmp1_;
#line 48 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp2_ = g_param_spec_string ("description-size", "Description Font Size", "The standard size the match description in Pango absolute sizes (strin" \
"g)", "medium", G_PARAM_READWRITE);
#line 48 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	descr_max = _tmp2_;
#line 54 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp3_ = icon_size;
#line 54 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_widget_class_install_style_property (GTK_WIDGET_CLASS (klass), (GParamSpec*) _tmp3_);
#line 55 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp4_ = title_max;
#line 55 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_widget_class_install_style_property (GTK_WIDGET_CLASS (klass), (GParamSpec*) _tmp4_);
#line 56 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_tmp5_ = descr_max;
#line 56 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	gtk_widget_class_install_style_property (GTK_WIDGET_CLASS (klass), (GParamSpec*) _tmp5_);
#line 34 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_param_spec_unref0 (descr_max);
#line 34 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_param_spec_unref0 (title_max);
#line 34 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_param_spec_unref0 (icon_size);
#line 1774 "view-custom.c"
}


static void synapse_gui_view_custom_instance_init (SynapseGuiViewCustom * self) {
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self->priv = SYNAPSE_GUI_VIEW_CUSTOM_GET_PRIVATE (self);
#line 1781 "view-custom.c"
}


static void synapse_gui_view_custom_finalize (GObject* obj) {
	SynapseGuiViewCustom * self;
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYNAPSE_GUI_TYPE_VIEW_CUSTOM, SynapseGuiViewCustom);
#line 74 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->container);
#line 75 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->action_box);
#line 76 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->target_box);
#line 78 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->status);
#line 79 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->logo);
#line 80 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->search);
#line 82 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->results_sources);
#line 83 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->results_actions);
#line 84 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->results_targets);
#line 86 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	_g_object_unref0 (self->priv->menuthrobber);
#line 28 "/home/heider/github/synapse-project/src/ui/view-custom.vala"
	G_OBJECT_CLASS (synapse_gui_view_custom_parent_class)->finalize (obj);
#line 1811 "view-custom.c"
}


GType synapse_gui_view_custom_get_type (void) {
	static volatile gsize synapse_gui_view_custom_type_id__volatile = 0;
	if (g_once_init_enter (&synapse_gui_view_custom_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynapseGuiViewCustomClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synapse_gui_view_custom_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynapseGuiViewCustom), 0, (GInstanceInitFunc) synapse_gui_view_custom_instance_init, NULL };
		GType synapse_gui_view_custom_type_id;
		synapse_gui_view_custom_type_id = g_type_register_static (SYNAPSE_GUI_TYPE_VIEW, "SynapseGuiViewCustom", &g_define_type_info, 0);
		g_once_init_leave (&synapse_gui_view_custom_type_id__volatile, synapse_gui_view_custom_type_id);
	}
	return synapse_gui_view_custom_type_id__volatile;
}



