/* volume-service.c generated by valac 0.30.1, the Vala compiler
 * generated from volume-service.vala, do not modify */

/*
 * Copyright (C) 2010 Michal Hruby <michal.mhr@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by Michal Hruby <michal.mhr@gmail.com>
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define SYNAPSE_TYPE_VOLUME_SERVICE (synapse_volume_service_get_type ())
#define SYNAPSE_VOLUME_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_TYPE_VOLUME_SERVICE, SynapseVolumeService))
#define SYNAPSE_VOLUME_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_TYPE_VOLUME_SERVICE, SynapseVolumeServiceClass))
#define SYNAPSE_IS_VOLUME_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_TYPE_VOLUME_SERVICE))
#define SYNAPSE_IS_VOLUME_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_TYPE_VOLUME_SERVICE))
#define SYNAPSE_VOLUME_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_TYPE_VOLUME_SERVICE, SynapseVolumeServiceClass))

typedef struct _SynapseVolumeService SynapseVolumeService;
typedef struct _SynapseVolumeServiceClass SynapseVolumeServiceClass;
typedef struct _SynapseVolumeServicePrivate SynapseVolumeServicePrivate;

#define SYNAPSE_TYPE_MATCH (synapse_match_get_type ())
#define SYNAPSE_MATCH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_TYPE_MATCH, SynapseMatch))
#define SYNAPSE_MATCH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_TYPE_MATCH, SynapseMatchClass))
#define SYNAPSE_IS_MATCH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_TYPE_MATCH))
#define SYNAPSE_IS_MATCH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_TYPE_MATCH))
#define SYNAPSE_MATCH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_TYPE_MATCH, SynapseMatchClass))

typedef struct _SynapseMatch SynapseMatch;
typedef struct _SynapseMatchClass SynapseMatchClass;

#define SYNAPSE_TYPE_URI_MATCH (synapse_uri_match_get_type ())
#define SYNAPSE_URI_MATCH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_TYPE_URI_MATCH, SynapseUriMatch))
#define SYNAPSE_URI_MATCH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_TYPE_URI_MATCH, SynapseUriMatchClass))
#define SYNAPSE_IS_URI_MATCH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_TYPE_URI_MATCH))
#define SYNAPSE_IS_URI_MATCH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_TYPE_URI_MATCH))
#define SYNAPSE_URI_MATCH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_TYPE_URI_MATCH, SynapseUriMatchClass))

typedef struct _SynapseUriMatch SynapseUriMatch;
typedef struct _SynapseUriMatchClass SynapseUriMatchClass;

#define SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT (synapse_volume_service_volume_object_get_type ())
#define SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, SynapseVolumeServiceVolumeObject))
#define SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, SynapseVolumeServiceVolumeObjectClass))
#define SYNAPSE_VOLUME_SERVICE_IS_VOLUME_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT))
#define SYNAPSE_VOLUME_SERVICE_IS_VOLUME_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT))
#define SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, SynapseVolumeServiceVolumeObjectClass))

typedef struct _SynapseVolumeServiceVolumeObject SynapseVolumeServiceVolumeObject;
typedef struct _SynapseVolumeServiceVolumeObjectClass SynapseVolumeServiceVolumeObjectClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _SynapseMatchPrivate SynapseMatchPrivate;

#define SYNAPSE_TYPE_QUERY_FLAGS (synapse_query_flags_get_type ())
typedef struct _SynapseUriMatchPrivate SynapseUriMatchPrivate;
typedef struct _SynapseVolumeServiceVolumeObjectPrivate SynapseVolumeServiceVolumeObjectPrivate;

struct _SynapseVolumeService {
	GObject parent_instance;
	SynapseVolumeServicePrivate * priv;
};

struct _SynapseVolumeServiceClass {
	GObjectClass parent_class;
};

struct _SynapseVolumeServicePrivate {
	GVolumeMonitor* vm;
	GeeMap* volumes;
};

typedef enum  {
	SYNAPSE_QUERY_FLAGS_INCLUDE_REMOTE = 1 << 0,
	SYNAPSE_QUERY_FLAGS_UNCATEGORIZED = 1 << 1,
	SYNAPSE_QUERY_FLAGS_APPLICATIONS = 1 << 2,
	SYNAPSE_QUERY_FLAGS_ACTIONS = 1 << 3,
	SYNAPSE_QUERY_FLAGS_AUDIO = 1 << 4,
	SYNAPSE_QUERY_FLAGS_VIDEO = 1 << 5,
	SYNAPSE_QUERY_FLAGS_DOCUMENTS = 1 << 6,
	SYNAPSE_QUERY_FLAGS_IMAGES = 1 << 7,
	SYNAPSE_QUERY_FLAGS_FILES = ((SYNAPSE_QUERY_FLAGS_AUDIO | SYNAPSE_QUERY_FLAGS_VIDEO) | SYNAPSE_QUERY_FLAGS_DOCUMENTS) | SYNAPSE_QUERY_FLAGS_IMAGES,
	SYNAPSE_QUERY_FLAGS_PLACES = 1 << 8,
	SYNAPSE_QUERY_FLAGS_INTERNET = 1 << 9,
	SYNAPSE_QUERY_FLAGS_TEXT = 1 << 10,
	SYNAPSE_QUERY_FLAGS_CONTACTS = 1 << 11,
	SYNAPSE_QUERY_FLAGS_ALL = 0xFFFFFFFFLL,
	SYNAPSE_QUERY_FLAGS_LOCAL_CONTENT = SYNAPSE_QUERY_FLAGS_ALL ^ SYNAPSE_QUERY_FLAGS_INCLUDE_REMOTE
} SynapseQueryFlags;

struct _SynapseMatch {
	GObject parent_instance;
	SynapseMatchPrivate * priv;
};

struct _SynapseMatchClass {
	GObjectClass parent_class;
	void (*execute) (SynapseMatch* self, SynapseMatch* match);
	void (*execute_with_target) (SynapseMatch* self, SynapseMatch* source, SynapseMatch* target);
	gboolean (*needs_target) (SynapseMatch* self);
	SynapseQueryFlags (*target_flags) (SynapseMatch* self);
};

struct _SynapseUriMatch {
	SynapseMatch parent_instance;
	SynapseUriMatchPrivate * priv;
};

struct _SynapseUriMatchClass {
	SynapseMatchClass parent_class;
};

struct _SynapseVolumeServiceVolumeObject {
	SynapseUriMatch parent_instance;
	SynapseVolumeServiceVolumeObjectPrivate * priv;
};

struct _SynapseVolumeServiceVolumeObjectClass {
	SynapseUriMatchClass parent_class;
};

struct _SynapseVolumeServiceVolumeObjectPrivate {
	gulong changed_signal_id;
	GVolume* _volume;
};


static gpointer synapse_volume_service_parent_class = NULL;
static SynapseVolumeService* synapse_volume_service_instance;
static SynapseVolumeService* synapse_volume_service_instance = NULL;
static gpointer synapse_volume_service_volume_object_parent_class = NULL;

GType synapse_volume_service_get_type (void) G_GNUC_CONST;
GType synapse_match_get_type (void) G_GNUC_CONST;
GType synapse_uri_match_get_type (void) G_GNUC_CONST;
GType synapse_volume_service_volume_object_get_type (void) G_GNUC_CONST;
#define SYNAPSE_VOLUME_SERVICE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYNAPSE_TYPE_VOLUME_SERVICE, SynapseVolumeServicePrivate))
enum  {
	SYNAPSE_VOLUME_SERVICE_DUMMY_PROPERTY
};
SynapseVolumeService* synapse_volume_service_get_default (void);
static SynapseVolumeService* synapse_volume_service_new (void);
static SynapseVolumeService* synapse_volume_service_construct (GType object_type);
void synapse_volume_service_initialize (SynapseVolumeService* self);
static void __lambda10_ (SynapseVolumeService* self, GVolume* volume);
SynapseVolumeServiceVolumeObject* synapse_volume_service_volume_object_new (GVolume* volume);
SynapseVolumeServiceVolumeObject* synapse_volume_service_volume_object_construct (GType object_type, GVolume* volume);
static void ___lambda10__g_volume_monitor_volume_added (GVolumeMonitor* _sender, GVolume* volume, gpointer self);
static void __lambda11_ (SynapseVolumeService* self, GVolume* volume);
static void ___lambda11__g_volume_monitor_volume_removed (GVolumeMonitor* _sender, GVolume* volume, gpointer self);
static void __lambda12_ (SynapseVolumeService* self, GMount* mount);
void synapse_volume_service_volume_object_update_state (SynapseVolumeServiceVolumeObject* self);
static void ___lambda12__g_volume_monitor_mount_added (GVolumeMonitor* _sender, GMount* mount, gpointer self);
static void synapse_volume_service_process_volume_list (SynapseVolumeService* self, GList* volume_list);
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
GeeCollection* synapse_volume_service_get_volumes (SynapseVolumeService* self);
gchar* synapse_volume_service_uri_to_volume_name (SynapseVolumeService* self, const gchar* uri, gchar** volume_path);
static GObject * synapse_volume_service_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
GType synapse_query_flags_get_type (void) G_GNUC_CONST;
#define SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, SynapseVolumeServiceVolumeObjectPrivate))
enum  {
	SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_DUMMY_PROPERTY,
	SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_VOLUME
};
void synapse_volume_service_volume_object_set_volume (SynapseVolumeServiceVolumeObject* self, GVolume* value);
gboolean synapse_volume_service_volume_object_is_mounted (SynapseVolumeServiceVolumeObject* self);
GVolume* synapse_volume_service_volume_object_get_volume (SynapseVolumeServiceVolumeObject* self);
void synapse_match_set_title (SynapseMatch* self, const gchar* value);
void synapse_match_set_description (SynapseMatch* self, const gchar* value);
void synapse_match_set_icon_name (SynapseMatch* self, const gchar* value);
void synapse_match_set_has_thumbnail (SynapseMatch* self, gboolean value);
void synapse_uri_match_set_uri (SynapseUriMatch* self, const gchar* value);
void synapse_uri_match_set_file_type (SynapseUriMatch* self, SynapseQueryFlags value);
void synapse_uri_match_set_mime_type (SynapseUriMatch* self, const gchar* value);
static void _synapse_volume_service_volume_object_update_state_g_volume_changed (GVolume* _sender, gpointer self);
const gchar* synapse_match_get_title (SynapseMatch* self);
const gchar* synapse_match_get_icon_name (SynapseMatch* self);
const gchar* synapse_uri_match_get_uri (SynapseUriMatch* self);
static void synapse_volume_service_volume_object_finalize (GObject* obj);
static void _vala_synapse_volume_service_volume_object_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_synapse_volume_service_volume_object_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void synapse_volume_service_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
#line 29 "/home/heider/github/synapse/src/core/volume-service.vala"
	return self ? g_object_ref (self) : NULL;
#line 212 "volume-service.c"
}


SynapseVolumeService* synapse_volume_service_get_default (void) {
	SynapseVolumeService* result = NULL;
	SynapseVolumeService* _tmp0_ = NULL;
	SynapseVolumeService* _tmp1_ = NULL;
	SynapseVolumeService* _tmp2_ = NULL;
	SynapseVolumeService* _tmp4_ = NULL;
#line 29 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp1_ = synapse_volume_service_instance;
#line 29 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 29 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp0_ = _tmp2_;
#line 29 "/home/heider/github/synapse/src/core/volume-service.vala"
	if (_tmp0_ == NULL) {
#line 230 "volume-service.c"
		SynapseVolumeService* _tmp3_ = NULL;
#line 29 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp3_ = synapse_volume_service_new ();
#line 29 "/home/heider/github/synapse/src/core/volume-service.vala"
		_g_object_unref0 (_tmp0_);
#line 29 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp0_ = _tmp3_;
#line 238 "volume-service.c"
	}
#line 29 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp4_ = _tmp0_;
#line 29 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp0_ = NULL;
#line 29 "/home/heider/github/synapse/src/core/volume-service.vala"
	result = _tmp4_;
#line 29 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_object_unref0 (_tmp0_);
#line 29 "/home/heider/github/synapse/src/core/volume-service.vala"
	return result;
#line 250 "volume-service.c"
}


static SynapseVolumeService* synapse_volume_service_construct (GType object_type) {
	SynapseVolumeService * self = NULL;
#line 32 "/home/heider/github/synapse/src/core/volume-service.vala"
	self = (SynapseVolumeService*) g_object_new (object_type, NULL);
#line 32 "/home/heider/github/synapse/src/core/volume-service.vala"
	return self;
#line 260 "volume-service.c"
}


static SynapseVolumeService* synapse_volume_service_new (void) {
#line 32 "/home/heider/github/synapse/src/core/volume-service.vala"
	return synapse_volume_service_construct (SYNAPSE_TYPE_VOLUME_SERVICE);
#line 267 "volume-service.c"
}


static void __lambda10_ (SynapseVolumeService* self, GVolume* volume) {
	GeeMap* _tmp0_ = NULL;
	GVolume* _tmp1_ = NULL;
	GVolume* _tmp2_ = NULL;
	SynapseVolumeServiceVolumeObject* _tmp3_ = NULL;
	SynapseVolumeServiceVolumeObject* _tmp4_ = NULL;
#line 56 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_return_if_fail (volume != NULL);
#line 57 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp0_ = self->priv->volumes;
#line 57 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp1_ = volume;
#line 57 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp2_ = volume;
#line 57 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp3_ = synapse_volume_service_volume_object_new (_tmp2_);
#line 57 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp4_ = _tmp3_;
#line 57 "/home/heider/github/synapse/src/core/volume-service.vala"
	gee_map_set (_tmp0_, _tmp1_, _tmp4_);
#line 57 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_object_unref0 (_tmp4_);
#line 293 "volume-service.c"
}


static void ___lambda10__g_volume_monitor_volume_added (GVolumeMonitor* _sender, GVolume* volume, gpointer self) {
#line 56 "/home/heider/github/synapse/src/core/volume-service.vala"
	__lambda10_ ((SynapseVolumeService*) self, volume);
#line 300 "volume-service.c"
}


static void __lambda11_ (SynapseVolumeService* self, GVolume* volume) {
	GeeMap* _tmp0_ = NULL;
	GVolume* _tmp1_ = NULL;
#line 59 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_return_if_fail (volume != NULL);
#line 60 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp0_ = self->priv->volumes;
#line 60 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp1_ = volume;
#line 60 "/home/heider/github/synapse/src/core/volume-service.vala"
	gee_map_unset (_tmp0_, _tmp1_, NULL);
#line 315 "volume-service.c"
}


static void ___lambda11__g_volume_monitor_volume_removed (GVolumeMonitor* _sender, GVolume* volume, gpointer self) {
#line 59 "/home/heider/github/synapse/src/core/volume-service.vala"
	__lambda11_ ((SynapseVolumeService*) self, volume);
#line 322 "volume-service.c"
}


static void __lambda12_ (SynapseVolumeService* self, GMount* mount) {
	GVolume* volume = NULL;
	GMount* _tmp0_ = NULL;
	GVolume* _tmp1_ = NULL;
	GVolume* _tmp2_ = NULL;
	GeeMap* _tmp3_ = NULL;
	GeeSet* _tmp4_ = NULL;
	GeeSet* _tmp5_ = NULL;
	GeeSet* _tmp6_ = NULL;
	GVolume* _tmp7_ = NULL;
	gboolean _tmp8_ = FALSE;
	gboolean _tmp9_ = FALSE;
#line 62 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_return_if_fail (mount != NULL);
#line 63 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp0_ = mount;
#line 63 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp1_ = g_mount_get_volume (_tmp0_);
#line 63 "/home/heider/github/synapse/src/core/volume-service.vala"
	volume = _tmp1_;
#line 64 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp2_ = volume;
#line 64 "/home/heider/github/synapse/src/core/volume-service.vala"
	if (_tmp2_ == NULL) {
#line 64 "/home/heider/github/synapse/src/core/volume-service.vala"
		_g_object_unref0 (volume);
#line 64 "/home/heider/github/synapse/src/core/volume-service.vala"
		return;
#line 354 "volume-service.c"
	}
#line 66 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp3_ = self->priv->volumes;
#line 66 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp4_ = gee_map_get_keys (_tmp3_);
#line 66 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp5_ = _tmp4_;
#line 66 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp6_ = _tmp5_;
#line 66 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp7_ = volume;
#line 66 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp8_ = gee_collection_contains ((GeeCollection*) _tmp6_, _tmp7_);
#line 66 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp9_ = _tmp8_;
#line 66 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_object_unref0 (_tmp6_);
#line 66 "/home/heider/github/synapse/src/core/volume-service.vala"
	if (_tmp9_) {
#line 374 "volume-service.c"
		GeeMap* _tmp10_ = NULL;
		GVolume* _tmp11_ = NULL;
		gpointer _tmp12_ = NULL;
		SynapseVolumeServiceVolumeObject* _tmp13_ = NULL;
#line 66 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp10_ = self->priv->volumes;
#line 66 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp11_ = volume;
#line 66 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp12_ = gee_map_get (_tmp10_, _tmp11_);
#line 66 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp13_ = (SynapseVolumeServiceVolumeObject*) _tmp12_;
#line 66 "/home/heider/github/synapse/src/core/volume-service.vala"
		synapse_volume_service_volume_object_update_state (_tmp13_);
#line 66 "/home/heider/github/synapse/src/core/volume-service.vala"
		_g_object_unref0 (_tmp13_);
#line 391 "volume-service.c"
	}
#line 62 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_object_unref0 (volume);
#line 395 "volume-service.c"
}


static void ___lambda12__g_volume_monitor_mount_added (GVolumeMonitor* _sender, GMount* mount, gpointer self) {
#line 62 "/home/heider/github/synapse/src/core/volume-service.vala"
	__lambda12_ ((SynapseVolumeService*) self, mount);
#line 402 "volume-service.c"
}


static void _g_object_unref0_ (gpointer var) {
#line 52 "/home/heider/github/synapse/src/core/volume-service.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 409 "volume-service.c"
}


static void _g_list_free__g_object_unref0_ (GList* self) {
#line 52 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
#line 52 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_list_free (self);
#line 418 "volume-service.c"
}


void synapse_volume_service_initialize (SynapseVolumeService* self) {
	GVolumeMonitor* _tmp0_ = NULL;
	GVolumeMonitor* _tmp1_ = NULL;
	GVolumeMonitor* _tmp2_ = NULL;
	GVolumeMonitor* _tmp3_ = NULL;
	GList* volume_list = NULL;
	GVolumeMonitor* _tmp4_ = NULL;
	GList* _tmp5_ = NULL;
#line 52 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_return_if_fail (self != NULL);
#line 54 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp0_ = g_volume_monitor_get ();
#line 54 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_object_unref0 (self->priv->vm);
#line 54 "/home/heider/github/synapse/src/core/volume-service.vala"
	self->priv->vm = _tmp0_;
#line 56 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp1_ = self->priv->vm;
#line 56 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_signal_connect_object (_tmp1_, "volume-added", (GCallback) ___lambda10__g_volume_monitor_volume_added, self, 0);
#line 59 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp2_ = self->priv->vm;
#line 59 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_signal_connect_object (_tmp2_, "volume-removed", (GCallback) ___lambda11__g_volume_monitor_volume_removed, self, 0);
#line 62 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp3_ = self->priv->vm;
#line 62 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_signal_connect_object (_tmp3_, "mount-added", (GCallback) ___lambda12__g_volume_monitor_mount_added, self, 0);
#line 70 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp4_ = self->priv->vm;
#line 70 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp5_ = g_volume_monitor_get_volumes (_tmp4_);
#line 70 "/home/heider/github/synapse/src/core/volume-service.vala"
	volume_list = _tmp5_;
#line 71 "/home/heider/github/synapse/src/core/volume-service.vala"
	synapse_volume_service_process_volume_list (self, volume_list);
#line 52 "/home/heider/github/synapse/src/core/volume-service.vala"
	__g_list_free__g_object_unref0_0 (volume_list);
#line 460 "volume-service.c"
}


static void synapse_volume_service_process_volume_list (SynapseVolumeService* self, GList* volume_list) {
	GList* _tmp0_ = NULL;
#line 74 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_return_if_fail (self != NULL);
#line 76 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp0_ = volume_list;
#line 470 "volume-service.c"
	{
		GList* volume_collection = NULL;
		GList* volume_it = NULL;
#line 76 "/home/heider/github/synapse/src/core/volume-service.vala"
		volume_collection = _tmp0_;
#line 76 "/home/heider/github/synapse/src/core/volume-service.vala"
		for (volume_it = volume_collection; volume_it != NULL; volume_it = volume_it->next) {
#line 478 "volume-service.c"
			GVolume* volume = NULL;
#line 76 "/home/heider/github/synapse/src/core/volume-service.vala"
			volume = (GVolume*) volume_it->data;
#line 482 "volume-service.c"
			{
				GeeMap* _tmp1_ = NULL;
				GVolume* _tmp2_ = NULL;
				GVolume* _tmp3_ = NULL;
				SynapseVolumeServiceVolumeObject* _tmp4_ = NULL;
				SynapseVolumeServiceVolumeObject* _tmp5_ = NULL;
#line 78 "/home/heider/github/synapse/src/core/volume-service.vala"
				_tmp1_ = self->priv->volumes;
#line 78 "/home/heider/github/synapse/src/core/volume-service.vala"
				_tmp2_ = volume;
#line 78 "/home/heider/github/synapse/src/core/volume-service.vala"
				_tmp3_ = volume;
#line 78 "/home/heider/github/synapse/src/core/volume-service.vala"
				_tmp4_ = synapse_volume_service_volume_object_new (_tmp3_);
#line 78 "/home/heider/github/synapse/src/core/volume-service.vala"
				_tmp5_ = _tmp4_;
#line 78 "/home/heider/github/synapse/src/core/volume-service.vala"
				gee_map_set (_tmp1_, _tmp2_, _tmp5_);
#line 78 "/home/heider/github/synapse/src/core/volume-service.vala"
				_g_object_unref0 (_tmp5_);
#line 503 "volume-service.c"
			}
		}
	}
}


GeeCollection* synapse_volume_service_get_volumes (SynapseVolumeService* self) {
	GeeCollection* result = NULL;
	GeeMap* _tmp0_ = NULL;
	GeeCollection* _tmp1_ = NULL;
	GeeCollection* _tmp2_ = NULL;
#line 82 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 84 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp0_ = self->priv->volumes;
#line 84 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp1_ = gee_map_get_values (_tmp0_);
#line 84 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp2_ = _tmp1_;
#line 84 "/home/heider/github/synapse/src/core/volume-service.vala"
	result = _tmp2_;
#line 84 "/home/heider/github/synapse/src/core/volume-service.vala"
	return result;
#line 527 "volume-service.c"
}


gchar* synapse_volume_service_uri_to_volume_name (SynapseVolumeService* self, const gchar* uri, gchar** volume_path) {
	gchar* _vala_volume_path = NULL;
	gchar* result = NULL;
	GeeSet* g_volumes = NULL;
	GeeMap* _tmp0_ = NULL;
	GeeSet* _tmp1_ = NULL;
	GeeSet* _tmp2_ = NULL;
	GFile* f = NULL;
	const gchar* _tmp3_ = NULL;
	GFile* _tmp4_ = NULL;
#line 87 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 87 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_return_val_if_fail (uri != NULL, NULL);
#line 89 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_free0 (_vala_volume_path);
#line 89 "/home/heider/github/synapse/src/core/volume-service.vala"
	_vala_volume_path = NULL;
#line 90 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp0_ = self->priv->volumes;
#line 90 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp1_ = gee_map_get_keys (_tmp0_);
#line 90 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp2_ = _tmp1_;
#line 90 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_volumes = _tmp2_;
#line 92 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp3_ = uri;
#line 92 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp4_ = g_file_new_for_uri (_tmp3_);
#line 92 "/home/heider/github/synapse/src/core/volume-service.vala"
	f = _tmp4_;
#line 563 "volume-service.c"
	{
		GeeIterator* _volume_it = NULL;
		GeeSet* _tmp5_ = NULL;
		GeeIterator* _tmp6_ = NULL;
#line 94 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp5_ = g_volumes;
#line 94 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp6_ = gee_iterable_iterator ((GeeIterable*) _tmp5_);
#line 94 "/home/heider/github/synapse/src/core/volume-service.vala"
		_volume_it = _tmp6_;
#line 94 "/home/heider/github/synapse/src/core/volume-service.vala"
		while (TRUE) {
#line 576 "volume-service.c"
			GeeIterator* _tmp7_ = NULL;
			gboolean _tmp8_ = FALSE;
			GVolume* volume = NULL;
			GeeIterator* _tmp9_ = NULL;
			gpointer _tmp10_ = NULL;
			GFile* root = NULL;
			GVolume* _tmp11_ = NULL;
			GFile* _tmp12_ = NULL;
			GFile* _tmp13_ = NULL;
			GFile* _tmp19_ = NULL;
			GFile* _tmp20_ = NULL;
			gboolean _tmp21_ = FALSE;
#line 94 "/home/heider/github/synapse/src/core/volume-service.vala"
			_tmp7_ = _volume_it;
#line 94 "/home/heider/github/synapse/src/core/volume-service.vala"
			_tmp8_ = gee_iterator_next (_tmp7_);
#line 94 "/home/heider/github/synapse/src/core/volume-service.vala"
			if (!_tmp8_) {
#line 94 "/home/heider/github/synapse/src/core/volume-service.vala"
				break;
#line 597 "volume-service.c"
			}
#line 94 "/home/heider/github/synapse/src/core/volume-service.vala"
			_tmp9_ = _volume_it;
#line 94 "/home/heider/github/synapse/src/core/volume-service.vala"
			_tmp10_ = gee_iterator_get (_tmp9_);
#line 94 "/home/heider/github/synapse/src/core/volume-service.vala"
			volume = (GVolume*) _tmp10_;
#line 96 "/home/heider/github/synapse/src/core/volume-service.vala"
			_tmp11_ = volume;
#line 96 "/home/heider/github/synapse/src/core/volume-service.vala"
			_tmp12_ = g_volume_get_activation_root (_tmp11_);
#line 96 "/home/heider/github/synapse/src/core/volume-service.vala"
			root = _tmp12_;
#line 97 "/home/heider/github/synapse/src/core/volume-service.vala"
			_tmp13_ = root;
#line 97 "/home/heider/github/synapse/src/core/volume-service.vala"
			if (_tmp13_ == NULL) {
#line 615 "volume-service.c"
				GMount* mount = NULL;
				GVolume* _tmp14_ = NULL;
				GMount* _tmp15_ = NULL;
				GMount* _tmp16_ = NULL;
				GMount* _tmp17_ = NULL;
				GFile* _tmp18_ = NULL;
#line 99 "/home/heider/github/synapse/src/core/volume-service.vala"
				_tmp14_ = volume;
#line 99 "/home/heider/github/synapse/src/core/volume-service.vala"
				_tmp15_ = g_volume_get_mount (_tmp14_);
#line 99 "/home/heider/github/synapse/src/core/volume-service.vala"
				mount = _tmp15_;
#line 100 "/home/heider/github/synapse/src/core/volume-service.vala"
				_tmp16_ = mount;
#line 100 "/home/heider/github/synapse/src/core/volume-service.vala"
				if (_tmp16_ == NULL) {
#line 100 "/home/heider/github/synapse/src/core/volume-service.vala"
					_g_object_unref0 (mount);
#line 100 "/home/heider/github/synapse/src/core/volume-service.vala"
					_g_object_unref0 (root);
#line 100 "/home/heider/github/synapse/src/core/volume-service.vala"
					_g_object_unref0 (volume);
#line 100 "/home/heider/github/synapse/src/core/volume-service.vala"
					continue;
#line 640 "volume-service.c"
				}
#line 101 "/home/heider/github/synapse/src/core/volume-service.vala"
				_tmp17_ = mount;
#line 101 "/home/heider/github/synapse/src/core/volume-service.vala"
				_tmp18_ = g_mount_get_root (_tmp17_);
#line 101 "/home/heider/github/synapse/src/core/volume-service.vala"
				_g_object_unref0 (root);
#line 101 "/home/heider/github/synapse/src/core/volume-service.vala"
				root = _tmp18_;
#line 97 "/home/heider/github/synapse/src/core/volume-service.vala"
				_g_object_unref0 (mount);
#line 652 "volume-service.c"
			}
#line 104 "/home/heider/github/synapse/src/core/volume-service.vala"
			_tmp19_ = f;
#line 104 "/home/heider/github/synapse/src/core/volume-service.vala"
			_tmp20_ = root;
#line 104 "/home/heider/github/synapse/src/core/volume-service.vala"
			_tmp21_ = g_file_has_prefix (_tmp19_, _tmp20_);
#line 104 "/home/heider/github/synapse/src/core/volume-service.vala"
			if (_tmp21_) {
#line 662 "volume-service.c"
				GFile* _tmp22_ = NULL;
				gchar* _tmp23_ = NULL;
				GVolume* _tmp24_ = NULL;
				gchar* _tmp25_ = NULL;
#line 106 "/home/heider/github/synapse/src/core/volume-service.vala"
				_tmp22_ = root;
#line 106 "/home/heider/github/synapse/src/core/volume-service.vala"
				_tmp23_ = g_file_get_path (_tmp22_);
#line 106 "/home/heider/github/synapse/src/core/volume-service.vala"
				_g_free0 (_vala_volume_path);
#line 106 "/home/heider/github/synapse/src/core/volume-service.vala"
				_vala_volume_path = _tmp23_;
#line 107 "/home/heider/github/synapse/src/core/volume-service.vala"
				_tmp24_ = volume;
#line 107 "/home/heider/github/synapse/src/core/volume-service.vala"
				_tmp25_ = g_volume_get_name (_tmp24_);
#line 107 "/home/heider/github/synapse/src/core/volume-service.vala"
				result = _tmp25_;
#line 107 "/home/heider/github/synapse/src/core/volume-service.vala"
				_g_object_unref0 (root);
#line 107 "/home/heider/github/synapse/src/core/volume-service.vala"
				_g_object_unref0 (volume);
#line 107 "/home/heider/github/synapse/src/core/volume-service.vala"
				_g_object_unref0 (_volume_it);
#line 107 "/home/heider/github/synapse/src/core/volume-service.vala"
				_g_object_unref0 (f);
#line 107 "/home/heider/github/synapse/src/core/volume-service.vala"
				_g_object_unref0 (g_volumes);
#line 107 "/home/heider/github/synapse/src/core/volume-service.vala"
				if (volume_path) {
#line 107 "/home/heider/github/synapse/src/core/volume-service.vala"
					*volume_path = _vala_volume_path;
#line 695 "volume-service.c"
				} else {
#line 107 "/home/heider/github/synapse/src/core/volume-service.vala"
					_g_free0 (_vala_volume_path);
#line 699 "volume-service.c"
				}
#line 107 "/home/heider/github/synapse/src/core/volume-service.vala"
				return result;
#line 703 "volume-service.c"
			}
#line 94 "/home/heider/github/synapse/src/core/volume-service.vala"
			_g_object_unref0 (root);
#line 94 "/home/heider/github/synapse/src/core/volume-service.vala"
			_g_object_unref0 (volume);
#line 709 "volume-service.c"
		}
#line 94 "/home/heider/github/synapse/src/core/volume-service.vala"
		_g_object_unref0 (_volume_it);
#line 713 "volume-service.c"
	}
#line 111 "/home/heider/github/synapse/src/core/volume-service.vala"
	result = NULL;
#line 111 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_object_unref0 (f);
#line 111 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_object_unref0 (g_volumes);
#line 111 "/home/heider/github/synapse/src/core/volume-service.vala"
	if (volume_path) {
#line 111 "/home/heider/github/synapse/src/core/volume-service.vala"
		*volume_path = _vala_volume_path;
#line 725 "volume-service.c"
	} else {
#line 111 "/home/heider/github/synapse/src/core/volume-service.vala"
		_g_free0 (_vala_volume_path);
#line 729 "volume-service.c"
	}
#line 111 "/home/heider/github/synapse/src/core/volume-service.vala"
	return result;
#line 733 "volume-service.c"
}


static GObject * synapse_volume_service_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	SynapseVolumeService * self;
	GeeHashMap* _tmp0_ = NULL;
#line 44 "/home/heider/github/synapse/src/core/volume-service.vala"
	parent_class = G_OBJECT_CLASS (synapse_volume_service_parent_class);
#line 44 "/home/heider/github/synapse/src/core/volume-service.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 44 "/home/heider/github/synapse/src/core/volume-service.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYNAPSE_TYPE_VOLUME_SERVICE, SynapseVolumeService);
#line 46 "/home/heider/github/synapse/src/core/volume-service.vala"
	synapse_volume_service_instance = self;
#line 48 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp0_ = gee_hash_map_new (g_volume_get_type (), (GBoxedCopyFunc) g_object_ref, g_object_unref, SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 48 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_object_unref0 (self->priv->volumes);
#line 48 "/home/heider/github/synapse/src/core/volume-service.vala"
	self->priv->volumes = (GeeMap*) _tmp0_;
#line 49 "/home/heider/github/synapse/src/core/volume-service.vala"
	synapse_volume_service_initialize (self);
#line 44 "/home/heider/github/synapse/src/core/volume-service.vala"
	return obj;
#line 760 "volume-service.c"
}


void synapse_volume_service_volume_object_update_state (SynapseVolumeServiceVolumeObject* self) {
	GVolume* _tmp0_ = NULL;
#line 154 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_return_if_fail (self != NULL);
#line 156 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp0_ = self->priv->_volume;
#line 156 "/home/heider/github/synapse/src/core/volume-service.vala"
	synapse_volume_service_volume_object_set_volume (self, _tmp0_);
#line 772 "volume-service.c"
}


gboolean synapse_volume_service_volume_object_is_mounted (SynapseVolumeServiceVolumeObject* self) {
	gboolean result = FALSE;
	GVolume* _tmp0_ = NULL;
	GMount* _tmp1_ = NULL;
	GMount* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
#line 159 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 161 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp0_ = self->priv->_volume;
#line 161 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp1_ = g_volume_get_mount (_tmp0_);
#line 161 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp2_ = _tmp1_;
#line 161 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp3_ = _tmp2_ != NULL;
#line 161 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_object_unref0 (_tmp2_);
#line 161 "/home/heider/github/synapse/src/core/volume-service.vala"
	result = _tmp3_;
#line 161 "/home/heider/github/synapse/src/core/volume-service.vala"
	return result;
#line 798 "volume-service.c"
}


SynapseVolumeServiceVolumeObject* synapse_volume_service_volume_object_construct (GType object_type, GVolume* volume) {
	SynapseVolumeServiceVolumeObject * self = NULL;
	GVolume* _tmp0_ = NULL;
#line 164 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_return_val_if_fail (volume != NULL, NULL);
#line 166 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp0_ = volume;
#line 166 "/home/heider/github/synapse/src/core/volume-service.vala"
	self = (SynapseVolumeServiceVolumeObject*) g_object_new (object_type, "volume", _tmp0_, NULL);
#line 164 "/home/heider/github/synapse/src/core/volume-service.vala"
	return self;
#line 813 "volume-service.c"
}


SynapseVolumeServiceVolumeObject* synapse_volume_service_volume_object_new (GVolume* volume) {
#line 164 "/home/heider/github/synapse/src/core/volume-service.vala"
	return synapse_volume_service_volume_object_construct (SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, volume);
#line 820 "volume-service.c"
}


GVolume* synapse_volume_service_volume_object_get_volume (SynapseVolumeServiceVolumeObject* self) {
	GVolume* result;
	GVolume* _tmp0_ = NULL;
#line 121 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 121 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp0_ = self->priv->_volume;
#line 121 "/home/heider/github/synapse/src/core/volume-service.vala"
	result = _tmp0_;
#line 121 "/home/heider/github/synapse/src/core/volume-service.vala"
	return result;
#line 835 "volume-service.c"
}


static void _synapse_volume_service_volume_object_update_state_g_volume_changed (GVolume* _sender, gpointer self) {
#line 147 "/home/heider/github/synapse/src/core/volume-service.vala"
	synapse_volume_service_volume_object_update_state ((SynapseVolumeServiceVolumeObject*) self);
#line 842 "volume-service.c"
}


void synapse_volume_service_volume_object_set_volume (SynapseVolumeServiceVolumeObject* self, GVolume* value) {
	GVolume* _tmp0_ = NULL;
	GVolume* _tmp1_ = NULL;
	GVolume* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	GVolume* _tmp5_ = NULL;
	GIcon* _tmp6_ = NULL;
	GIcon* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	GVolume* _tmp10_ = NULL;
	GMount* _tmp11_ = NULL;
	GMount* _tmp12_ = NULL;
	gboolean _tmp13_ = FALSE;
	gulong _tmp21_ = 0UL;
	gint _tmp24_ = 0;
	GVolume* _tmp25_ = NULL;
	GMount* _tmp26_ = NULL;
	GMount* _tmp27_ = NULL;
	gboolean _tmp28_ = FALSE;
	const gchar* _tmp29_ = NULL;
	const gchar* _tmp30_ = NULL;
	const gchar* _tmp31_ = NULL;
	const gchar* _tmp32_ = NULL;
	const gchar* _tmp33_ = NULL;
	const gchar* _tmp34_ = NULL;
#line 122 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_return_if_fail (self != NULL);
#line 124 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp0_ = value;
#line 124 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 124 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_object_unref0 (self->priv->_volume);
#line 124 "/home/heider/github/synapse/src/core/volume-service.vala"
	self->priv->_volume = _tmp1_;
#line 125 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp2_ = value;
#line 125 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp3_ = g_volume_get_name (_tmp2_);
#line 125 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp4_ = _tmp3_;
#line 125 "/home/heider/github/synapse/src/core/volume-service.vala"
	synapse_match_set_title ((SynapseMatch*) self, _tmp4_);
#line 125 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_free0 (_tmp4_);
#line 126 "/home/heider/github/synapse/src/core/volume-service.vala"
	synapse_match_set_description ((SynapseMatch*) self, "");
#line 127 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp5_ = value;
#line 127 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp6_ = g_volume_get_icon (_tmp5_);
#line 127 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp7_ = _tmp6_;
#line 127 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp8_ = g_icon_to_string (_tmp7_);
#line 127 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp9_ = _tmp8_;
#line 127 "/home/heider/github/synapse/src/core/volume-service.vala"
	synapse_match_set_icon_name ((SynapseMatch*) self, _tmp9_);
#line 127 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_free0 (_tmp9_);
#line 127 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_object_unref0 (_tmp7_);
#line 128 "/home/heider/github/synapse/src/core/volume-service.vala"
	synapse_match_set_has_thumbnail ((SynapseMatch*) self, FALSE);
#line 134 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp10_ = value;
#line 134 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp11_ = g_volume_get_mount (_tmp10_);
#line 134 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp12_ = _tmp11_;
#line 134 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp13_ = _tmp12_ != NULL;
#line 134 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_object_unref0 (_tmp12_);
#line 134 "/home/heider/github/synapse/src/core/volume-service.vala"
	if (_tmp13_) {
#line 925 "volume-service.c"
		GVolume* _tmp14_ = NULL;
		GMount* _tmp15_ = NULL;
		GMount* _tmp16_ = NULL;
		GFile* _tmp17_ = NULL;
		GFile* _tmp18_ = NULL;
		gchar* _tmp19_ = NULL;
		gchar* _tmp20_ = NULL;
#line 136 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp14_ = value;
#line 136 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp15_ = g_volume_get_mount (_tmp14_);
#line 136 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp16_ = _tmp15_;
#line 136 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp17_ = g_mount_get_root (_tmp16_);
#line 136 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp18_ = _tmp17_;
#line 136 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp19_ = g_file_get_uri (_tmp18_);
#line 136 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp20_ = _tmp19_;
#line 136 "/home/heider/github/synapse/src/core/volume-service.vala"
		synapse_uri_match_set_uri ((SynapseUriMatch*) self, _tmp20_);
#line 136 "/home/heider/github/synapse/src/core/volume-service.vala"
		_g_free0 (_tmp20_);
#line 136 "/home/heider/github/synapse/src/core/volume-service.vala"
		_g_object_unref0 (_tmp18_);
#line 136 "/home/heider/github/synapse/src/core/volume-service.vala"
		_g_object_unref0 (_tmp16_);
#line 137 "/home/heider/github/synapse/src/core/volume-service.vala"
		synapse_uri_match_set_file_type ((SynapseUriMatch*) self, SYNAPSE_QUERY_FLAGS_PLACES);
#line 138 "/home/heider/github/synapse/src/core/volume-service.vala"
		synapse_uri_match_set_mime_type ((SynapseUriMatch*) self, "");
#line 959 "volume-service.c"
	} else {
#line 142 "/home/heider/github/synapse/src/core/volume-service.vala"
		synapse_uri_match_set_uri ((SynapseUriMatch*) self, NULL);
#line 963 "volume-service.c"
	}
#line 145 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp21_ = self->priv->changed_signal_id;
#line 145 "/home/heider/github/synapse/src/core/volume-service.vala"
	if (_tmp21_ == ((gulong) 0)) {
#line 969 "volume-service.c"
		GVolume* _tmp22_ = NULL;
		gulong _tmp23_ = 0UL;
#line 147 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp22_ = self->priv->_volume;
#line 147 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp23_ = g_signal_connect_object (_tmp22_, "changed", (GCallback) _synapse_volume_service_volume_object_update_state_g_volume_changed, self, 0);
#line 147 "/home/heider/github/synapse/src/core/volume-service.vala"
		self->priv->changed_signal_id = _tmp23_;
#line 978 "volume-service.c"
	}
#line 150 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp25_ = value;
#line 150 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp26_ = g_volume_get_mount (_tmp25_);
#line 150 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp27_ = _tmp26_;
#line 150 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp28_ = _tmp27_ != NULL;
#line 150 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_object_unref0 (_tmp27_);
#line 150 "/home/heider/github/synapse/src/core/volume-service.vala"
	if (_tmp28_) {
#line 150 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp24_ = 1;
#line 994 "volume-service.c"
	} else {
#line 150 "/home/heider/github/synapse/src/core/volume-service.vala"
		_tmp24_ = 0;
#line 998 "volume-service.c"
	}
#line 150 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp29_ = synapse_match_get_title ((SynapseMatch*) self);
#line 150 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp30_ = _tmp29_;
#line 150 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp31_ = synapse_match_get_icon_name ((SynapseMatch*) self);
#line 150 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp32_ = _tmp31_;
#line 150 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp33_ = synapse_uri_match_get_uri ((SynapseUriMatch*) self);
#line 150 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp34_ = _tmp33_;
#line 150 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_debug ("volume-service.vala:150: vo[%p]: %s [%s], has_mount: %d, uri: %s", self, _tmp30_, _tmp32_, _tmp24_, _tmp34_);
#line 122 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_object_notify ((GObject *) self, "volume");
#line 1016 "volume-service.c"
}


static void synapse_volume_service_volume_object_class_init (SynapseVolumeServiceVolumeObjectClass * klass) {
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
	synapse_volume_service_volume_object_parent_class = g_type_class_peek_parent (klass);
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_type_class_add_private (klass, sizeof (SynapseVolumeServiceVolumeObjectPrivate));
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_synapse_volume_service_volume_object_get_property;
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_synapse_volume_service_volume_object_set_property;
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
	G_OBJECT_CLASS (klass)->finalize = synapse_volume_service_volume_object_finalize;
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_VOLUME, g_param_spec_object ("volume", "volume", "volume", g_volume_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 1033 "volume-service.c"
}


static void synapse_volume_service_volume_object_instance_init (SynapseVolumeServiceVolumeObject * self) {
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
	self->priv = SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_GET_PRIVATE (self);
#line 1040 "volume-service.c"
}


static void synapse_volume_service_volume_object_finalize (GObject* obj) {
	SynapseVolumeServiceVolumeObject * self;
	gulong _tmp0_ = 0UL;
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, SynapseVolumeServiceVolumeObject);
#line 171 "/home/heider/github/synapse/src/core/volume-service.vala"
	_tmp0_ = self->priv->changed_signal_id;
#line 171 "/home/heider/github/synapse/src/core/volume-service.vala"
	if (_tmp0_ != ((gulong) 0)) {
#line 175 "/home/heider/github/synapse/src/core/volume-service.vala"
		self->priv->changed_signal_id = (gulong) 0;
#line 1055 "volume-service.c"
	}
#line 118 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_object_unref0 (self->priv->_volume);
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
	G_OBJECT_CLASS (synapse_volume_service_volume_object_parent_class)->finalize (obj);
#line 1061 "volume-service.c"
}


GType synapse_volume_service_volume_object_get_type (void) {
	static volatile gsize synapse_volume_service_volume_object_type_id__volatile = 0;
	if (g_once_init_enter (&synapse_volume_service_volume_object_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynapseVolumeServiceVolumeObjectClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synapse_volume_service_volume_object_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynapseVolumeServiceVolumeObject), 0, (GInstanceInitFunc) synapse_volume_service_volume_object_instance_init, NULL };
		GType synapse_volume_service_volume_object_type_id;
		synapse_volume_service_volume_object_type_id = g_type_register_static (SYNAPSE_TYPE_URI_MATCH, "SynapseVolumeServiceVolumeObject", &g_define_type_info, 0);
		g_once_init_leave (&synapse_volume_service_volume_object_type_id__volatile, synapse_volume_service_volume_object_type_id);
	}
	return synapse_volume_service_volume_object_type_id__volatile;
}


static void _vala_synapse_volume_service_volume_object_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SynapseVolumeServiceVolumeObject * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, SynapseVolumeServiceVolumeObject);
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
	switch (property_id) {
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_VOLUME:
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
		g_value_set_object (value, synapse_volume_service_volume_object_get_volume (self));
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
		break;
#line 1088 "volume-service.c"
		default:
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
		break;
#line 1094 "volume-service.c"
	}
}


static void _vala_synapse_volume_service_volume_object_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SynapseVolumeServiceVolumeObject * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, SynapseVolumeServiceVolumeObject);
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
	switch (property_id) {
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_VOLUME:
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
		synapse_volume_service_volume_object_set_volume (self, g_value_get_object (value));
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
		break;
#line 1110 "volume-service.c"
		default:
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 114 "/home/heider/github/synapse/src/core/volume-service.vala"
		break;
#line 1116 "volume-service.c"
	}
}


static void synapse_volume_service_class_init (SynapseVolumeServiceClass * klass) {
#line 23 "/home/heider/github/synapse/src/core/volume-service.vala"
	synapse_volume_service_parent_class = g_type_class_peek_parent (klass);
#line 23 "/home/heider/github/synapse/src/core/volume-service.vala"
	g_type_class_add_private (klass, sizeof (SynapseVolumeServicePrivate));
#line 23 "/home/heider/github/synapse/src/core/volume-service.vala"
	G_OBJECT_CLASS (klass)->constructor = synapse_volume_service_constructor;
#line 23 "/home/heider/github/synapse/src/core/volume-service.vala"
	G_OBJECT_CLASS (klass)->finalize = synapse_volume_service_finalize;
#line 1130 "volume-service.c"
}


static void synapse_volume_service_instance_init (SynapseVolumeService * self) {
#line 23 "/home/heider/github/synapse/src/core/volume-service.vala"
	self->priv = SYNAPSE_VOLUME_SERVICE_GET_PRIVATE (self);
#line 1137 "volume-service.c"
}


static void synapse_volume_service_finalize (GObject* obj) {
	SynapseVolumeService * self;
#line 23 "/home/heider/github/synapse/src/core/volume-service.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYNAPSE_TYPE_VOLUME_SERVICE, SynapseVolumeService);
#line 38 "/home/heider/github/synapse/src/core/volume-service.vala"
	synapse_volume_service_instance = NULL;
#line 41 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_object_unref0 (self->priv->vm);
#line 42 "/home/heider/github/synapse/src/core/volume-service.vala"
	_g_object_unref0 (self->priv->volumes);
#line 23 "/home/heider/github/synapse/src/core/volume-service.vala"
	G_OBJECT_CLASS (synapse_volume_service_parent_class)->finalize (obj);
#line 1153 "volume-service.c"
}


GType synapse_volume_service_get_type (void) {
	static volatile gsize synapse_volume_service_type_id__volatile = 0;
	if (g_once_init_enter (&synapse_volume_service_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynapseVolumeServiceClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synapse_volume_service_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynapseVolumeService), 0, (GInstanceInitFunc) synapse_volume_service_instance_init, NULL };
		GType synapse_volume_service_type_id;
		synapse_volume_service_type_id = g_type_register_static (G_TYPE_OBJECT, "SynapseVolumeService", &g_define_type_info, 0);
		g_once_init_leave (&synapse_volume_service_type_id__volatile, synapse_volume_service_type_id);
	}
	return synapse_volume_service_type_id__volatile;
}



