/* file-op-plugin.c generated by valac 0.30.0, the Vala compiler
 * generated from file-op-plugin.vala, do not modify */

/*
 * Copyright (C) 2010 Michal Hruby <michal.mhr@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA.
 *
 * Authored by Alberto Aldegheri <albyrock87+dev@gmail.com>
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <synapse-core.h>
#include <gee.h>
#include <glib/gi18n-lib.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>


#define SYNAPSE_TYPE_FILE_OP_PLUGIN (synapse_file_op_plugin_get_type ())
#define SYNAPSE_FILE_OP_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_TYPE_FILE_OP_PLUGIN, SynapseFileOpPlugin))
#define SYNAPSE_FILE_OP_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_TYPE_FILE_OP_PLUGIN, SynapseFileOpPluginClass))
#define SYNAPSE_IS_FILE_OP_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_TYPE_FILE_OP_PLUGIN))
#define SYNAPSE_IS_FILE_OP_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_TYPE_FILE_OP_PLUGIN))
#define SYNAPSE_FILE_OP_PLUGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_TYPE_FILE_OP_PLUGIN, SynapseFileOpPluginClass))

typedef struct _SynapseFileOpPlugin SynapseFileOpPlugin;
typedef struct _SynapseFileOpPluginClass SynapseFileOpPluginClass;
typedef struct _SynapseFileOpPluginPrivate SynapseFileOpPluginPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define SYNAPSE_FILE_OP_PLUGIN_TYPE_REMOVE (synapse_file_op_plugin_remove_get_type ())
#define SYNAPSE_FILE_OP_PLUGIN_REMOVE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_FILE_OP_PLUGIN_TYPE_REMOVE, SynapseFileOpPluginRemove))
#define SYNAPSE_FILE_OP_PLUGIN_REMOVE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_FILE_OP_PLUGIN_TYPE_REMOVE, SynapseFileOpPluginRemoveClass))
#define SYNAPSE_FILE_OP_PLUGIN_IS_REMOVE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_FILE_OP_PLUGIN_TYPE_REMOVE))
#define SYNAPSE_FILE_OP_PLUGIN_IS_REMOVE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_FILE_OP_PLUGIN_TYPE_REMOVE))
#define SYNAPSE_FILE_OP_PLUGIN_REMOVE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_FILE_OP_PLUGIN_TYPE_REMOVE, SynapseFileOpPluginRemoveClass))

typedef struct _SynapseFileOpPluginRemove SynapseFileOpPluginRemove;
typedef struct _SynapseFileOpPluginRemoveClass SynapseFileOpPluginRemoveClass;

#define SYNAPSE_FILE_OP_PLUGIN_TYPE_RENAME_TO (synapse_file_op_plugin_rename_to_get_type ())
#define SYNAPSE_FILE_OP_PLUGIN_RENAME_TO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_FILE_OP_PLUGIN_TYPE_RENAME_TO, SynapseFileOpPluginRenameTo))
#define SYNAPSE_FILE_OP_PLUGIN_RENAME_TO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_FILE_OP_PLUGIN_TYPE_RENAME_TO, SynapseFileOpPluginRenameToClass))
#define SYNAPSE_FILE_OP_PLUGIN_IS_RENAME_TO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_FILE_OP_PLUGIN_TYPE_RENAME_TO))
#define SYNAPSE_FILE_OP_PLUGIN_IS_RENAME_TO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_FILE_OP_PLUGIN_TYPE_RENAME_TO))
#define SYNAPSE_FILE_OP_PLUGIN_RENAME_TO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_FILE_OP_PLUGIN_TYPE_RENAME_TO, SynapseFileOpPluginRenameToClass))

typedef struct _SynapseFileOpPluginRenameTo SynapseFileOpPluginRenameTo;
typedef struct _SynapseFileOpPluginRenameToClass SynapseFileOpPluginRenameToClass;
typedef struct _SynapseFileOpPluginRemovePrivate SynapseFileOpPluginRemovePrivate;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _SynapseFileOpPluginRenameToPrivate SynapseFileOpPluginRenameToPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _SynapseFileOpPlugin {
	GObject parent_instance;
	SynapseFileOpPluginPrivate * priv;
};

struct _SynapseFileOpPluginClass {
	GObjectClass parent_class;
};

struct _SynapseFileOpPluginPrivate {
	gboolean _enabled;
	GeeList* actions;
};

struct _SynapseFileOpPluginRemove {
	SynapseAction parent_instance;
	SynapseFileOpPluginRemovePrivate * priv;
};

struct _SynapseFileOpPluginRemoveClass {
	SynapseActionClass parent_class;
};

struct _SynapseFileOpPluginRenameTo {
	SynapseAction parent_instance;
	SynapseFileOpPluginRenameToPrivate * priv;
};

struct _SynapseFileOpPluginRenameToClass {
	SynapseActionClass parent_class;
};


static gpointer synapse_file_op_plugin_parent_class = NULL;
static gpointer synapse_file_op_plugin_remove_parent_class = NULL;
static gpointer synapse_file_op_plugin_rename_to_parent_class = NULL;
static SynapseActivatableIface* synapse_file_op_plugin_synapse_activatable_parent_iface = NULL;
static SynapseActionProviderIface* synapse_file_op_plugin_synapse_action_provider_parent_iface = NULL;

GType synapse_file_op_plugin_get_type (void) G_GNUC_CONST;
#define SYNAPSE_FILE_OP_PLUGIN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYNAPSE_TYPE_FILE_OP_PLUGIN, SynapseFileOpPluginPrivate))
enum  {
	SYNAPSE_FILE_OP_PLUGIN_DUMMY_PROPERTY,
	SYNAPSE_FILE_OP_PLUGIN_ENABLED
};
static void synapse_file_op_plugin_real_activate (SynapseActivatable* base);
static void synapse_file_op_plugin_real_deactivate (SynapseActivatable* base);
static void synapse_file_op_plugin_register_plugin (void);
static void _synapse_file_op_plugin_register_plugin_synapse_plugin_register_func (void);
static SynapseResultSet* synapse_file_op_plugin_real_find_for_match (SynapseActionProvider* base, SynapseQuery* query, SynapseMatch* match);
SynapseFileOpPlugin* synapse_file_op_plugin_new (void);
SynapseFileOpPlugin* synapse_file_op_plugin_construct (GType object_type);
static GObject * synapse_file_op_plugin_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static SynapseFileOpPluginRemove* synapse_file_op_plugin_remove_new (void);
static SynapseFileOpPluginRemove* synapse_file_op_plugin_remove_construct (GType object_type);
static GType synapse_file_op_plugin_remove_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static SynapseFileOpPluginRenameTo* synapse_file_op_plugin_rename_to_new (void);
static SynapseFileOpPluginRenameTo* synapse_file_op_plugin_rename_to_construct (GType object_type);
static GType synapse_file_op_plugin_rename_to_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
enum  {
	SYNAPSE_FILE_OP_PLUGIN_REMOVE_DUMMY_PROPERTY
};
static void synapse_file_op_plugin_remove_real_do_execute (SynapseAction* base, SynapseMatch* source, SynapseMatch* target);
static gboolean synapse_file_op_plugin_remove_real_valid_for_match (SynapseAction* base, SynapseMatch* match);
enum  {
	SYNAPSE_FILE_OP_PLUGIN_RENAME_TO_DUMMY_PROPERTY
};
static void synapse_file_op_plugin_rename_to_real_do_execute (SynapseAction* base, SynapseMatch* source, SynapseMatch* target);
static gboolean synapse_file_op_plugin_rename_to_real_needs_target (SynapseMatch* base);
static SynapseQueryFlags synapse_file_op_plugin_rename_to_real_target_flags (SynapseMatch* base);
static gboolean synapse_file_op_plugin_rename_to_real_valid_for_match (SynapseAction* base, SynapseMatch* match);
static void synapse_file_op_plugin_finalize (GObject* obj);
static void _vala_synapse_file_op_plugin_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_synapse_file_op_plugin_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static void synapse_file_op_plugin_real_activate (SynapseActivatable* base) {
	SynapseFileOpPlugin * self;
#line 28 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self = (SynapseFileOpPlugin*) base;
#line 152 "file-op-plugin.c"
}


static void synapse_file_op_plugin_real_deactivate (SynapseActivatable* base) {
	SynapseFileOpPlugin * self;
#line 32 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self = (SynapseFileOpPlugin*) base;
#line 160 "file-op-plugin.c"
}


static void _synapse_file_op_plugin_register_plugin_synapse_plugin_register_func (void) {
#line 123 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	synapse_file_op_plugin_register_plugin ();
#line 167 "file-op-plugin.c"
}


static void synapse_file_op_plugin_register_plugin (void) {
	SynapsePluginRegistry* _tmp0_ = NULL;
	SynapsePluginRegistry* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
#line 123 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp0_ = synapse_plugin_registry_get_default ();
#line 123 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp1_ = _tmp0_;
#line 123 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp2_ = _ ("File Operations");
#line 123 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp3_ = _ ("Copy, Cut, Paste and Delete files");
#line 123 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	synapse_plugin_registry_register_plugin (_tmp1_, SYNAPSE_TYPE_FILE_OP_PLUGIN, _tmp2_, _tmp3_, "stock_copy", _synapse_file_op_plugin_register_plugin_synapse_plugin_register_func, TRUE, "");
#line 123 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_g_object_unref0 (_tmp1_);
#line 188 "file-op-plugin.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	return self ? g_object_ref (self) : NULL;
#line 195 "file-op-plugin.c"
}


static SynapseResultSet* synapse_file_op_plugin_real_find_for_match (SynapseActionProvider* base, SynapseQuery* query, SynapseMatch* match) {
	SynapseFileOpPlugin * self;
	SynapseResultSet* result = NULL;
	gboolean query_empty = FALSE;
	SynapseQuery _tmp0_ = {0};
	const gchar* _tmp1_ = NULL;
	SynapseResultSet* results = NULL;
	SynapseResultSet* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
#line 147 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self = (SynapseFileOpPlugin*) base;
#line 147 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	g_return_val_if_fail (query != NULL, NULL);
#line 147 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	g_return_val_if_fail (match != NULL, NULL);
#line 149 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp0_ = *query;
#line 149 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp1_ = _tmp0_.query_string;
#line 149 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	query_empty = g_strcmp0 (_tmp1_, "") == 0;
#line 150 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp2_ = synapse_result_set_new ();
#line 150 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	results = _tmp2_;
#line 152 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp3_ = query_empty;
#line 152 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	if (_tmp3_) {
#line 228 "file-op-plugin.c"
		{
			GeeList* _action_list = NULL;
			GeeList* _tmp4_ = NULL;
			GeeList* _tmp5_ = NULL;
			gint _action_size = 0;
			GeeList* _tmp6_ = NULL;
			gint _tmp7_ = 0;
			gint _tmp8_ = 0;
			gint _action_index = 0;
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_tmp4_ = self->priv->actions;
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_tmp5_ = _g_object_ref0 (_tmp4_);
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_action_list = _tmp5_;
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_tmp6_ = _action_list;
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_tmp7_ = gee_collection_get_size ((GeeCollection*) _tmp6_);
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_tmp8_ = _tmp7_;
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_action_size = _tmp8_;
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_action_index = -1;
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			while (TRUE) {
#line 256 "file-op-plugin.c"
				gint _tmp9_ = 0;
				gint _tmp10_ = 0;
				gint _tmp11_ = 0;
				SynapseAction* action = NULL;
				GeeList* _tmp12_ = NULL;
				gint _tmp13_ = 0;
				gpointer _tmp14_ = NULL;
				SynapseAction* _tmp15_ = NULL;
				SynapseMatch* _tmp16_ = NULL;
				gboolean _tmp17_ = FALSE;
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp9_ = _action_index;
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_action_index = _tmp9_ + 1;
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp10_ = _action_index;
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp11_ = _action_size;
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				if (!(_tmp10_ < _tmp11_)) {
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					break;
#line 279 "file-op-plugin.c"
				}
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp12_ = _action_list;
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp13_ = _action_index;
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp14_ = gee_list_get (_tmp12_, _tmp13_);
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				action = (SynapseAction*) _tmp14_;
#line 156 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp15_ = action;
#line 156 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp16_ = match;
#line 156 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp17_ = synapse_action_valid_for_match (_tmp15_, _tmp16_);
#line 156 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				if (_tmp17_) {
#line 297 "file-op-plugin.c"
					SynapseResultSet* _tmp18_ = NULL;
					SynapseAction* _tmp19_ = NULL;
					SynapseAction* _tmp20_ = NULL;
					SynapseMatch* _tmp21_ = NULL;
					gint _tmp22_ = 0;
#line 158 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					_tmp18_ = results;
#line 158 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					_tmp19_ = action;
#line 158 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					_tmp20_ = action;
#line 158 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					_tmp21_ = match;
#line 158 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					_tmp22_ = synapse_action_get_relevancy_for_match (_tmp20_, _tmp21_);
#line 158 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					synapse_result_set_add (_tmp18_, (SynapseMatch*) _tmp19_, _tmp22_);
#line 315 "file-op-plugin.c"
				}
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_g_object_unref0 (action);
#line 319 "file-op-plugin.c"
			}
#line 154 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_g_object_unref0 (_action_list);
#line 323 "file-op-plugin.c"
		}
	} else {
		GeeList* matchers = NULL;
		SynapseQuery _tmp23_ = {0};
		const gchar* _tmp24_ = NULL;
		GeeList* _tmp25_ = NULL;
#line 164 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp23_ = *query;
#line 164 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp24_ = _tmp23_.query_string;
#line 164 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp25_ = synapse_query_get_matchers_for_query (_tmp24_, 0, G_REGEX_OPTIMIZE | G_REGEX_CASELESS);
#line 164 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		matchers = _tmp25_;
#line 338 "file-op-plugin.c"
		{
			GeeList* _action_list = NULL;
			GeeList* _tmp26_ = NULL;
			GeeList* _tmp27_ = NULL;
			gint _action_size = 0;
			GeeList* _tmp28_ = NULL;
			gint _tmp29_ = 0;
			gint _tmp30_ = 0;
			gint _action_index = 0;
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_tmp26_ = self->priv->actions;
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_tmp27_ = _g_object_ref0 (_tmp26_);
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_action_list = _tmp27_;
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_tmp28_ = _action_list;
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_tmp29_ = gee_collection_get_size ((GeeCollection*) _tmp28_);
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_tmp30_ = _tmp29_;
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_action_size = _tmp30_;
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_action_index = -1;
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			while (TRUE) {
#line 366 "file-op-plugin.c"
				gint _tmp31_ = 0;
				gint _tmp32_ = 0;
				gint _tmp33_ = 0;
				SynapseAction* action = NULL;
				GeeList* _tmp34_ = NULL;
				gint _tmp35_ = 0;
				gpointer _tmp36_ = NULL;
				SynapseAction* _tmp37_ = NULL;
				SynapseMatch* _tmp38_ = NULL;
				gboolean _tmp39_ = FALSE;
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp31_ = _action_index;
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_action_index = _tmp31_ + 1;
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp32_ = _action_index;
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp33_ = _action_size;
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				if (!(_tmp32_ < _tmp33_)) {
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					break;
#line 389 "file-op-plugin.c"
				}
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp34_ = _action_list;
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp35_ = _action_index;
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp36_ = gee_list_get (_tmp34_, _tmp35_);
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				action = (SynapseAction*) _tmp36_;
#line 168 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp37_ = action;
#line 168 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp38_ = match;
#line 168 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_tmp39_ = synapse_action_valid_for_match (_tmp37_, _tmp38_);
#line 168 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				if (!_tmp39_) {
#line 168 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					_g_object_unref0 (action);
#line 168 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					continue;
#line 411 "file-op-plugin.c"
				}
				{
					GeeList* _matcher_list = NULL;
					GeeList* _tmp40_ = NULL;
					GeeList* _tmp41_ = NULL;
					gint _matcher_size = 0;
					GeeList* _tmp42_ = NULL;
					gint _tmp43_ = 0;
					gint _tmp44_ = 0;
					gint _matcher_index = 0;
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					_tmp40_ = matchers;
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					_tmp41_ = _g_object_ref0 (_tmp40_);
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					_matcher_list = _tmp41_;
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					_tmp42_ = _matcher_list;
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					_tmp43_ = gee_collection_get_size ((GeeCollection*) _tmp42_);
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					_tmp44_ = _tmp43_;
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					_matcher_size = _tmp44_;
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					_matcher_index = -1;
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					while (TRUE) {
#line 440 "file-op-plugin.c"
						gint _tmp45_ = 0;
						gint _tmp46_ = 0;
						gint _tmp47_ = 0;
						GeeMapEntry* matcher = NULL;
						GeeList* _tmp48_ = NULL;
						gint _tmp49_ = 0;
						gpointer _tmp50_ = NULL;
						GeeMapEntry* _tmp51_ = NULL;
						gconstpointer _tmp52_ = NULL;
						GRegex* _tmp53_ = NULL;
						SynapseAction* _tmp54_ = NULL;
						const gchar* _tmp55_ = NULL;
						const gchar* _tmp56_ = NULL;
						gboolean _tmp57_ = FALSE;
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						_tmp45_ = _matcher_index;
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						_matcher_index = _tmp45_ + 1;
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						_tmp46_ = _matcher_index;
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						_tmp47_ = _matcher_size;
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						if (!(_tmp46_ < _tmp47_)) {
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
							break;
#line 467 "file-op-plugin.c"
						}
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						_tmp48_ = _matcher_list;
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						_tmp49_ = _matcher_index;
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						_tmp50_ = gee_list_get (_tmp48_, _tmp49_);
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						matcher = (GeeMapEntry*) _tmp50_;
#line 171 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						_tmp51_ = matcher;
#line 171 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						_tmp52_ = gee_map_entry_get_key (_tmp51_);
#line 171 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						_tmp53_ = _tmp52_;
#line 171 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						_tmp54_ = action;
#line 171 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						_tmp55_ = synapse_match_get_title ((SynapseMatch*) _tmp54_);
#line 171 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						_tmp56_ = _tmp55_;
#line 171 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						_tmp57_ = g_regex_match ((GRegex*) _tmp53_, _tmp56_, 0, NULL);
#line 171 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						if (_tmp57_) {
#line 493 "file-op-plugin.c"
							SynapseResultSet* _tmp58_ = NULL;
							SynapseAction* _tmp59_ = NULL;
							GeeMapEntry* _tmp60_ = NULL;
							gconstpointer _tmp61_ = NULL;
							gint _tmp62_ = 0;
#line 173 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
							_tmp58_ = results;
#line 173 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
							_tmp59_ = action;
#line 173 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
							_tmp60_ = matcher;
#line 173 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
							_tmp61_ = gee_map_entry_get_value (_tmp60_);
#line 173 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
							_tmp62_ = _tmp61_;
#line 173 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
							synapse_result_set_add (_tmp58_, (SynapseMatch*) _tmp59_, (gint) ((gintptr) _tmp62_));
#line 174 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
							_g_object_unref0 (matcher);
#line 174 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
							break;
#line 515 "file-op-plugin.c"
						}
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
						_g_object_unref0 (matcher);
#line 519 "file-op-plugin.c"
					}
#line 169 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
					_g_object_unref0 (_matcher_list);
#line 523 "file-op-plugin.c"
				}
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
				_g_object_unref0 (action);
#line 527 "file-op-plugin.c"
			}
#line 166 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
			_g_object_unref0 (_action_list);
#line 531 "file-op-plugin.c"
		}
#line 152 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_g_object_unref0 (matchers);
#line 535 "file-op-plugin.c"
	}
#line 180 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	result = results;
#line 180 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	return result;
#line 541 "file-op-plugin.c"
}


SynapseFileOpPlugin* synapse_file_op_plugin_construct (GType object_type) {
	SynapseFileOpPlugin * self = NULL;
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self = (SynapseFileOpPlugin*) g_object_new (object_type, NULL);
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	return self;
#line 551 "file-op-plugin.c"
}


SynapseFileOpPlugin* synapse_file_op_plugin_new (void) {
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	return synapse_file_op_plugin_construct (SYNAPSE_TYPE_FILE_OP_PLUGIN);
#line 558 "file-op-plugin.c"
}


static gboolean synapse_file_op_plugin_real_get_enabled (SynapseActivatable* base) {
	gboolean result;
	SynapseFileOpPlugin* self;
	gboolean _tmp0_ = FALSE;
#line 26 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self = (SynapseFileOpPlugin*) base;
#line 26 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp0_ = self->priv->_enabled;
#line 26 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	result = _tmp0_;
#line 26 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	return result;
#line 574 "file-op-plugin.c"
}


static void synapse_file_op_plugin_real_set_enabled (SynapseActivatable* base, gboolean value) {
	SynapseFileOpPlugin* self;
	gboolean _tmp0_ = FALSE;
#line 26 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self = (SynapseFileOpPlugin*) base;
#line 26 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp0_ = value;
#line 26 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self->priv->_enabled = _tmp0_;
#line 26 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	g_object_notify ((GObject *) self, "enabled");
#line 589 "file-op-plugin.c"
}


static GObject * synapse_file_op_plugin_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	SynapseFileOpPlugin * self;
	GeeArrayList* _tmp0_ = NULL;
	GeeList* _tmp1_ = NULL;
	SynapseFileOpPluginRemove* _tmp2_ = NULL;
	SynapseFileOpPluginRemove* _tmp3_ = NULL;
	GeeList* _tmp4_ = NULL;
	SynapseFileOpPluginRenameTo* _tmp5_ = NULL;
	SynapseFileOpPluginRenameTo* _tmp6_ = NULL;
#line 139 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	parent_class = G_OBJECT_CLASS (synapse_file_op_plugin_parent_class);
#line 139 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 139 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYNAPSE_TYPE_FILE_OP_PLUGIN, SynapseFileOpPlugin);
#line 141 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp0_ = gee_array_list_new (SYNAPSE_TYPE_ACTION, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
#line 141 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_g_object_unref0 (self->priv->actions);
#line 141 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self->priv->actions = (GeeList*) _tmp0_;
#line 143 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp1_ = self->priv->actions;
#line 143 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp2_ = synapse_file_op_plugin_remove_new ();
#line 143 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp3_ = _tmp2_;
#line 143 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	gee_collection_add ((GeeCollection*) _tmp1_, (SynapseAction*) _tmp3_);
#line 143 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_g_object_unref0 (_tmp3_);
#line 144 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp4_ = self->priv->actions;
#line 144 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp5_ = synapse_file_op_plugin_rename_to_new ();
#line 144 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp6_ = _tmp5_;
#line 144 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	gee_collection_add ((GeeCollection*) _tmp4_, (SynapseAction*) _tmp6_);
#line 144 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_g_object_unref0 (_tmp6_);
#line 139 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	return obj;
#line 638 "file-op-plugin.c"
}


static SynapseFileOpPluginRemove* synapse_file_op_plugin_remove_construct (GType object_type) {
	SynapseFileOpPluginRemove * self = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 40 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp0_ = _ ("Remove");
#line 40 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp1_ = _ ("Move to Trash");
#line 40 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self = (SynapseFileOpPluginRemove*) g_object_new (object_type, "title", _tmp0_, "description", _tmp1_, "icon-name", "user-trash", "has-thumbnail", FALSE, "default-relevancy", SYNAPSE_MATCH_SCORE_POOR, NULL);
#line 38 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	return self;
#line 654 "file-op-plugin.c"
}


static SynapseFileOpPluginRemove* synapse_file_op_plugin_remove_new (void) {
#line 38 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	return synapse_file_op_plugin_remove_construct (SYNAPSE_FILE_OP_PLUGIN_TYPE_REMOVE);
#line 661 "file-op-plugin.c"
}


static void synapse_file_op_plugin_remove_real_do_execute (SynapseAction* base, SynapseMatch* source, SynapseMatch* target) {
	SynapseFileOpPluginRemove * self;
	SynapseUriMatch* uri_match = NULL;
	SynapseMatch* _tmp0_ = NULL;
	GFile* f = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	GFile* _tmp3_ = NULL;
	GError * _inner_error_ = NULL;
#line 46 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self = (SynapseFileOpPluginRemove*) base;
#line 46 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	g_return_if_fail (source != NULL);
#line 48 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp0_ = source;
#line 48 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	uri_match = G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, SYNAPSE_TYPE_URI_MATCH) ? ((SynapseUriMatch*) _tmp0_) : NULL;
#line 49 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	g_return_if_fail (uri_match != NULL);
#line 51 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp1_ = synapse_uri_match_get_uri (uri_match);
#line 51 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp2_ = _tmp1_;
#line 51 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp3_ = g_file_new_for_uri (_tmp2_);
#line 51 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	f = _tmp3_;
#line 692 "file-op-plugin.c"
	{
#line 54 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		g_file_trash (f, NULL, &_inner_error_);
#line 54 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 698 "file-op-plugin.c"
			goto __catch13_g_error;
		}
	}
	goto __finally13;
	__catch13_g_error:
	{
		GError* err = NULL;
		GError* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
#line 52 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		err = _inner_error_;
#line 52 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_inner_error_ = NULL;
#line 58 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp4_ = err;
#line 58 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp5_ = _tmp4_->message;
#line 58 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		g_warning ("file-op-plugin.vala:58: %s", _tmp5_);
#line 52 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_g_error_free0 (err);
#line 720 "file-op-plugin.c"
	}
	__finally13:
#line 52 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 52 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_g_object_unref0 (f);
#line 52 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 52 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		g_clear_error (&_inner_error_);
#line 52 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		return;
#line 733 "file-op-plugin.c"
	}
#line 46 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_g_object_unref0 (f);
#line 737 "file-op-plugin.c"
}


static gboolean synapse_file_op_plugin_remove_real_valid_for_match (SynapseAction* base, SynapseMatch* match) {
	SynapseFileOpPluginRemove * self;
	gboolean result = FALSE;
	SynapseMatch* _tmp0_ = NULL;
#line 62 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self = (SynapseFileOpPluginRemove*) base;
#line 62 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	g_return_val_if_fail (match != NULL, FALSE);
#line 64 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp0_ = match;
#line 64 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	result = G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, SYNAPSE_TYPE_URI_MATCH);
#line 64 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	return result;
#line 755 "file-op-plugin.c"
}


static void synapse_file_op_plugin_remove_class_init (SynapseFileOpPluginRemoveClass * klass) {
#line 36 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	synapse_file_op_plugin_remove_parent_class = g_type_class_peek_parent (klass);
#line 36 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	((SynapseActionClass *) klass)->do_execute = synapse_file_op_plugin_remove_real_do_execute;
#line 36 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	((SynapseActionClass *) klass)->valid_for_match = synapse_file_op_plugin_remove_real_valid_for_match;
#line 766 "file-op-plugin.c"
}


static void synapse_file_op_plugin_remove_instance_init (SynapseFileOpPluginRemove * self) {
}


static GType synapse_file_op_plugin_remove_get_type (void) {
	static volatile gsize synapse_file_op_plugin_remove_type_id__volatile = 0;
	if (g_once_init_enter (&synapse_file_op_plugin_remove_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynapseFileOpPluginRemoveClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synapse_file_op_plugin_remove_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynapseFileOpPluginRemove), 0, (GInstanceInitFunc) synapse_file_op_plugin_remove_instance_init, NULL };
		GType synapse_file_op_plugin_remove_type_id;
		synapse_file_op_plugin_remove_type_id = g_type_register_static (SYNAPSE_TYPE_ACTION, "SynapseFileOpPluginRemove", &g_define_type_info, 0);
		g_once_init_leave (&synapse_file_op_plugin_remove_type_id__volatile, synapse_file_op_plugin_remove_type_id);
	}
	return synapse_file_op_plugin_remove_type_id__volatile;
}


static SynapseFileOpPluginRenameTo* synapse_file_op_plugin_rename_to_construct (GType object_type) {
	SynapseFileOpPluginRenameTo * self = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 72 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp0_ = _ ("Rename to");
#line 72 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp1_ = _ ("Rename the file to...");
#line 72 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self = (SynapseFileOpPluginRenameTo*) g_object_new (object_type, "title", _tmp0_, "description", _tmp1_, "icon-name", "stock_save-as", "has-thumbnail", FALSE, "default-relevancy", SYNAPSE_MATCH_SCORE_AVERAGE, NULL);
#line 70 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	return self;
#line 798 "file-op-plugin.c"
}


static SynapseFileOpPluginRenameTo* synapse_file_op_plugin_rename_to_new (void) {
#line 70 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	return synapse_file_op_plugin_rename_to_construct (SYNAPSE_FILE_OP_PLUGIN_TYPE_RENAME_TO);
#line 805 "file-op-plugin.c"
}


static void synapse_file_op_plugin_rename_to_real_do_execute (SynapseAction* base, SynapseMatch* source, SynapseMatch* target) {
	SynapseFileOpPluginRenameTo * self;
	SynapseMatch* _tmp0_ = NULL;
	SynapseUriMatch* uri_match = NULL;
	SynapseMatch* _tmp1_ = NULL;
	SynapseUriMatch* _tmp2_ = NULL;
	GFile* f = NULL;
	SynapseUriMatch* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	GFile* _tmp6_ = NULL;
	GFile* _tmp7_ = NULL;
	gboolean _tmp8_ = FALSE;
	gchar* newpath = NULL;
	GFile* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	SynapseMatch* _tmp18_ = NULL;
	const gchar* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	GFile* f2 = NULL;
	const gchar* _tmp23_ = NULL;
	GFile* _tmp24_ = NULL;
	GFile* _tmp25_ = NULL;
	gchar* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
	const gchar* _tmp28_ = NULL;
	gboolean done = FALSE;
	gboolean _tmp33_ = FALSE;
	GError * _inner_error_ = NULL;
#line 78 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self = (SynapseFileOpPluginRenameTo*) base;
#line 78 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	g_return_if_fail (source != NULL);
#line 80 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp0_ = target;
#line 80 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	if (_tmp0_ == NULL) {
#line 80 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		return;
#line 853 "file-op-plugin.c"
	}
#line 82 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp1_ = source;
#line 82 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	uri_match = G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, SYNAPSE_TYPE_URI_MATCH) ? ((SynapseUriMatch*) _tmp1_) : NULL;
#line 83 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp2_ = uri_match;
#line 83 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	if (_tmp2_ == NULL) {
#line 83 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		return;
#line 865 "file-op-plugin.c"
	}
#line 86 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp3_ = uri_match;
#line 86 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp4_ = synapse_uri_match_get_uri (_tmp3_);
#line 86 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp5_ = _tmp4_;
#line 86 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp6_ = g_file_new_for_uri (_tmp5_);
#line 86 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_g_object_unref0 (f);
#line 86 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	f = _tmp6_;
#line 87 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp7_ = f;
#line 87 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp8_ = g_file_query_exists (_tmp7_, NULL);
#line 87 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	if (!_tmp8_) {
#line 885 "file-op-plugin.c"
		const gchar* _tmp9_ = NULL;
		SynapseUriMatch* _tmp10_ = NULL;
		const gchar* _tmp11_ = NULL;
		const gchar* _tmp12_ = NULL;
#line 89 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp9_ = _ ("File \"%s\"does not exist.");
#line 89 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp10_ = uri_match;
#line 89 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp11_ = synapse_uri_match_get_uri (_tmp10_);
#line 89 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp12_ = _tmp11_;
#line 89 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		g_warning (_tmp9_, _tmp12_);
#line 90 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_g_object_unref0 (f);
#line 90 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		return;
#line 904 "file-op-plugin.c"
	}
#line 92 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp13_ = f;
#line 92 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp14_ = g_file_get_path (_tmp13_);
#line 92 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp15_ = _tmp14_;
#line 92 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp16_ = g_path_get_dirname (_tmp15_);
#line 92 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp17_ = _tmp16_;
#line 92 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp18_ = target;
#line 92 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp19_ = synapse_match_get_title (_tmp18_);
#line 92 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp20_ = _tmp19_;
#line 92 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp21_ = g_build_filename (_tmp17_, _tmp20_, NULL);
#line 92 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp22_ = _tmp21_;
#line 92 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_g_free0 (_tmp17_);
#line 92 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_g_free0 (_tmp15_);
#line 92 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	newpath = _tmp22_;
#line 93 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp23_ = newpath;
#line 93 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp24_ = g_file_new_for_path (_tmp23_);
#line 93 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	f2 = _tmp24_;
#line 94 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp25_ = f;
#line 94 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp26_ = g_file_get_path (_tmp25_);
#line 94 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp27_ = _tmp26_;
#line 94 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp28_ = newpath;
#line 94 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	g_debug ("file-op-plugin.vala:94: Moving \"%s\" to \"%s\"", _tmp27_, _tmp28_);
#line 94 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_g_free0 (_tmp27_);
#line 95 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	done = FALSE;
#line 952 "file-op-plugin.c"
	{
		gboolean _tmp29_ = FALSE;
		GFile* _tmp30_ = NULL;
		GFile* _tmp31_ = NULL;
		gboolean _tmp32_ = FALSE;
#line 97 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp30_ = f;
#line 97 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp31_ = f2;
#line 97 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp32_ = g_file_move (_tmp30_, _tmp31_, G_FILE_COPY_OVERWRITE, NULL, NULL, NULL, &_inner_error_);
#line 97 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp29_ = _tmp32_;
#line 97 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 968 "file-op-plugin.c"
			goto __catch14_g_error;
		}
#line 97 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		done = _tmp29_;
#line 973 "file-op-plugin.c"
	}
	goto __finally14;
	__catch14_g_error:
	{
		GError* err = NULL;
#line 96 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		err = _inner_error_;
#line 96 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_inner_error_ = NULL;
#line 96 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_g_error_free0 (err);
#line 985 "file-op-plugin.c"
	}
	__finally14:
#line 96 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 96 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_g_object_unref0 (f2);
#line 96 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_g_free0 (newpath);
#line 96 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_g_object_unref0 (f);
#line 96 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 96 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		g_clear_error (&_inner_error_);
#line 96 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		return;
#line 1002 "file-op-plugin.c"
	}
#line 99 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp33_ = done;
#line 99 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	if (!_tmp33_) {
#line 1008 "file-op-plugin.c"
		const gchar* _tmp34_ = NULL;
		GFile* _tmp35_ = NULL;
		gchar* _tmp36_ = NULL;
		gchar* _tmp37_ = NULL;
		const gchar* _tmp38_ = NULL;
#line 101 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp34_ = _ ("Cannot move \"%s\" to \"%s\"");
#line 101 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp35_ = f;
#line 101 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp36_ = g_file_get_path (_tmp35_);
#line 101 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp37_ = _tmp36_;
#line 101 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp38_ = newpath;
#line 101 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		g_warning (_tmp34_, _tmp37_, _tmp38_);
#line 101 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_g_free0 (_tmp37_);
#line 1028 "file-op-plugin.c"
	}
#line 78 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_g_object_unref0 (f2);
#line 78 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_g_free0 (newpath);
#line 78 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_g_object_unref0 (f);
#line 1036 "file-op-plugin.c"
}


static gboolean synapse_file_op_plugin_rename_to_real_needs_target (SynapseMatch* base) {
	SynapseFileOpPluginRenameTo * self;
	gboolean result = FALSE;
#line 105 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self = (SynapseFileOpPluginRenameTo*) base;
#line 107 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	result = TRUE;
#line 107 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	return result;
#line 1049 "file-op-plugin.c"
}


static SynapseQueryFlags synapse_file_op_plugin_rename_to_real_target_flags (SynapseMatch* base) {
	SynapseFileOpPluginRenameTo * self;
	SynapseQueryFlags result = 0;
#line 110 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self = (SynapseFileOpPluginRenameTo*) base;
#line 112 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	result = SYNAPSE_QUERY_FLAGS_TEXT;
#line 112 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	return result;
#line 1062 "file-op-plugin.c"
}


static gboolean synapse_file_op_plugin_rename_to_real_valid_for_match (SynapseAction* base, SynapseMatch* match) {
	SynapseFileOpPluginRenameTo * self;
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	SynapseMatch* _tmp1_ = NULL;
#line 115 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self = (SynapseFileOpPluginRenameTo*) base;
#line 115 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	g_return_val_if_fail (match != NULL, FALSE);
#line 117 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_tmp1_ = match;
#line 117 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, SYNAPSE_TYPE_URI_MATCH)) {
#line 1079 "file-op-plugin.c"
		SynapseMatch* _tmp2_ = NULL;
		SynapseQueryFlags _tmp3_ = 0;
		SynapseQueryFlags _tmp4_ = 0;
#line 117 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp2_ = match;
#line 117 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp3_ = synapse_uri_match_get_file_type (G_TYPE_CHECK_INSTANCE_CAST (_tmp2_, SYNAPSE_TYPE_URI_MATCH, SynapseUriMatch));
#line 117 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp4_ = _tmp3_;
#line 117 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp0_ = (_tmp4_ & SYNAPSE_QUERY_FLAGS_FILES) != 0;
#line 1091 "file-op-plugin.c"
	} else {
#line 117 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		_tmp0_ = FALSE;
#line 1095 "file-op-plugin.c"
	}
#line 117 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	result = _tmp0_;
#line 117 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	return result;
#line 1101 "file-op-plugin.c"
}


static void synapse_file_op_plugin_rename_to_class_init (SynapseFileOpPluginRenameToClass * klass) {
#line 68 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	synapse_file_op_plugin_rename_to_parent_class = g_type_class_peek_parent (klass);
#line 68 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	((SynapseActionClass *) klass)->do_execute = synapse_file_op_plugin_rename_to_real_do_execute;
#line 68 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	((SynapseMatchClass *) klass)->needs_target = synapse_file_op_plugin_rename_to_real_needs_target;
#line 68 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	((SynapseMatchClass *) klass)->target_flags = synapse_file_op_plugin_rename_to_real_target_flags;
#line 68 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	((SynapseActionClass *) klass)->valid_for_match = synapse_file_op_plugin_rename_to_real_valid_for_match;
#line 1116 "file-op-plugin.c"
}


static void synapse_file_op_plugin_rename_to_instance_init (SynapseFileOpPluginRenameTo * self) {
}


static GType synapse_file_op_plugin_rename_to_get_type (void) {
	static volatile gsize synapse_file_op_plugin_rename_to_type_id__volatile = 0;
	if (g_once_init_enter (&synapse_file_op_plugin_rename_to_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynapseFileOpPluginRenameToClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synapse_file_op_plugin_rename_to_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynapseFileOpPluginRenameTo), 0, (GInstanceInitFunc) synapse_file_op_plugin_rename_to_instance_init, NULL };
		GType synapse_file_op_plugin_rename_to_type_id;
		synapse_file_op_plugin_rename_to_type_id = g_type_register_static (SYNAPSE_TYPE_ACTION, "SynapseFileOpPluginRenameTo", &g_define_type_info, 0);
		g_once_init_leave (&synapse_file_op_plugin_rename_to_type_id__volatile, synapse_file_op_plugin_rename_to_type_id);
	}
	return synapse_file_op_plugin_rename_to_type_id__volatile;
}


static void synapse_file_op_plugin_class_init (SynapseFileOpPluginClass * klass) {
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	synapse_file_op_plugin_parent_class = g_type_class_peek_parent (klass);
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	g_type_class_add_private (klass, sizeof (SynapseFileOpPluginPrivate));
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_synapse_file_op_plugin_get_property;
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_synapse_file_op_plugin_set_property;
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	G_OBJECT_CLASS (klass)->constructor = synapse_file_op_plugin_constructor;
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	G_OBJECT_CLASS (klass)->finalize = synapse_file_op_plugin_finalize;
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNAPSE_FILE_OP_PLUGIN_ENABLED, g_param_spec_boolean ("enabled", "enabled", "enabled", TRUE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 134 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	synapse_file_op_plugin_register_plugin ();
#line 1153 "file-op-plugin.c"
}


static void synapse_file_op_plugin_synapse_activatable_interface_init (SynapseActivatableIface * iface) {
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	synapse_file_op_plugin_synapse_activatable_parent_iface = g_type_interface_peek_parent (iface);
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	iface->activate = (void (*)(SynapseActivatable*)) synapse_file_op_plugin_real_activate;
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	iface->deactivate = (void (*)(SynapseActivatable*)) synapse_file_op_plugin_real_deactivate;
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	iface->get_enabled = synapse_file_op_plugin_real_get_enabled;
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	iface->set_enabled = synapse_file_op_plugin_real_set_enabled;
#line 1168 "file-op-plugin.c"
}


static void synapse_file_op_plugin_synapse_action_provider_interface_init (SynapseActionProviderIface * iface) {
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	synapse_file_op_plugin_synapse_action_provider_parent_iface = g_type_interface_peek_parent (iface);
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	iface->find_for_match = (SynapseResultSet* (*)(SynapseActionProvider*, SynapseQuery*, SynapseMatch*)) synapse_file_op_plugin_real_find_for_match;
#line 1177 "file-op-plugin.c"
}


static void synapse_file_op_plugin_instance_init (SynapseFileOpPlugin * self) {
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self->priv = SYNAPSE_FILE_OP_PLUGIN_GET_PRIVATE (self);
#line 26 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self->priv->_enabled = TRUE;
#line 1186 "file-op-plugin.c"
}


static void synapse_file_op_plugin_finalize (GObject* obj) {
	SynapseFileOpPlugin * self;
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYNAPSE_TYPE_FILE_OP_PLUGIN, SynapseFileOpPlugin);
#line 137 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	_g_object_unref0 (self->priv->actions);
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	G_OBJECT_CLASS (synapse_file_op_plugin_parent_class)->finalize (obj);
#line 1198 "file-op-plugin.c"
}


GType synapse_file_op_plugin_get_type (void) {
	static volatile gsize synapse_file_op_plugin_type_id__volatile = 0;
	if (g_once_init_enter (&synapse_file_op_plugin_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynapseFileOpPluginClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synapse_file_op_plugin_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynapseFileOpPlugin), 0, (GInstanceInitFunc) synapse_file_op_plugin_instance_init, NULL };
		static const GInterfaceInfo synapse_activatable_info = { (GInterfaceInitFunc) synapse_file_op_plugin_synapse_activatable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo synapse_action_provider_info = { (GInterfaceInitFunc) synapse_file_op_plugin_synapse_action_provider_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType synapse_file_op_plugin_type_id;
		synapse_file_op_plugin_type_id = g_type_register_static (G_TYPE_OBJECT, "SynapseFileOpPlugin", &g_define_type_info, 0);
		g_type_add_interface_static (synapse_file_op_plugin_type_id, SYNAPSE_TYPE_ACTIVATABLE, &synapse_activatable_info);
		g_type_add_interface_static (synapse_file_op_plugin_type_id, SYNAPSE_TYPE_ACTION_PROVIDER, &synapse_action_provider_info);
		g_once_init_leave (&synapse_file_op_plugin_type_id__volatile, synapse_file_op_plugin_type_id);
	}
	return synapse_file_op_plugin_type_id__volatile;
}


static void _vala_synapse_file_op_plugin_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SynapseFileOpPlugin * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYNAPSE_TYPE_FILE_OP_PLUGIN, SynapseFileOpPlugin);
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	switch (property_id) {
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		case SYNAPSE_FILE_OP_PLUGIN_ENABLED:
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		g_value_set_boolean (value, synapse_activatable_get_enabled ((SynapseActivatable*) self));
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		break;
#line 1229 "file-op-plugin.c"
		default:
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		break;
#line 1235 "file-op-plugin.c"
	}
}


static void _vala_synapse_file_op_plugin_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SynapseFileOpPlugin * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYNAPSE_TYPE_FILE_OP_PLUGIN, SynapseFileOpPlugin);
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
	switch (property_id) {
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		case SYNAPSE_FILE_OP_PLUGIN_ENABLED:
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		synapse_activatable_set_enabled ((SynapseActivatable*) self, g_value_get_boolean (value));
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		break;
#line 1251 "file-op-plugin.c"
		default:
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "/home/heider/github/synapse-project/src/plugins/file-op-plugin.vala"
		break;
#line 1257 "file-op-plugin.c"
	}
}



