/* spotify-plugin.c generated by valac 0.30.1, the Vala compiler
 * generated from spotify-plugin.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <synapse-core.h>
#include <glib/gi18n-lib.h>
#include <gio/gio.h>
#include <string.h>
#include <stdlib.h>


#define SYNAPSE_TYPE_SPOTIFY_PLUGIN (synapse_spotify_plugin_get_type ())
#define SYNAPSE_SPOTIFY_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_TYPE_SPOTIFY_PLUGIN, SynapseSpotifyPlugin))
#define SYNAPSE_SPOTIFY_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_TYPE_SPOTIFY_PLUGIN, SynapseSpotifyPluginClass))
#define SYNAPSE_IS_SPOTIFY_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_TYPE_SPOTIFY_PLUGIN))
#define SYNAPSE_IS_SPOTIFY_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_TYPE_SPOTIFY_PLUGIN))
#define SYNAPSE_SPOTIFY_PLUGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_TYPE_SPOTIFY_PLUGIN, SynapseSpotifyPluginClass))

typedef struct _SynapseSpotifyPlugin SynapseSpotifyPlugin;
typedef struct _SynapseSpotifyPluginClass SynapseSpotifyPluginClass;
typedef struct _SynapseSpotifyPluginPrivate SynapseSpotifyPluginPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define SYNAPSE_SPOTIFY_PLUGIN_TYPE_SPOTIFY_MATCH (synapse_spotify_plugin_spotify_match_get_type ())
#define SYNAPSE_SPOTIFY_PLUGIN_SPOTIFY_MATCH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_SPOTIFY_PLUGIN_TYPE_SPOTIFY_MATCH, SynapseSpotifyPluginSpotifyMatch))
#define SYNAPSE_SPOTIFY_PLUGIN_SPOTIFY_MATCH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_SPOTIFY_PLUGIN_TYPE_SPOTIFY_MATCH, SynapseSpotifyPluginSpotifyMatchClass))
#define SYNAPSE_SPOTIFY_PLUGIN_IS_SPOTIFY_MATCH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_SPOTIFY_PLUGIN_TYPE_SPOTIFY_MATCH))
#define SYNAPSE_SPOTIFY_PLUGIN_IS_SPOTIFY_MATCH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_SPOTIFY_PLUGIN_TYPE_SPOTIFY_MATCH))
#define SYNAPSE_SPOTIFY_PLUGIN_SPOTIFY_MATCH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_SPOTIFY_PLUGIN_TYPE_SPOTIFY_MATCH, SynapseSpotifyPluginSpotifyMatchClass))

typedef struct _SynapseSpotifyPluginSpotifyMatch SynapseSpotifyPluginSpotifyMatch;
typedef struct _SynapseSpotifyPluginSpotifyMatchClass SynapseSpotifyPluginSpotifyMatchClass;
typedef struct _SynapseSpotifyPluginSearchData SynapseSpotifyPluginSearchData;
typedef struct _SynapseSpotifyPluginSpotifyMatchPrivate SynapseSpotifyPluginSpotifyMatchPrivate;

struct _SynapseSpotifyPlugin {
	GObject parent_instance;
	SynapseSpotifyPluginPrivate * priv;
};

struct _SynapseSpotifyPluginClass {
	GObjectClass parent_class;
};

struct _SynapseSpotifyPluginPrivate {
	gboolean _enabled;
};

struct _SynapseSpotifyPluginSearchData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	SynapseSpotifyPlugin* self;
	SynapseQuery query;
	SynapseResultSet* result;
	SynapseQuery _tmp0_;
	const gchar* _tmp1_;
	gboolean _tmp2_;
	SynapseResultSet* results;
	SynapseResultSet* _tmp3_;
	SynapseResultSet* _tmp4_;
	SynapseSpotifyPluginSpotifyMatch* _tmp5_;
	SynapseSpotifyPluginSpotifyMatch* _tmp6_;
	GError * _inner_error_;
};

struct _SynapseSpotifyPluginSpotifyMatch {
	SynapseUnknownMatch parent_instance;
	SynapseSpotifyPluginSpotifyMatchPrivate * priv;
};

struct _SynapseSpotifyPluginSpotifyMatchClass {
	SynapseUnknownMatchClass parent_class;
};


static gpointer synapse_spotify_plugin_parent_class = NULL;
static gpointer synapse_spotify_plugin_spotify_match_parent_class = NULL;
static SynapseActivatableIface* synapse_spotify_plugin_synapse_activatable_parent_iface = NULL;
static SynapseItemProviderIface* synapse_spotify_plugin_synapse_item_provider_parent_iface = NULL;

GType synapse_spotify_plugin_get_type (void) G_GNUC_CONST;
#define SYNAPSE_SPOTIFY_PLUGIN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYNAPSE_TYPE_SPOTIFY_PLUGIN, SynapseSpotifyPluginPrivate))
enum  {
	SYNAPSE_SPOTIFY_PLUGIN_DUMMY_PROPERTY,
	SYNAPSE_SPOTIFY_PLUGIN_ENABLED
};
static void synapse_spotify_plugin_real_activate (SynapseActivatable* base);
static void synapse_spotify_plugin_real_deactivate (SynapseActivatable* base);
static void synapse_spotify_plugin_register_plugin (void);
static void _synapse_spotify_plugin_register_plugin_synapse_plugin_register_func (void);
static gboolean synapse_spotify_plugin_real_handles_query (SynapseItemProvider* base, SynapseQuery* query);
static void synapse_spotify_plugin_real_search_data_free (gpointer _data);
static void synapse_spotify_plugin_real_search (SynapseItemProvider* base, SynapseQuery* query, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean synapse_spotify_plugin_real_search_co (SynapseSpotifyPluginSearchData* _data_);
static SynapseSpotifyPluginSpotifyMatch* synapse_spotify_plugin_spotify_match_new (void);
static SynapseSpotifyPluginSpotifyMatch* synapse_spotify_plugin_spotify_match_construct (GType object_type);
static GType synapse_spotify_plugin_spotify_match_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
SynapseSpotifyPlugin* synapse_spotify_plugin_new (void);
SynapseSpotifyPlugin* synapse_spotify_plugin_construct (GType object_type);
enum  {
	SYNAPSE_SPOTIFY_PLUGIN_SPOTIFY_MATCH_DUMMY_PROPERTY
};
static void synapse_spotify_plugin_finalize (GObject* obj);
static void _vala_synapse_spotify_plugin_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_synapse_spotify_plugin_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static void synapse_spotify_plugin_real_activate (SynapseActivatable* base) {
	SynapseSpotifyPlugin * self;
#line 22 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	self = (SynapseSpotifyPlugin*) base;
#line 118 "spotify-plugin.c"
}


static void synapse_spotify_plugin_real_deactivate (SynapseActivatable* base) {
	SynapseSpotifyPlugin * self;
#line 28 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	self = (SynapseSpotifyPlugin*) base;
#line 126 "spotify-plugin.c"
}


static void _synapse_spotify_plugin_register_plugin_synapse_plugin_register_func (void) {
#line 35 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	synapse_spotify_plugin_register_plugin ();
#line 133 "spotify-plugin.c"
}


static void synapse_spotify_plugin_register_plugin (void) {
	SynapsePluginRegistry* _tmp0_ = NULL;
	SynapsePluginRegistry* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
#line 35 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_tmp0_ = synapse_plugin_registry_get_default ();
#line 35 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_tmp1_ = _tmp0_;
#line 35 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_tmp2_ = _ ("SpotifyPlugin");
#line 35 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_tmp3_ = _ ("An example plugin.");
#line 35 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_tmp4_ = g_find_program_in_path ("ls");
#line 35 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_tmp5_ = _tmp4_;
#line 35 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_tmp6_ = _ ("ls is not installed");
#line 35 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	synapse_plugin_registry_register_plugin (_tmp1_, SYNAPSE_TYPE_SPOTIFY_PLUGIN, _tmp2_, _tmp3_, "system-run", _synapse_spotify_plugin_register_plugin_synapse_plugin_register_func, _tmp5_ != NULL, _tmp6_);
#line 35 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_g_free0 (_tmp5_);
#line 35 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_g_object_unref0 (_tmp1_);
#line 165 "spotify-plugin.c"
}


static gboolean synapse_spotify_plugin_real_handles_query (SynapseItemProvider* base, SynapseQuery* query) {
	SynapseSpotifyPlugin * self;
	gboolean result = FALSE;
	SynapseQuery _tmp0_ = {0};
	SynapseQueryFlags _tmp1_ = 0;
#line 55 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	self = (SynapseSpotifyPlugin*) base;
#line 55 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	g_return_val_if_fail (query != NULL, FALSE);
#line 58 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_tmp0_ = *query;
#line 58 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_tmp1_ = _tmp0_.query_type;
#line 58 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	result = (_tmp1_ & SYNAPSE_QUERY_FLAGS_ACTIONS) == SYNAPSE_QUERY_FLAGS_ACTIONS;
#line 58 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	return result;
#line 186 "spotify-plugin.c"
}


static void synapse_spotify_plugin_real_search_data_free (gpointer _data) {
	SynapseSpotifyPluginSearchData* _data_;
	_data_ = _data;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	synapse_query_destroy (&_data_->query);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_g_object_unref0 (_data_->result);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_g_object_unref0 (_data_->self);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	g_slice_free (SynapseSpotifyPluginSearchData, _data_);
#line 201 "spotify-plugin.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	return self ? g_object_ref (self) : NULL;
#line 208 "spotify-plugin.c"
}


static void synapse_spotify_plugin_real_search (SynapseItemProvider* base, SynapseQuery* query, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	SynapseSpotifyPlugin * self;
	SynapseSpotifyPluginSearchData* _data_;
	SynapseSpotifyPlugin* _tmp0_ = NULL;
	SynapseQuery _tmp1_ = {0};
	SynapseQuery _tmp2_ = {0};
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	self = (SynapseSpotifyPlugin*) base;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_data_ = g_slice_new0 (SynapseSpotifyPluginSearchData);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, synapse_spotify_plugin_real_search);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, synapse_spotify_plugin_real_search_data_free);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_data_->self = _tmp0_;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_tmp1_ = *query;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	synapse_query_copy (&_tmp1_, &_tmp2_);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	synapse_query_destroy (&_data_->query);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_data_->query = _tmp2_;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	synapse_spotify_plugin_real_search_co (_data_);
#line 240 "spotify-plugin.c"
}


static SynapseResultSet* synapse_spotify_plugin_real_search_finish (SynapseItemProvider* base, GAsyncResult* _res_, GError** error) {
	SynapseResultSet* result;
	SynapseSpotifyPluginSearchData* _data_;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	if (g_simple_async_result_propagate_error (G_SIMPLE_ASYNC_RESULT (_res_), error)) {
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		return NULL;
#line 251 "spotify-plugin.c"
	}
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	result = _data_->result;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_data_->result = NULL;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	return result;
#line 261 "spotify-plugin.c"
}


static gboolean synapse_spotify_plugin_real_search_co (SynapseSpotifyPluginSearchData* _data_) {
#line 61 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	switch (_data_->_state_) {
#line 61 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		case 0:
#line 270 "spotify-plugin.c"
		goto _state_0;
		default:
#line 61 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		g_assert_not_reached ();
#line 275 "spotify-plugin.c"
	}
	_state_0:
#line 63 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	memset (&_data_->_tmp0_, 0, sizeof (SynapseQuery));
#line 63 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_data_->_tmp0_ = _data_->query;
#line 63 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_data_->_tmp1_ = NULL;
#line 63 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_data_->_tmp1_ = _data_->_tmp0_.query_string;
#line 63 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_data_->_tmp2_ = FALSE;
#line 63 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_data_->_tmp2_ = g_str_has_prefix (_data_->_tmp1_, "spot");
#line 63 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	if (_data_->_tmp2_) {
#line 66 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		_data_->_tmp3_ = NULL;
#line 66 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		_data_->_tmp3_ = synapse_result_set_new ();
#line 66 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		_data_->results = _data_->_tmp3_;
#line 67 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		_data_->_tmp4_ = NULL;
#line 67 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		_data_->_tmp4_ = _data_->results;
#line 67 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		_data_->_tmp5_ = NULL;
#line 67 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		_data_->_tmp5_ = synapse_spotify_plugin_spotify_match_new ();
#line 67 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		_data_->_tmp6_ = NULL;
#line 67 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		_data_->_tmp6_ = _data_->_tmp5_;
#line 67 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		synapse_result_set_add (_data_->_tmp4_, (SynapseMatch*) _data_->_tmp6_, (gint) SYNAPSE_MATCH_SCORE_AVERAGE);
#line 67 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		_g_object_unref0 (_data_->_tmp6_);
#line 70 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		synapse_query_check_cancellable (&_data_->query, &_data_->_inner_error_);
#line 70 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
#line 70 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
			if (_data_->_inner_error_->domain == SYNAPSE_SEARCH_ERROR) {
#line 70 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
				g_simple_async_result_set_from_error (_data_->_async_result, _data_->_inner_error_);
#line 70 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
				g_error_free (_data_->_inner_error_);
#line 70 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
				_g_object_unref0 (_data_->results);
#line 70 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
				if (_data_->_state_ == 0) {
#line 70 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
					g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 330 "spotify-plugin.c"
				} else {
#line 70 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
					g_simple_async_result_complete (_data_->_async_result);
#line 334 "spotify-plugin.c"
				}
#line 70 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
				g_object_unref (_data_->_async_result);
#line 70 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
				return FALSE;
#line 340 "spotify-plugin.c"
			} else {
#line 70 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
				_g_object_unref0 (_data_->results);
#line 70 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
#line 70 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
				g_clear_error (&_data_->_inner_error_);
#line 70 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
				return FALSE;
#line 350 "spotify-plugin.c"
			}
		}
#line 71 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		_data_->result = _data_->results;
#line 71 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		if (_data_->_state_ == 0) {
#line 71 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
			g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 359 "spotify-plugin.c"
		} else {
#line 71 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
			g_simple_async_result_complete (_data_->_async_result);
#line 363 "spotify-plugin.c"
		}
#line 71 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		g_object_unref (_data_->_async_result);
#line 71 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		return FALSE;
#line 369 "spotify-plugin.c"
	}
#line 75 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	synapse_query_check_cancellable (&_data_->query, &_data_->_inner_error_);
#line 75 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
#line 75 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		if (_data_->_inner_error_->domain == SYNAPSE_SEARCH_ERROR) {
#line 75 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
			g_simple_async_result_set_from_error (_data_->_async_result, _data_->_inner_error_);
#line 75 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
			g_error_free (_data_->_inner_error_);
#line 75 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
			if (_data_->_state_ == 0) {
#line 75 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
				g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 385 "spotify-plugin.c"
			} else {
#line 75 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
				g_simple_async_result_complete (_data_->_async_result);
#line 389 "spotify-plugin.c"
			}
#line 75 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
			g_object_unref (_data_->_async_result);
#line 75 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
			return FALSE;
#line 395 "spotify-plugin.c"
		} else {
#line 75 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
#line 75 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
			g_clear_error (&_data_->_inner_error_);
#line 75 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
			return FALSE;
#line 403 "spotify-plugin.c"
		}
	}
#line 76 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_data_->result = NULL;
#line 76 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	if (_data_->_state_ == 0) {
#line 76 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 412 "spotify-plugin.c"
	} else {
#line 76 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 416 "spotify-plugin.c"
	}
#line 76 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	g_object_unref (_data_->_async_result);
#line 76 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	return FALSE;
#line 61 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	if (_data_->_state_ == 0) {
#line 61 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 426 "spotify-plugin.c"
	} else {
#line 61 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 430 "spotify-plugin.c"
	}
#line 61 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	g_object_unref (_data_->_async_result);
#line 61 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	return FALSE;
#line 436 "spotify-plugin.c"
}


SynapseSpotifyPlugin* synapse_spotify_plugin_construct (GType object_type) {
	SynapseSpotifyPlugin * self = NULL;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	self = (SynapseSpotifyPlugin*) g_object_new (object_type, NULL);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	return self;
#line 446 "spotify-plugin.c"
}


SynapseSpotifyPlugin* synapse_spotify_plugin_new (void) {
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	return synapse_spotify_plugin_construct (SYNAPSE_TYPE_SPOTIFY_PLUGIN);
#line 453 "spotify-plugin.c"
}


static gboolean synapse_spotify_plugin_real_get_enabled (SynapseActivatable* base) {
	gboolean result;
	SynapseSpotifyPlugin* self;
	gboolean _tmp0_ = FALSE;
#line 18 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	self = (SynapseSpotifyPlugin*) base;
#line 18 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_tmp0_ = self->priv->_enabled;
#line 18 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	result = _tmp0_;
#line 18 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	return result;
#line 469 "spotify-plugin.c"
}


static void synapse_spotify_plugin_real_set_enabled (SynapseActivatable* base, gboolean value) {
	SynapseSpotifyPlugin* self;
	gboolean _tmp0_ = FALSE;
#line 18 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	self = (SynapseSpotifyPlugin*) base;
#line 18 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	_tmp0_ = value;
#line 18 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	self->priv->_enabled = _tmp0_;
#line 18 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	g_object_notify ((GObject *) self, "enabled");
#line 484 "spotify-plugin.c"
}


static SynapseSpotifyPluginSpotifyMatch* synapse_spotify_plugin_spotify_match_construct (GType object_type) {
	SynapseSpotifyPluginSpotifyMatch * self = NULL;
#line 84 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	self = (SynapseSpotifyPluginSpotifyMatch*) g_object_new (object_type, "title", "SpotifyPlugin", "description", "Result from SpotifyPlugin, hej simon", "has-thumbnail", FALSE, "icon-name", "system-run", NULL);
#line 82 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	return self;
#line 494 "spotify-plugin.c"
}


static SynapseSpotifyPluginSpotifyMatch* synapse_spotify_plugin_spotify_match_new (void) {
#line 82 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	return synapse_spotify_plugin_spotify_match_construct (SYNAPSE_SPOTIFY_PLUGIN_TYPE_SPOTIFY_MATCH);
#line 501 "spotify-plugin.c"
}


static void synapse_spotify_plugin_spotify_match_class_init (SynapseSpotifyPluginSpotifyMatchClass * klass) {
#line 80 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	synapse_spotify_plugin_spotify_match_parent_class = g_type_class_peek_parent (klass);
#line 508 "spotify-plugin.c"
}


static void synapse_spotify_plugin_spotify_match_instance_init (SynapseSpotifyPluginSpotifyMatch * self) {
}


static GType synapse_spotify_plugin_spotify_match_get_type (void) {
	static volatile gsize synapse_spotify_plugin_spotify_match_type_id__volatile = 0;
	if (g_once_init_enter (&synapse_spotify_plugin_spotify_match_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynapseSpotifyPluginSpotifyMatchClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synapse_spotify_plugin_spotify_match_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynapseSpotifyPluginSpotifyMatch), 0, (GInstanceInitFunc) synapse_spotify_plugin_spotify_match_instance_init, NULL };
		GType synapse_spotify_plugin_spotify_match_type_id;
		synapse_spotify_plugin_spotify_match_type_id = g_type_register_static (SYNAPSE_TYPE_UNKNOWN_MATCH, "SynapseSpotifyPluginSpotifyMatch", &g_define_type_info, 0);
		g_once_init_leave (&synapse_spotify_plugin_spotify_match_type_id__volatile, synapse_spotify_plugin_spotify_match_type_id);
	}
	return synapse_spotify_plugin_spotify_match_type_id__volatile;
}


static void synapse_spotify_plugin_class_init (SynapseSpotifyPluginClass * klass) {
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	synapse_spotify_plugin_parent_class = g_type_class_peek_parent (klass);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	g_type_class_add_private (klass, sizeof (SynapseSpotifyPluginPrivate));
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_synapse_spotify_plugin_get_property;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_synapse_spotify_plugin_set_property;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	G_OBJECT_CLASS (klass)->finalize = synapse_spotify_plugin_finalize;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNAPSE_SPOTIFY_PLUGIN_ENABLED, g_param_spec_boolean ("enabled", "enabled", "enabled", TRUE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 49 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	synapse_spotify_plugin_register_plugin ();
#line 543 "spotify-plugin.c"
}


static void synapse_spotify_plugin_synapse_activatable_interface_init (SynapseActivatableIface * iface) {
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	synapse_spotify_plugin_synapse_activatable_parent_iface = g_type_interface_peek_parent (iface);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	iface->activate = (void (*)(SynapseActivatable*)) synapse_spotify_plugin_real_activate;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	iface->deactivate = (void (*)(SynapseActivatable*)) synapse_spotify_plugin_real_deactivate;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	iface->get_enabled = synapse_spotify_plugin_real_get_enabled;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	iface->set_enabled = synapse_spotify_plugin_real_set_enabled;
#line 558 "spotify-plugin.c"
}


static void synapse_spotify_plugin_synapse_item_provider_interface_init (SynapseItemProviderIface * iface) {
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	synapse_spotify_plugin_synapse_item_provider_parent_iface = g_type_interface_peek_parent (iface);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	iface->handles_query = (gboolean (*)(SynapseItemProvider*, SynapseQuery*)) synapse_spotify_plugin_real_handles_query;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	iface->search = (SynapseResultSet* (*)(SynapseItemProvider*, SynapseQuery*, GError**)) synapse_spotify_plugin_real_search;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	iface->search_finish = synapse_spotify_plugin_real_search_finish;
#line 571 "spotify-plugin.c"
}


static void synapse_spotify_plugin_instance_init (SynapseSpotifyPlugin * self) {
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	self->priv = SYNAPSE_SPOTIFY_PLUGIN_GET_PRIVATE (self);
#line 18 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	self->priv->_enabled = TRUE;
#line 580 "spotify-plugin.c"
}


static void synapse_spotify_plugin_finalize (GObject* obj) {
	SynapseSpotifyPlugin * self;
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYNAPSE_TYPE_SPOTIFY_PLUGIN, SynapseSpotifyPlugin);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	G_OBJECT_CLASS (synapse_spotify_plugin_parent_class)->finalize (obj);
#line 590 "spotify-plugin.c"
}


GType synapse_spotify_plugin_get_type (void) {
	static volatile gsize synapse_spotify_plugin_type_id__volatile = 0;
	if (g_once_init_enter (&synapse_spotify_plugin_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynapseSpotifyPluginClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synapse_spotify_plugin_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynapseSpotifyPlugin), 0, (GInstanceInitFunc) synapse_spotify_plugin_instance_init, NULL };
		static const GInterfaceInfo synapse_activatable_info = { (GInterfaceInitFunc) synapse_spotify_plugin_synapse_activatable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo synapse_item_provider_info = { (GInterfaceInitFunc) synapse_spotify_plugin_synapse_item_provider_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType synapse_spotify_plugin_type_id;
		synapse_spotify_plugin_type_id = g_type_register_static (G_TYPE_OBJECT, "SynapseSpotifyPlugin", &g_define_type_info, 0);
		g_type_add_interface_static (synapse_spotify_plugin_type_id, SYNAPSE_TYPE_ACTIVATABLE, &synapse_activatable_info);
		g_type_add_interface_static (synapse_spotify_plugin_type_id, SYNAPSE_TYPE_ITEM_PROVIDER, &synapse_item_provider_info);
		g_once_init_leave (&synapse_spotify_plugin_type_id__volatile, synapse_spotify_plugin_type_id);
	}
	return synapse_spotify_plugin_type_id__volatile;
}


static void _vala_synapse_spotify_plugin_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SynapseSpotifyPlugin * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYNAPSE_TYPE_SPOTIFY_PLUGIN, SynapseSpotifyPlugin);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	switch (property_id) {
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		case SYNAPSE_SPOTIFY_PLUGIN_ENABLED:
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		g_value_set_boolean (value, synapse_activatable_get_enabled ((SynapseActivatable*) self));
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		break;
#line 621 "spotify-plugin.c"
		default:
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		break;
#line 627 "spotify-plugin.c"
	}
}


static void _vala_synapse_spotify_plugin_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SynapseSpotifyPlugin * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYNAPSE_TYPE_SPOTIFY_PLUGIN, SynapseSpotifyPlugin);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
	switch (property_id) {
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		case SYNAPSE_SPOTIFY_PLUGIN_ENABLED:
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		synapse_activatable_set_enabled ((SynapseActivatable*) self, g_value_get_boolean (value));
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		break;
#line 643 "spotify-plugin.c"
		default:
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 15 "/home/heider/github/synapse/src/plugins/spotify-plugin.vala"
		break;
#line 649 "spotify-plugin.c"
	}
}



