/* ssh-plugin.c generated by valac 0.30.1, the Vala compiler
 * generated from ssh-plugin.vala, do not modify */

/*
 * Copyright (C) 2011 Antono Vasiljev <self@antono.info>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA.
 *
 * Authored by Antono Vasiljev <self@antono.info>
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <synapse-core.h>
#include <gio/gio.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>


#define SYNAPSE_TYPE_SSH_PLUGIN (synapse_ssh_plugin_get_type ())
#define SYNAPSE_SSH_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_TYPE_SSH_PLUGIN, SynapseSshPlugin))
#define SYNAPSE_SSH_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_TYPE_SSH_PLUGIN, SynapseSshPluginClass))
#define SYNAPSE_IS_SSH_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_TYPE_SSH_PLUGIN))
#define SYNAPSE_IS_SSH_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_TYPE_SSH_PLUGIN))
#define SYNAPSE_SSH_PLUGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_TYPE_SSH_PLUGIN, SynapseSshPluginClass))

typedef struct _SynapseSshPlugin SynapseSshPlugin;
typedef struct _SynapseSshPluginClass SynapseSshPluginClass;
typedef struct _SynapseSshPluginPrivate SynapseSshPluginPrivate;

#define SYNAPSE_SSH_PLUGIN_TYPE_SSH_HOST (synapse_ssh_plugin_ssh_host_get_type ())
#define SYNAPSE_SSH_PLUGIN_SSH_HOST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_SSH_PLUGIN_TYPE_SSH_HOST, SynapseSshPluginSshHost))
#define SYNAPSE_SSH_PLUGIN_SSH_HOST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_SSH_PLUGIN_TYPE_SSH_HOST, SynapseSshPluginSshHostClass))
#define SYNAPSE_SSH_PLUGIN_IS_SSH_HOST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_SSH_PLUGIN_TYPE_SSH_HOST))
#define SYNAPSE_SSH_PLUGIN_IS_SSH_HOST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_SSH_PLUGIN_TYPE_SSH_HOST))
#define SYNAPSE_SSH_PLUGIN_SSH_HOST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_SSH_PLUGIN_TYPE_SSH_HOST, SynapseSshPluginSshHostClass))

typedef struct _SynapseSshPluginSshHost SynapseSshPluginSshHost;
typedef struct _SynapseSshPluginSshHostClass SynapseSshPluginSshHostClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
typedef struct _SynapseSshPluginParseSshConfigData SynapseSshPluginParseSshConfigData;
typedef struct _SynapseSshPluginSearchData SynapseSshPluginSearchData;
typedef struct _SynapseSshPluginSshHostPrivate SynapseSshPluginSshHostPrivate;

struct _SynapseSshPlugin {
	GObject parent_instance;
	SynapseSshPluginPrivate * priv;
	GFile* config_file;
	GFileMonitor* monitor;
};

struct _SynapseSshPluginClass {
	GObjectClass parent_class;
};

struct _SynapseSshPluginPrivate {
	gboolean _enabled;
	GeeHashMap* hosts;
};

struct _SynapseSshPluginParseSshConfigData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	SynapseSshPlugin* self;
	GeeHashMap* _tmp0_;
	GFileInputStream* _tmp1_;
	GFile* _tmp2_;
	GFileInputStream* _tmp3_;
	GDataInputStream* dis;
	GDataInputStream* _tmp4_;
	GRegex* host_key_re;
	GRegex* _tmp5_;
	GRegex* comment_re;
	GRegex* _tmp6_;
	GRegex* ws_re;
	GRegex* _tmp7_;
	gchar* line;
	gchar* _tmp8_;
	GDataInputStream* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	const gchar* _tmp12_;
	gchar* _tmp13_;
	GRegex* _tmp14_;
	const gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	GRegex* _tmp18_;
	const gchar* _tmp19_;
	gboolean _tmp20_;
	gchar* _tmp21_;
	GRegex* _tmp22_;
	const gchar* _tmp23_;
	gchar* _tmp24_;
	gchar* _tmp25_;
	gchar* _tmp26_;
	GRegex* _tmp27_;
	const gchar* _tmp28_;
	gchar* _tmp29_;
	gchar* _tmp30_;
	gchar* _tmp31_;
	gchar* _tmp32_;
	const gchar* _tmp33_;
	gchar** _tmp34_;
	gchar** _tmp35_;
	gchar** host_collection;
	gint host_collection_length1;
	gint _host_collection_size_;
	gint host_it;
	gchar* _tmp36_;
	gchar* host;
	gchar* host_stripped;
	const gchar* _tmp37_;
	gchar* _tmp38_;
	gboolean _tmp39_;
	gboolean _tmp40_;
	const gchar* _tmp41_;
	const gchar* _tmp42_;
	gint _tmp43_;
	const gchar* _tmp44_;
	gint _tmp45_;
	const gchar* _tmp46_;
	GeeHashMap* _tmp47_;
	const gchar* _tmp48_;
	const gchar* _tmp49_;
	SynapseSshPluginSshHost* _tmp50_;
	SynapseSshPluginSshHost* _tmp51_;
	GError* e;
	GFile* _tmp52_;
	gchar* _tmp53_;
	gchar* _tmp54_;
	GError* _tmp55_;
	const gchar* _tmp56_;
	GError * _inner_error_;
};

struct _SynapseSshPluginSearchData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	SynapseSshPlugin* self;
	SynapseQuery q;
	SynapseResultSet* result;
	SynapseResultSet* results;
	SynapseResultSet* _tmp0_;
	GeeList* matchers;
	SynapseQuery _tmp1_;
	const gchar* _tmp2_;
	GeeList* _tmp3_;
	GeeIterator* _host_it;
	GeeHashMap* _tmp4_;
	GeeCollection* _tmp5_;
	GeeCollection* _tmp6_;
	GeeCollection* _tmp7_;
	GeeIterator* _tmp8_;
	GeeIterator* _tmp9_;
	GeeIterator* _tmp10_;
	gboolean _tmp11_;
	SynapseSshPluginSshHost* host;
	GeeIterator* _tmp12_;
	gpointer _tmp13_;
	GeeList* _matcher_list;
	GeeList* _tmp14_;
	GeeList* _tmp15_;
	gint _matcher_size;
	GeeList* _tmp16_;
	gint _tmp17_;
	gint _tmp18_;
	gint _matcher_index;
	gint _tmp19_;
	gint _tmp20_;
	gint _tmp21_;
	GeeMapEntry* matcher;
	GeeList* _tmp22_;
	gint _tmp23_;
	gpointer _tmp24_;
	GeeMapEntry* _tmp25_;
	gconstpointer _tmp26_;
	GRegex* _tmp27_;
	SynapseSshPluginSshHost* _tmp28_;
	const gchar* _tmp29_;
	const gchar* _tmp30_;
	gboolean _tmp31_;
	SynapseResultSet* _tmp32_;
	SynapseSshPluginSshHost* _tmp33_;
	GeeMapEntry* _tmp34_;
	gconstpointer _tmp35_;
	gint _tmp36_;
	GError * _inner_error_;
};

struct _SynapseSshPluginSshHost {
	SynapseActionMatch parent_instance;
	SynapseSshPluginSshHostPrivate * priv;
};

struct _SynapseSshPluginSshHostClass {
	SynapseActionMatchClass parent_class;
};

struct _SynapseSshPluginSshHostPrivate {
	gchar* _host_query;
};


static gpointer synapse_ssh_plugin_parent_class = NULL;
static gpointer synapse_ssh_plugin_ssh_host_parent_class = NULL;
static SynapseActivatableIface* synapse_ssh_plugin_synapse_activatable_parent_iface = NULL;
static SynapseItemProviderIface* synapse_ssh_plugin_synapse_item_provider_parent_iface = NULL;

GType synapse_ssh_plugin_get_type (void) G_GNUC_CONST;
static GType synapse_ssh_plugin_ssh_host_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
#define SYNAPSE_SSH_PLUGIN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYNAPSE_TYPE_SSH_PLUGIN, SynapseSshPluginPrivate))
enum  {
	SYNAPSE_SSH_PLUGIN_DUMMY_PROPERTY,
	SYNAPSE_SSH_PLUGIN_ENABLED
};
static void synapse_ssh_plugin_real_activate (SynapseActivatable* base);
static void synapse_ssh_plugin_parse_ssh_config (SynapseSshPlugin* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void synapse_ssh_plugin_parse_ssh_config_finish (SynapseSshPlugin* self, GAsyncResult* _res_);
void synapse_ssh_plugin_handle_ssh_config_update (SynapseSshPlugin* self, GFileMonitor* monitor, GFile* file, GFile* other_file, GFileMonitorEvent event_type);
static void _synapse_ssh_plugin_handle_ssh_config_update_g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self);
static void synapse_ssh_plugin_real_deactivate (SynapseActivatable* base);
static void synapse_ssh_plugin_register_plugin (void);
static void _synapse_ssh_plugin_register_plugin_synapse_plugin_register_func (void);
static void synapse_ssh_plugin_parse_ssh_config_data_free (gpointer _data);
static gboolean synapse_ssh_plugin_parse_ssh_config_co (SynapseSshPluginParseSshConfigData* _data_);
static void synapse_ssh_plugin_parse_ssh_config_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static SynapseSshPluginSshHost* synapse_ssh_plugin_ssh_host_new (const gchar* host_name);
static SynapseSshPluginSshHost* synapse_ssh_plugin_ssh_host_construct (GType object_type, const gchar* host_name);
static gboolean synapse_ssh_plugin_real_handles_query (SynapseItemProvider* base, SynapseQuery* query);
static void synapse_ssh_plugin_real_search_data_free (gpointer _data);
static void synapse_ssh_plugin_real_search (SynapseItemProvider* base, SynapseQuery* q, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean synapse_ssh_plugin_real_search_co (SynapseSshPluginSearchData* _data_);
static gboolean _synapse_ssh_plugin_real_search_co_gsource_func (gpointer self);
static const gchar* synapse_ssh_plugin_ssh_host_get_host_query (SynapseSshPluginSshHost* self);
SynapseSshPlugin* synapse_ssh_plugin_new (void);
SynapseSshPlugin* synapse_ssh_plugin_construct (GType object_type);
static GObject * synapse_ssh_plugin_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
#define SYNAPSE_SSH_PLUGIN_SSH_HOST_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYNAPSE_SSH_PLUGIN_TYPE_SSH_HOST, SynapseSshPluginSshHostPrivate))
enum  {
	SYNAPSE_SSH_PLUGIN_SSH_HOST_DUMMY_PROPERTY,
	SYNAPSE_SSH_PLUGIN_SSH_HOST_HOST_QUERY
};
static void synapse_ssh_plugin_ssh_host_real_do_action (SynapseActionMatch* base);
static void synapse_ssh_plugin_ssh_host_set_host_query (SynapseSshPluginSshHost* self, const gchar* value);
static void synapse_ssh_plugin_ssh_host_finalize (GObject* obj);
static void _vala_synapse_ssh_plugin_ssh_host_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_synapse_ssh_plugin_ssh_host_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void synapse_ssh_plugin_finalize (GObject* obj);
static void _vala_synapse_ssh_plugin_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_synapse_ssh_plugin_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static void _synapse_ssh_plugin_handle_ssh_config_update_g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self) {
#line 52 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_ssh_plugin_handle_ssh_config_update ((SynapseSshPlugin*) self, _sender, file, other_file, event_type);
#line 283 "ssh-plugin.c"
}


static void synapse_ssh_plugin_real_activate (SynapseActivatable* base) {
	SynapseSshPlugin * self;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	GFile* _tmp3_ = NULL;
	GError * _inner_error_ = NULL;
#line 44 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self = (SynapseSshPlugin*) base;
#line 46 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp0_ = g_get_home_dir ();
#line 46 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp1_ = g_strconcat (_tmp0_, "/.ssh/config", NULL);
#line 46 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp2_ = _tmp1_;
#line 46 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp3_ = g_file_new_for_path (_tmp2_);
#line 46 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_g_object_unref0 (self->config_file);
#line 46 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self->config_file = _tmp3_;
#line 46 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_g_free0 (_tmp2_);
#line 48 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_ssh_plugin_parse_ssh_config (self, NULL, NULL);
#line 312 "ssh-plugin.c"
	{
		GFileMonitor* _tmp4_ = NULL;
		GFile* _tmp5_ = NULL;
		GFileMonitor* _tmp6_ = NULL;
		GFileMonitor* _tmp7_ = NULL;
		GFileMonitor* _tmp8_ = NULL;
#line 51 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp5_ = self->config_file;
#line 51 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp6_ = g_file_monitor_file (_tmp5_, G_FILE_MONITOR_NONE, NULL, &_inner_error_);
#line 51 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp4_ = _tmp6_;
#line 51 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 51 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			if (_inner_error_->domain == G_IO_ERROR) {
#line 329 "ssh-plugin.c"
				goto __catch18_g_io_error;
			}
#line 51 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 51 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			g_clear_error (&_inner_error_);
#line 51 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			return;
#line 338 "ssh-plugin.c"
		}
#line 51 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp7_ = _tmp4_;
#line 51 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp4_ = NULL;
#line 51 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_g_object_unref0 (self->monitor);
#line 51 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		self->monitor = _tmp7_;
#line 52 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp8_ = self->monitor;
#line 52 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_signal_connect_object (_tmp8_, "changed", (GCallback) _synapse_ssh_plugin_handle_ssh_config_update_g_file_monitor_changed, self, 0);
#line 50 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_g_object_unref0 (_tmp4_);
#line 354 "ssh-plugin.c"
	}
	goto __finally18;
	__catch18_g_io_error:
	{
		GError* e = NULL;
#line 50 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		e = _inner_error_;
#line 50 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_inner_error_ = NULL;
#line 56 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_warning ("ssh-plugin.vala:56: Failed to start monitoring changes of ssh client c" \
"onfig file");
#line 50 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_g_error_free0 (e);
#line 368 "ssh-plugin.c"
	}
	__finally18:
#line 50 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 50 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 50 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_clear_error (&_inner_error_);
#line 50 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		return;
#line 379 "ssh-plugin.c"
	}
}


static void synapse_ssh_plugin_real_deactivate (SynapseActivatable* base) {
	SynapseSshPlugin * self;
#line 60 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self = (SynapseSshPlugin*) base;
#line 388 "ssh-plugin.c"
}


static void _synapse_ssh_plugin_register_plugin_synapse_plugin_register_func (void) {
#line 64 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_ssh_plugin_register_plugin ();
#line 395 "ssh-plugin.c"
}


static void synapse_ssh_plugin_register_plugin (void) {
	SynapsePluginRegistry* _tmp0_ = NULL;
	SynapsePluginRegistry* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
#line 64 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp0_ = synapse_plugin_registry_get_default ();
#line 64 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp1_ = _tmp0_;
#line 64 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp2_ = _ ("Connect to host with SSH");
#line 64 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp3_ = g_find_program_in_path ("ssh");
#line 64 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp4_ = _tmp3_;
#line 64 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp5_ = _ ("ssh is not installed");
#line 64 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_plugin_registry_register_plugin (_tmp1_, SYNAPSE_TYPE_SSH_PLUGIN, "SSH", _tmp2_, "terminal", _synapse_ssh_plugin_register_plugin_synapse_plugin_register_func, _tmp4_ != NULL, _tmp5_);
#line 64 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_g_free0 (_tmp4_);
#line 64 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_g_object_unref0 (_tmp1_);
#line 424 "ssh-plugin.c"
}


static void synapse_ssh_plugin_parse_ssh_config_data_free (gpointer _data) {
	SynapseSshPluginParseSshConfigData* _data_;
	_data_ = _data;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_g_object_unref0 (_data_->self);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_slice_free (SynapseSshPluginParseSshConfigData, _data_);
#line 435 "ssh-plugin.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	return self ? g_object_ref (self) : NULL;
#line 442 "ssh-plugin.c"
}


static void synapse_ssh_plugin_parse_ssh_config (SynapseSshPlugin* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	SynapseSshPluginParseSshConfigData* _data_;
	SynapseSshPlugin* _tmp0_ = NULL;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_ = g_slice_new0 (SynapseSshPluginParseSshConfigData);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, synapse_ssh_plugin_parse_ssh_config);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, synapse_ssh_plugin_parse_ssh_config_data_free);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->self = _tmp0_;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_ssh_plugin_parse_ssh_config_co (_data_);
#line 461 "ssh-plugin.c"
}


static void synapse_ssh_plugin_parse_ssh_config_finish (SynapseSshPlugin* self, GAsyncResult* _res_) {
	SynapseSshPluginParseSshConfigData* _data_;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
#line 469 "ssh-plugin.c"
}


static void synapse_ssh_plugin_parse_ssh_config_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	SynapseSshPluginParseSshConfigData* _data_;
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_ = _user_data_;
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->_source_object_ = source_object;
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->_res_ = _res_;
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_ssh_plugin_parse_ssh_config_co (_data_);
#line 483 "ssh-plugin.c"
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 1115 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1116 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	_tmp0_ = g_strdup (self);
#line 1116 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	_result_ = _tmp0_;
#line 1117 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	_tmp1_ = _result_;
#line 1117 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	g_strstrip (_tmp1_);
#line 1118 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	result = _result_;
#line 1118 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	return result;
#line 506 "ssh-plugin.c"
}


static gint string_index_of (const gchar* self, const gchar* needle, gint start_index) {
	gint result = 0;
	gchar* _result_ = NULL;
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
#line 900 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, 0);
#line 900 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, 0);
#line 901 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	_tmp0_ = start_index;
#line 901 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	_tmp1_ = needle;
#line 901 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	_tmp2_ = strstr (((gchar*) self) + _tmp0_, (gchar*) _tmp1_);
#line 901 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	_result_ = _tmp2_;
#line 903 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	_tmp3_ = _result_;
#line 903 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	if (_tmp3_ != NULL) {
#line 533 "ssh-plugin.c"
		gchar* _tmp4_ = NULL;
#line 904 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_tmp4_ = _result_;
#line 904 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		result = (gint) (_tmp4_ - ((gchar*) self));
#line 904 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		return result;
#line 541 "ssh-plugin.c"
	} else {
#line 906 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		result = -1;
#line 906 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		return result;
#line 547 "ssh-plugin.c"
	}
}


static gboolean synapse_ssh_plugin_parse_ssh_config_co (SynapseSshPluginParseSshConfigData* _data_) {
#line 76 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	switch (_data_->_state_) {
#line 76 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		case 0:
#line 557 "ssh-plugin.c"
		goto _state_0;
#line 76 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		case 1:
#line 561 "ssh-plugin.c"
		goto _state_1;
		default:
#line 76 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_assert_not_reached ();
#line 566 "ssh-plugin.c"
	}
	_state_0:
#line 78 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->_tmp0_ = NULL;
#line 78 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->_tmp0_ = _data_->self->priv->hosts;
#line 78 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	gee_abstract_map_clear ((GeeAbstractMap*) _data_->_tmp0_);
#line 575 "ssh-plugin.c"
	{
#line 82 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp2_ = NULL;
#line 82 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp2_ = _data_->self->config_file;
#line 82 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp3_ = NULL;
#line 82 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp3_ = g_file_read (_data_->_tmp2_, NULL, &_data_->_inner_error_);
#line 82 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp1_ = _data_->_tmp3_;
#line 82 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
#line 589 "ssh-plugin.c"
			goto __catch19_g_error;
		}
#line 82 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp4_ = NULL;
#line 82 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp4_ = g_data_input_stream_new ((GInputStream*) _data_->_tmp1_);
#line 82 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->dis = _data_->_tmp4_;
#line 85 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp5_ = NULL;
#line 85 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp5_ = g_regex_new ("(host\\s)", G_REGEX_OPTIMIZE | G_REGEX_CASELESS, 0, &_data_->_inner_error_);
#line 85 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->host_key_re = _data_->_tmp5_;
#line 85 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
#line 85 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_object_unref0 (_data_->dis);
#line 85 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_object_unref0 (_data_->_tmp1_);
#line 610 "ssh-plugin.c"
			goto __catch19_g_error;
		}
#line 86 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp6_ = NULL;
#line 86 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp6_ = g_regex_new ("#.*$", G_REGEX_OPTIMIZE, 0, &_data_->_inner_error_);
#line 86 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->comment_re = _data_->_tmp6_;
#line 86 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
#line 86 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_regex_unref0 (_data_->host_key_re);
#line 86 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_object_unref0 (_data_->dis);
#line 86 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_object_unref0 (_data_->_tmp1_);
#line 627 "ssh-plugin.c"
			goto __catch19_g_error;
		}
#line 87 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp7_ = NULL;
#line 87 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp7_ = g_regex_new ("[\\s]+", G_REGEX_OPTIMIZE, 0, &_data_->_inner_error_);
#line 87 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->ws_re = _data_->_tmp7_;
#line 87 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
#line 87 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_regex_unref0 (_data_->comment_re);
#line 87 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_regex_unref0 (_data_->host_key_re);
#line 87 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_object_unref0 (_data_->dis);
#line 87 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_object_unref0 (_data_->_tmp1_);
#line 646 "ssh-plugin.c"
			goto __catch19_g_error;
		}
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		while (TRUE) {
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp9_ = NULL;
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp9_ = _data_->dis;
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_state_ = 1;
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			g_data_input_stream_read_line_async (_data_->_tmp9_, G_PRIORITY_DEFAULT, NULL, synapse_ssh_plugin_parse_ssh_config_ready, _data_);
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			return FALSE;
#line 661 "ssh-plugin.c"
			_state_1:
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp10_ = NULL;
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp10_ = g_data_input_stream_read_line_finish (_data_->_tmp9_, _data_->_res_, NULL, &_data_->_inner_error_);
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp8_ = _data_->_tmp10_;
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_free0 (_data_->line);
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_regex_unref0 (_data_->ws_re);
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_regex_unref0 (_data_->comment_re);
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_regex_unref0 (_data_->host_key_re);
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_object_unref0 (_data_->dis);
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_object_unref0 (_data_->_tmp1_);
#line 683 "ssh-plugin.c"
				goto __catch19_g_error;
			}
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp11_ = NULL;
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp11_ = _data_->_tmp8_;
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp8_ = NULL;
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_free0 (_data_->line);
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->line = _data_->_tmp11_;
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp12_ = NULL;
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp12_ = _data_->line;
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			if (!(_data_->_tmp12_ != NULL)) {
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_free0 (_data_->_tmp8_);
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				break;
#line 706 "ssh-plugin.c"
			}
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp14_ = NULL;
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp14_ = _data_->comment_re;
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp15_ = NULL;
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp15_ = _data_->line;
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp16_ = NULL;
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp16_ = g_regex_replace (_data_->_tmp14_, _data_->_tmp15_, (gssize) -1, 0, "", 0, &_data_->_inner_error_);
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp13_ = _data_->_tmp16_;
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_free0 (_data_->_tmp8_);
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_free0 (_data_->line);
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_regex_unref0 (_data_->ws_re);
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_regex_unref0 (_data_->comment_re);
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_regex_unref0 (_data_->host_key_re);
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_object_unref0 (_data_->dis);
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_object_unref0 (_data_->_tmp1_);
#line 738 "ssh-plugin.c"
				goto __catch19_g_error;
			}
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp17_ = NULL;
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp17_ = _data_->_tmp13_;
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp13_ = NULL;
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_free0 (_data_->line);
#line 94 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->line = _data_->_tmp17_;
#line 95 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp18_ = NULL;
#line 95 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp18_ = _data_->host_key_re;
#line 95 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp19_ = NULL;
#line 95 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp19_ = _data_->line;
#line 95 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp20_ = FALSE;
#line 95 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp20_ = g_regex_match (_data_->_tmp18_, _data_->_tmp19_, 0, NULL);
#line 95 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			if (_data_->_tmp20_) {
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp22_ = NULL;
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp22_ = _data_->host_key_re;
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp23_ = NULL;
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp23_ = _data_->line;
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp24_ = NULL;
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp24_ = g_regex_replace (_data_->_tmp22_, _data_->_tmp23_, (gssize) -1, 0, "", 0, &_data_->_inner_error_);
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp21_ = _data_->_tmp24_;
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_free0 (_data_->_tmp13_);
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_free0 (_data_->_tmp8_);
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_free0 (_data_->line);
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_regex_unref0 (_data_->ws_re);
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_regex_unref0 (_data_->comment_re);
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_regex_unref0 (_data_->host_key_re);
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_object_unref0 (_data_->dis);
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_object_unref0 (_data_->_tmp1_);
#line 797 "ssh-plugin.c"
					goto __catch19_g_error;
				}
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp25_ = NULL;
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp25_ = _data_->_tmp21_;
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp21_ = NULL;
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_free0 (_data_->line);
#line 98 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->line = _data_->_tmp25_;
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp27_ = NULL;
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp27_ = _data_->ws_re;
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp28_ = NULL;
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp28_ = _data_->line;
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp29_ = NULL;
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp29_ = g_regex_replace (_data_->_tmp27_, _data_->_tmp28_, (gssize) -1, 0, " ", 0, &_data_->_inner_error_);
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp26_ = _data_->_tmp29_;
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_free0 (_data_->_tmp21_);
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_free0 (_data_->_tmp13_);
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_free0 (_data_->_tmp8_);
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_free0 (_data_->line);
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_regex_unref0 (_data_->ws_re);
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_regex_unref0 (_data_->comment_re);
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_regex_unref0 (_data_->host_key_re);
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_object_unref0 (_data_->dis);
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_object_unref0 (_data_->_tmp1_);
#line 844 "ssh-plugin.c"
					goto __catch19_g_error;
				}
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp30_ = NULL;
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp30_ = _data_->_tmp26_;
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp26_ = NULL;
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp31_ = NULL;
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp31_ = _data_->_tmp30_;
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp32_ = NULL;
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp32_ = string_strip (_data_->_tmp31_);
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_free0 (_data_->line);
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->line = _data_->_tmp32_;
#line 100 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_free0 (_data_->_tmp31_);
#line 102 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp33_ = NULL;
#line 102 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp33_ = _data_->line;
#line 102 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp34_ = NULL;
#line 102 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp35_ = NULL;
#line 102 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp35_ = _data_->_tmp34_ = g_strsplit (_data_->_tmp33_, " ", 0);
#line 877 "ssh-plugin.c"
				{
#line 102 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->host_collection_length1 = 0;
#line 102 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_host_collection_size_ = 0;
#line 102 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->host_collection = _data_->_tmp35_;
#line 102 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->host_collection_length1 = _vala_array_length (_data_->_tmp34_);
#line 102 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					for (_data_->host_it = 0; _data_->host_it < _vala_array_length (_data_->_tmp34_); _data_->host_it = _data_->host_it + 1) {
#line 102 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						_data_->_tmp36_ = NULL;
#line 102 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						_data_->_tmp36_ = g_strdup (_data_->host_collection[_data_->host_it]);
#line 102 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						_data_->host = _data_->_tmp36_;
#line 895 "ssh-plugin.c"
						{
#line 104 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
							_data_->_tmp37_ = NULL;
#line 104 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
							_data_->_tmp37_ = _data_->host;
#line 104 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
							_data_->_tmp38_ = NULL;
#line 104 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
							_data_->_tmp38_ = string_strip (_data_->_tmp37_);
#line 104 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
							_data_->host_stripped = _data_->_tmp38_;
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
							_data_->_tmp41_ = NULL;
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
							_data_->_tmp41_ = _data_->host_stripped;
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
							if (g_strcmp0 (_data_->_tmp41_, "") != 0) {
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp42_ = NULL;
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp42_ = _data_->host_stripped;
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp43_ = 0;
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp43_ = string_index_of (_data_->_tmp42_, "*", 0);
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp40_ = _data_->_tmp43_ == -1;
#line 923 "ssh-plugin.c"
							} else {
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp40_ = FALSE;
#line 927 "ssh-plugin.c"
							}
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
							if (_data_->_tmp40_) {
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp44_ = NULL;
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp44_ = _data_->host_stripped;
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp45_ = 0;
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp45_ = string_index_of (_data_->_tmp44_, "?", 0);
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp39_ = _data_->_tmp45_ == -1;
#line 941 "ssh-plugin.c"
							} else {
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp39_ = FALSE;
#line 945 "ssh-plugin.c"
							}
#line 105 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
							if (_data_->_tmp39_) {
#line 107 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp46_ = NULL;
#line 107 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp46_ = _data_->host_stripped;
#line 107 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								g_debug ("ssh-plugin.vala:107: host added: %s\n", _data_->_tmp46_);
#line 108 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp47_ = NULL;
#line 108 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp47_ = _data_->self->priv->hosts;
#line 108 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp48_ = NULL;
#line 108 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp48_ = _data_->host_stripped;
#line 108 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp49_ = NULL;
#line 108 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp49_ = _data_->host_stripped;
#line 108 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp50_ = NULL;
#line 108 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp50_ = synapse_ssh_plugin_ssh_host_new (_data_->_tmp49_);
#line 108 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp51_ = NULL;
#line 108 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_data_->_tmp51_ = _data_->_tmp50_;
#line 108 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								gee_abstract_map_set ((GeeAbstractMap*) _data_->_tmp47_, _data_->_tmp48_, _data_->_tmp51_);
#line 108 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
								_g_object_unref0 (_data_->_tmp51_);
#line 979 "ssh-plugin.c"
							}
#line 102 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
							_g_free0 (_data_->host_stripped);
#line 102 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
							_g_free0 (_data_->host);
#line 985 "ssh-plugin.c"
						}
					}
#line 102 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->host_collection = (_vala_array_free (_data_->host_collection, _data_->host_collection_length1, (GDestroyNotify) g_free), NULL);
#line 990 "ssh-plugin.c"
				}
#line 95 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_free0 (_data_->_tmp26_);
#line 95 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_free0 (_data_->_tmp21_);
#line 996 "ssh-plugin.c"
			}
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_free0 (_data_->_tmp13_);
#line 91 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_free0 (_data_->_tmp8_);
#line 1002 "ssh-plugin.c"
		}
#line 80 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_g_free0 (_data_->line);
#line 80 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_g_regex_unref0 (_data_->ws_re);
#line 80 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_g_regex_unref0 (_data_->comment_re);
#line 80 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_g_regex_unref0 (_data_->host_key_re);
#line 80 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_g_object_unref0 (_data_->dis);
#line 80 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_g_object_unref0 (_data_->_tmp1_);
#line 1016 "ssh-plugin.c"
	}
	goto __finally19;
	__catch19_g_error:
	{
#line 80 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->e = _data_->_inner_error_;
#line 80 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_inner_error_ = NULL;
#line 116 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp52_ = NULL;
#line 116 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp52_ = _data_->self->config_file;
#line 116 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp53_ = NULL;
#line 116 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp53_ = g_file_get_path (_data_->_tmp52_);
#line 116 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp54_ = NULL;
#line 116 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp54_ = _data_->_tmp53_;
#line 116 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp55_ = NULL;
#line 116 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp55_ = _data_->e;
#line 116 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp56_ = NULL;
#line 116 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp56_ = _data_->_tmp55_->message;
#line 116 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_warning ("ssh-plugin.vala:116: %s: %s", _data_->_tmp54_, _data_->_tmp56_);
#line 116 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_g_free0 (_data_->_tmp54_);
#line 80 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_g_error_free0 (_data_->e);
#line 1051 "ssh-plugin.c"
	}
	__finally19:
#line 80 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
#line 80 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
#line 80 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_clear_error (&_data_->_inner_error_);
#line 80 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		return FALSE;
#line 1062 "ssh-plugin.c"
	}
#line 76 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	if (_data_->_state_ == 0) {
#line 76 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 1068 "ssh-plugin.c"
	} else {
#line 76 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 1072 "ssh-plugin.c"
	}
#line 76 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_object_unref (_data_->_async_result);
#line 76 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	return FALSE;
#line 1078 "ssh-plugin.c"
}


void synapse_ssh_plugin_handle_ssh_config_update (SynapseSshPlugin* self, GFileMonitor* monitor, GFile* file, GFile* other_file, GFileMonitorEvent event_type) {
	GFileMonitorEvent _tmp0_ = 0;
#line 120 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_return_if_fail (self != NULL);
#line 120 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_return_if_fail (monitor != NULL);
#line 120 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_return_if_fail (file != NULL);
#line 125 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp0_ = event_type;
#line 125 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	if (_tmp0_ == G_FILE_MONITOR_EVENT_CHANGES_DONE_HINT) {
#line 127 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_message ("ssh-plugin.vala:127: ssh_config is changed, reparsing");
#line 128 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		synapse_ssh_plugin_parse_ssh_config (self, NULL, NULL);
#line 1098 "ssh-plugin.c"
	}
}


static gboolean synapse_ssh_plugin_real_handles_query (SynapseItemProvider* base, SynapseQuery* query) {
	SynapseSshPlugin * self;
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	GeeHashMap* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
#line 132 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self = (SynapseSshPlugin*) base;
#line 132 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_return_val_if_fail (query != NULL, FALSE);
#line 134 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp1_ = self->priv->hosts;
#line 134 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp2_ = gee_abstract_map_get_size ((GeeMap*) _tmp1_);
#line 134 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp3_ = _tmp2_;
#line 134 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	if (_tmp3_ > 0) {
#line 1122 "ssh-plugin.c"
		gboolean _tmp4_ = FALSE;
		SynapseQuery _tmp5_ = {0};
		SynapseQueryFlags _tmp6_ = 0;
#line 135 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp5_ = *query;
#line 135 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp6_ = _tmp5_.query_type;
#line 135 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		if ((_tmp6_ & SYNAPSE_QUERY_FLAGS_ACTIONS) == SYNAPSE_QUERY_FLAGS_ACTIONS) {
#line 135 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_tmp4_ = TRUE;
#line 1134 "ssh-plugin.c"
		} else {
			SynapseQuery _tmp7_ = {0};
			SynapseQueryFlags _tmp8_ = 0;
#line 136 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_tmp7_ = *query;
#line 136 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_tmp8_ = _tmp7_.query_type;
#line 136 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_tmp4_ = (_tmp8_ & SYNAPSE_QUERY_FLAGS_INTERNET) == SYNAPSE_QUERY_FLAGS_INTERNET;
#line 1144 "ssh-plugin.c"
		}
#line 135 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp0_ = _tmp4_;
#line 1148 "ssh-plugin.c"
	} else {
#line 134 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp0_ = FALSE;
#line 1152 "ssh-plugin.c"
	}
#line 134 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	result = _tmp0_;
#line 134 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	return result;
#line 1158 "ssh-plugin.c"
}


static void synapse_ssh_plugin_real_search_data_free (gpointer _data) {
	SynapseSshPluginSearchData* _data_;
	_data_ = _data;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_query_destroy (&_data_->q);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_g_object_unref0 (_data_->result);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_g_object_unref0 (_data_->self);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_slice_free (SynapseSshPluginSearchData, _data_);
#line 1173 "ssh-plugin.c"
}


static void synapse_ssh_plugin_real_search (SynapseItemProvider* base, SynapseQuery* q, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	SynapseSshPlugin * self;
	SynapseSshPluginSearchData* _data_;
	SynapseSshPlugin* _tmp0_ = NULL;
	SynapseQuery _tmp1_ = {0};
	SynapseQuery _tmp2_ = {0};
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self = (SynapseSshPlugin*) base;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_ = g_slice_new0 (SynapseSshPluginSearchData);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, synapse_ssh_plugin_real_search);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, synapse_ssh_plugin_real_search_data_free);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->self = _tmp0_;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp1_ = *q;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_query_copy (&_tmp1_, &_tmp2_);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_query_destroy (&_data_->q);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->q = _tmp2_;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_ssh_plugin_real_search_co (_data_);
#line 1205 "ssh-plugin.c"
}


static SynapseResultSet* synapse_ssh_plugin_real_search_finish (SynapseItemProvider* base, GAsyncResult* _res_, GError** error) {
	SynapseResultSet* result;
	SynapseSshPluginSearchData* _data_;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	if (g_simple_async_result_propagate_error (G_SIMPLE_ASYNC_RESULT (_res_), error)) {
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		return NULL;
#line 1216 "ssh-plugin.c"
	}
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	result = _data_->result;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->result = NULL;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	return result;
#line 1226 "ssh-plugin.c"
}


static gboolean _synapse_ssh_plugin_real_search_co_gsource_func (gpointer self) {
	gboolean result;
	result = synapse_ssh_plugin_real_search_co (self);
#line 141 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	return result;
#line 1235 "ssh-plugin.c"
}


static gboolean synapse_ssh_plugin_real_search_co (SynapseSshPluginSearchData* _data_) {
#line 139 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	switch (_data_->_state_) {
#line 139 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		case 0:
#line 1244 "ssh-plugin.c"
		goto _state_0;
#line 139 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		case 1:
#line 1248 "ssh-plugin.c"
		goto _state_1;
		default:
#line 139 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_assert_not_reached ();
#line 1253 "ssh-plugin.c"
	}
	_state_0:
#line 141 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, _synapse_ssh_plugin_real_search_co_gsource_func, _data_, NULL);
#line 142 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->_state_ = 1;
#line 142 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	return FALSE;
#line 1262 "ssh-plugin.c"
	_state_1:
	;
#line 143 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_query_check_cancellable (&_data_->q, &_data_->_inner_error_);
#line 143 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
#line 143 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		if (_data_->_inner_error_->domain == SYNAPSE_SEARCH_ERROR) {
#line 143 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			g_simple_async_result_set_from_error (_data_->_async_result, _data_->_inner_error_);
#line 143 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			g_error_free (_data_->_inner_error_);
#line 143 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			if (_data_->_state_ == 0) {
#line 143 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 1279 "ssh-plugin.c"
			} else {
#line 143 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				g_simple_async_result_complete (_data_->_async_result);
#line 1283 "ssh-plugin.c"
			}
#line 143 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			g_object_unref (_data_->_async_result);
#line 143 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			return FALSE;
#line 1289 "ssh-plugin.c"
		} else {
#line 143 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
#line 143 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			g_clear_error (&_data_->_inner_error_);
#line 143 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			return FALSE;
#line 1297 "ssh-plugin.c"
		}
	}
#line 145 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->_tmp0_ = NULL;
#line 145 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->_tmp0_ = synapse_result_set_new ();
#line 145 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->results = _data_->_tmp0_;
#line 147 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	memset (&_data_->_tmp1_, 0, sizeof (SynapseQuery));
#line 147 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->_tmp1_ = _data_->q;
#line 147 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->_tmp2_ = NULL;
#line 147 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->_tmp2_ = _data_->_tmp1_.query_string;
#line 147 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->_tmp3_ = NULL;
#line 147 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->_tmp3_ = synapse_query_get_matchers_for_query (_data_->_tmp2_, 0, G_REGEX_OPTIMIZE | G_REGEX_CASELESS);
#line 147 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->matchers = _data_->_tmp3_;
#line 1320 "ssh-plugin.c"
	{
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp4_ = NULL;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp4_ = _data_->self->priv->hosts;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp5_ = NULL;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp5_ = gee_abstract_map_get_values ((GeeMap*) _data_->_tmp4_);
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp6_ = NULL;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp6_ = _data_->_tmp5_;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp7_ = NULL;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp7_ = _data_->_tmp6_;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp8_ = NULL;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp8_ = gee_iterable_iterator ((GeeIterable*) _data_->_tmp7_);
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp9_ = NULL;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_tmp9_ = _data_->_tmp8_;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_g_object_unref0 (_data_->_tmp7_);
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_data_->_host_it = _data_->_tmp9_;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		while (TRUE) {
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp10_ = NULL;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp10_ = _data_->_host_it;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp11_ = FALSE;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp11_ = gee_iterator_next (_data_->_tmp10_);
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			if (!_data_->_tmp11_) {
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				break;
#line 1364 "ssh-plugin.c"
			}
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp12_ = NULL;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp12_ = _data_->_host_it;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp13_ = NULL;
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->_tmp13_ = gee_iterator_get (_data_->_tmp12_);
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_data_->host = (SynapseSshPluginSshHost*) _data_->_tmp13_;
#line 1376 "ssh-plugin.c"
			{
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp14_ = NULL;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp14_ = _data_->matchers;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp15_ = NULL;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp15_ = _g_object_ref0 (_data_->_tmp14_);
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_matcher_list = _data_->_tmp15_;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp16_ = NULL;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp16_ = _data_->_matcher_list;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp17_ = 0;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp17_ = gee_collection_get_size ((GeeCollection*) _data_->_tmp16_);
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp18_ = 0;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_tmp18_ = _data_->_tmp17_;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_matcher_size = _data_->_tmp18_;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_data_->_matcher_index = -1;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				while (TRUE) {
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp19_ = 0;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp19_ = _data_->_matcher_index;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_matcher_index = _data_->_tmp19_ + 1;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp20_ = 0;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp20_ = _data_->_matcher_index;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp21_ = 0;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp21_ = _data_->_matcher_size;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					if (!(_data_->_tmp20_ < _data_->_tmp21_)) {
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						break;
#line 1424 "ssh-plugin.c"
					}
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp22_ = NULL;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp22_ = _data_->_matcher_list;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp23_ = 0;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp23_ = _data_->_matcher_index;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp24_ = NULL;
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp24_ = gee_list_get (_data_->_tmp22_, _data_->_tmp23_);
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->matcher = (GeeMapEntry*) _data_->_tmp24_;
#line 154 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp25_ = NULL;
#line 154 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp25_ = _data_->matcher;
#line 154 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp26_ = NULL;
#line 154 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp26_ = gee_map_entry_get_key (_data_->_tmp25_);
#line 154 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp27_ = NULL;
#line 154 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp27_ = _data_->_tmp26_;
#line 154 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp28_ = NULL;
#line 154 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp28_ = _data_->host;
#line 154 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp29_ = NULL;
#line 154 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp29_ = synapse_ssh_plugin_ssh_host_get_host_query (_data_->_tmp28_);
#line 154 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp30_ = NULL;
#line 154 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp30_ = _data_->_tmp29_;
#line 154 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp31_ = FALSE;
#line 154 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_data_->_tmp31_ = g_regex_match ((GRegex*) _data_->_tmp27_, _data_->_tmp30_, 0, NULL);
#line 154 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					if (_data_->_tmp31_) {
#line 156 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						_data_->_tmp32_ = NULL;
#line 156 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						_data_->_tmp32_ = _data_->results;
#line 156 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						_data_->_tmp33_ = NULL;
#line 156 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						_data_->_tmp33_ = _data_->host;
#line 156 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						_data_->_tmp34_ = NULL;
#line 156 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						_data_->_tmp34_ = _data_->matcher;
#line 156 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						_data_->_tmp35_ = NULL;
#line 156 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						_data_->_tmp35_ = gee_map_entry_get_value (_data_->_tmp34_);
#line 156 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						_data_->_tmp36_ = 0;
#line 156 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						_data_->_tmp36_ = _data_->_tmp35_;
#line 156 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						synapse_result_set_add (_data_->_tmp32_, (SynapseMatch*) _data_->_tmp33_, ((gint) ((gintptr) _data_->_tmp36_)) - SYNAPSE_MATCH_SCORE_INCREMENT_SMALL);
#line 157 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						_g_object_unref0 (_data_->matcher);
#line 157 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
						break;
#line 1496 "ssh-plugin.c"
					}
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
					_g_object_unref0 (_data_->matcher);
#line 1500 "ssh-plugin.c"
				}
#line 152 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				_g_object_unref0 (_data_->_matcher_list);
#line 1504 "ssh-plugin.c"
			}
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_object_unref0 (_data_->host);
#line 1508 "ssh-plugin.c"
		}
#line 150 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_g_object_unref0 (_data_->_host_it);
#line 1512 "ssh-plugin.c"
	}
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_query_check_cancellable (&_data_->q, &_data_->_inner_error_);
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		if (_data_->_inner_error_->domain == SYNAPSE_SEARCH_ERROR) {
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			g_simple_async_result_set_from_error (_data_->_async_result, _data_->_inner_error_);
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			g_error_free (_data_->_inner_error_);
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_object_unref0 (_data_->matchers);
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_object_unref0 (_data_->results);
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			if (_data_->_state_ == 0) {
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 1532 "ssh-plugin.c"
			} else {
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
				g_simple_async_result_complete (_data_->_async_result);
#line 1536 "ssh-plugin.c"
			}
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			g_object_unref (_data_->_async_result);
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			return FALSE;
#line 1542 "ssh-plugin.c"
		} else {
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_object_unref0 (_data_->matchers);
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_object_unref0 (_data_->results);
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			g_clear_error (&_data_->_inner_error_);
#line 162 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			return FALSE;
#line 1554 "ssh-plugin.c"
		}
	}
#line 164 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_data_->result = _data_->results;
#line 164 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_g_object_unref0 (_data_->matchers);
#line 164 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	if (_data_->_state_ == 0) {
#line 164 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 1565 "ssh-plugin.c"
	} else {
#line 164 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 1569 "ssh-plugin.c"
	}
#line 164 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_object_unref (_data_->_async_result);
#line 164 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	return FALSE;
#line 139 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_g_object_unref0 (_data_->matchers);
#line 139 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_g_object_unref0 (_data_->results);
#line 139 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	if (_data_->_state_ == 0) {
#line 139 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 1583 "ssh-plugin.c"
	} else {
#line 139 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 1587 "ssh-plugin.c"
	}
#line 139 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_object_unref (_data_->_async_result);
#line 139 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	return FALSE;
#line 1593 "ssh-plugin.c"
}


SynapseSshPlugin* synapse_ssh_plugin_construct (GType object_type) {
	SynapseSshPlugin * self = NULL;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self = (SynapseSshPlugin*) g_object_new (object_type, NULL);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	return self;
#line 1603 "ssh-plugin.c"
}


SynapseSshPlugin* synapse_ssh_plugin_new (void) {
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	return synapse_ssh_plugin_construct (SYNAPSE_TYPE_SSH_PLUGIN);
#line 1610 "ssh-plugin.c"
}


static gboolean synapse_ssh_plugin_real_get_enabled (SynapseActivatable* base) {
	gboolean result;
	SynapseSshPlugin* self;
	gboolean _tmp0_ = FALSE;
#line 28 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self = (SynapseSshPlugin*) base;
#line 28 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp0_ = self->priv->_enabled;
#line 28 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	result = _tmp0_;
#line 28 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	return result;
#line 1626 "ssh-plugin.c"
}


static void synapse_ssh_plugin_real_set_enabled (SynapseActivatable* base, gboolean value) {
	SynapseSshPlugin* self;
	gboolean _tmp0_ = FALSE;
#line 28 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self = (SynapseSshPlugin*) base;
#line 28 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp0_ = value;
#line 28 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self->priv->_enabled = _tmp0_;
#line 28 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_object_notify ((GObject *) self, "enabled");
#line 1641 "ssh-plugin.c"
}


static GObject * synapse_ssh_plugin_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	SynapseSshPlugin * self;
	GeeHashMap* _tmp0_ = NULL;
#line 39 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	parent_class = G_OBJECT_CLASS (synapse_ssh_plugin_parent_class);
#line 39 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 39 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYNAPSE_TYPE_SSH_PLUGIN, SynapseSshPlugin);
#line 41 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp0_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, SYNAPSE_SSH_PLUGIN_TYPE_SSH_HOST, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 41 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_g_object_unref0 (self->priv->hosts);
#line 41 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self->priv->hosts = _tmp0_;
#line 39 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	return obj;
#line 1664 "ssh-plugin.c"
}


static void synapse_ssh_plugin_ssh_host_real_do_action (SynapseActionMatch* base) {
	SynapseSshPluginSshHost * self;
	GError * _inner_error_ = NULL;
#line 171 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self = (SynapseSshPluginSshHost*) base;
#line 1673 "ssh-plugin.c"
	{
		GAppInfo* ai = NULL;
		const gchar* _tmp0_ = NULL;
		const gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		gchar* _tmp3_ = NULL;
		GAppInfo* _tmp4_ = NULL;
		GAppInfo* _tmp5_ = NULL;
		GAppInfo* _tmp6_ = NULL;
#line 175 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp0_ = synapse_match_get_title ((SynapseMatch*) self);
#line 175 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp1_ = _tmp0_;
#line 175 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp2_ = g_strdup_printf ("ssh %s", _tmp1_);
#line 175 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp3_ = _tmp2_;
#line 175 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp4_ = g_app_info_create_from_commandline (_tmp3_, "ssh", G_APP_INFO_CREATE_NEEDS_TERMINAL, &_inner_error_);
#line 175 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp5_ = _tmp4_;
#line 175 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_g_free0 (_tmp3_);
#line 175 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		ai = _tmp5_;
#line 175 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1701 "ssh-plugin.c"
			goto __catch20_g_error;
		}
#line 178 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp6_ = ai;
#line 178 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_app_info_launch (_tmp6_, NULL, NULL, &_inner_error_);
#line 178 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 178 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
			_g_object_unref0 (ai);
#line 1712 "ssh-plugin.c"
			goto __catch20_g_error;
		}
#line 173 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_g_object_unref0 (ai);
#line 1717 "ssh-plugin.c"
	}
	goto __finally20;
	__catch20_g_error:
	{
		GError* err = NULL;
		GError* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
#line 173 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		err = _inner_error_;
#line 173 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_inner_error_ = NULL;
#line 182 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp7_ = err;
#line 182 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_tmp8_ = _tmp7_->message;
#line 182 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_warning ("ssh-plugin.vala:182: %s", _tmp8_);
#line 173 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		_g_error_free0 (err);
#line 1737 "ssh-plugin.c"
	}
	__finally20:
#line 173 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 173 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 173 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_clear_error (&_inner_error_);
#line 173 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		return;
#line 1748 "ssh-plugin.c"
	}
}


static SynapseSshPluginSshHost* synapse_ssh_plugin_ssh_host_construct (GType object_type, const gchar* host_name) {
	SynapseSshPluginSshHost * self = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
#line 186 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_return_val_if_fail (host_name != NULL, NULL);
#line 188 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp0_ = host_name;
#line 188 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp1_ = _ ("Connect with SSH");
#line 188 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp2_ = host_name;
#line 188 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self = (SynapseSshPluginSshHost*) g_object_new (object_type, "title", _tmp0_, "description", _tmp1_, "has-thumbnail", FALSE, "icon-name", "terminal", "host-query", _tmp2_, NULL);
#line 186 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	return self;
#line 1770 "ssh-plugin.c"
}


static SynapseSshPluginSshHost* synapse_ssh_plugin_ssh_host_new (const gchar* host_name) {
#line 186 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	return synapse_ssh_plugin_ssh_host_construct (SYNAPSE_SSH_PLUGIN_TYPE_SSH_HOST, host_name);
#line 1777 "ssh-plugin.c"
}


static const gchar* synapse_ssh_plugin_ssh_host_get_host_query (SynapseSshPluginSshHost* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 169 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 169 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp0_ = self->priv->_host_query;
#line 169 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	result = _tmp0_;
#line 169 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	return result;
#line 1792 "ssh-plugin.c"
}


static void synapse_ssh_plugin_ssh_host_set_host_query (SynapseSshPluginSshHost* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 169 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_return_if_fail (self != NULL);
#line 169 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp0_ = value;
#line 169 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 169 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_g_free0 (self->priv->_host_query);
#line 169 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self->priv->_host_query = _tmp1_;
#line 169 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_object_notify ((GObject *) self, "host-query");
#line 1811 "ssh-plugin.c"
}


static void synapse_ssh_plugin_ssh_host_class_init (SynapseSshPluginSshHostClass * klass) {
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_ssh_plugin_ssh_host_parent_class = g_type_class_peek_parent (klass);
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_type_class_add_private (klass, sizeof (SynapseSshPluginSshHostPrivate));
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	((SynapseActionMatchClass *) klass)->do_action = synapse_ssh_plugin_ssh_host_real_do_action;
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_synapse_ssh_plugin_ssh_host_get_property;
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_synapse_ssh_plugin_ssh_host_set_property;
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	G_OBJECT_CLASS (klass)->finalize = synapse_ssh_plugin_ssh_host_finalize;
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNAPSE_SSH_PLUGIN_SSH_HOST_HOST_QUERY, g_param_spec_string ("host-query", "host-query", "host-query", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
#line 1830 "ssh-plugin.c"
}


static void synapse_ssh_plugin_ssh_host_instance_init (SynapseSshPluginSshHost * self) {
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self->priv = SYNAPSE_SSH_PLUGIN_SSH_HOST_GET_PRIVATE (self);
#line 1837 "ssh-plugin.c"
}


static void synapse_ssh_plugin_ssh_host_finalize (GObject* obj) {
	SynapseSshPluginSshHost * self;
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYNAPSE_SSH_PLUGIN_TYPE_SSH_HOST, SynapseSshPluginSshHost);
#line 169 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_g_free0 (self->priv->_host_query);
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	G_OBJECT_CLASS (synapse_ssh_plugin_ssh_host_parent_class)->finalize (obj);
#line 1849 "ssh-plugin.c"
}


static GType synapse_ssh_plugin_ssh_host_get_type (void) {
	static volatile gsize synapse_ssh_plugin_ssh_host_type_id__volatile = 0;
	if (g_once_init_enter (&synapse_ssh_plugin_ssh_host_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynapseSshPluginSshHostClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synapse_ssh_plugin_ssh_host_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynapseSshPluginSshHost), 0, (GInstanceInitFunc) synapse_ssh_plugin_ssh_host_instance_init, NULL };
		GType synapse_ssh_plugin_ssh_host_type_id;
		synapse_ssh_plugin_ssh_host_type_id = g_type_register_static (SYNAPSE_TYPE_ACTION_MATCH, "SynapseSshPluginSshHost", &g_define_type_info, 0);
		g_once_init_leave (&synapse_ssh_plugin_ssh_host_type_id__volatile, synapse_ssh_plugin_ssh_host_type_id);
	}
	return synapse_ssh_plugin_ssh_host_type_id__volatile;
}


static void _vala_synapse_ssh_plugin_ssh_host_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SynapseSshPluginSshHost * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYNAPSE_SSH_PLUGIN_TYPE_SSH_HOST, SynapseSshPluginSshHost);
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	switch (property_id) {
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		case SYNAPSE_SSH_PLUGIN_SSH_HOST_HOST_QUERY:
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_value_set_string (value, synapse_ssh_plugin_ssh_host_get_host_query (self));
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		break;
#line 1876 "ssh-plugin.c"
		default:
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		break;
#line 1882 "ssh-plugin.c"
	}
}


static void _vala_synapse_ssh_plugin_ssh_host_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SynapseSshPluginSshHost * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYNAPSE_SSH_PLUGIN_TYPE_SSH_HOST, SynapseSshPluginSshHost);
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	switch (property_id) {
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		case SYNAPSE_SSH_PLUGIN_SSH_HOST_HOST_QUERY:
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		synapse_ssh_plugin_ssh_host_set_host_query (self, g_value_get_string (value));
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		break;
#line 1898 "ssh-plugin.c"
		default:
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 167 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		break;
#line 1904 "ssh-plugin.c"
	}
}


static void synapse_ssh_plugin_class_init (SynapseSshPluginClass * klass) {
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_ssh_plugin_parent_class = g_type_class_peek_parent (klass);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_type_class_add_private (klass, sizeof (SynapseSshPluginPrivate));
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_synapse_ssh_plugin_get_property;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_synapse_ssh_plugin_set_property;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	G_OBJECT_CLASS (klass)->constructor = synapse_ssh_plugin_constructor;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	G_OBJECT_CLASS (klass)->finalize = synapse_ssh_plugin_finalize;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNAPSE_SSH_PLUGIN_ENABLED, g_param_spec_boolean ("enabled", "enabled", "enabled", TRUE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 36 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_ssh_plugin_register_plugin ();
#line 1926 "ssh-plugin.c"
}


static void synapse_ssh_plugin_synapse_activatable_interface_init (SynapseActivatableIface * iface) {
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_ssh_plugin_synapse_activatable_parent_iface = g_type_interface_peek_parent (iface);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	iface->activate = (void (*)(SynapseActivatable*)) synapse_ssh_plugin_real_activate;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	iface->deactivate = (void (*)(SynapseActivatable*)) synapse_ssh_plugin_real_deactivate;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	iface->get_enabled = synapse_ssh_plugin_real_get_enabled;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	iface->set_enabled = synapse_ssh_plugin_real_set_enabled;
#line 1941 "ssh-plugin.c"
}


static void synapse_ssh_plugin_synapse_item_provider_interface_init (SynapseItemProviderIface * iface) {
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	synapse_ssh_plugin_synapse_item_provider_parent_iface = g_type_interface_peek_parent (iface);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	iface->handles_query = (gboolean (*)(SynapseItemProvider*, SynapseQuery*)) synapse_ssh_plugin_real_handles_query;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	iface->search = (SynapseResultSet* (*)(SynapseItemProvider*, SynapseQuery*, GError**)) synapse_ssh_plugin_real_search;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	iface->search_finish = synapse_ssh_plugin_real_search_finish;
#line 1954 "ssh-plugin.c"
}


static void synapse_ssh_plugin_instance_init (SynapseSshPlugin * self) {
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self->priv = SYNAPSE_SSH_PLUGIN_GET_PRIVATE (self);
#line 28 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self->priv->_enabled = TRUE;
#line 1963 "ssh-plugin.c"
}


static void synapse_ssh_plugin_finalize (GObject* obj) {
	SynapseSshPlugin * self;
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYNAPSE_TYPE_SSH_PLUGIN, SynapseSshPlugin);
#line 29 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_g_object_unref0 (self->priv->hosts);
#line 31 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_g_object_unref0 (self->config_file);
#line 32 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	_g_object_unref0 (self->monitor);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	G_OBJECT_CLASS (synapse_ssh_plugin_parent_class)->finalize (obj);
#line 1979 "ssh-plugin.c"
}


GType synapse_ssh_plugin_get_type (void) {
	static volatile gsize synapse_ssh_plugin_type_id__volatile = 0;
	if (g_once_init_enter (&synapse_ssh_plugin_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynapseSshPluginClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synapse_ssh_plugin_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynapseSshPlugin), 0, (GInstanceInitFunc) synapse_ssh_plugin_instance_init, NULL };
		static const GInterfaceInfo synapse_activatable_info = { (GInterfaceInitFunc) synapse_ssh_plugin_synapse_activatable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo synapse_item_provider_info = { (GInterfaceInitFunc) synapse_ssh_plugin_synapse_item_provider_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType synapse_ssh_plugin_type_id;
		synapse_ssh_plugin_type_id = g_type_register_static (G_TYPE_OBJECT, "SynapseSshPlugin", &g_define_type_info, 0);
		g_type_add_interface_static (synapse_ssh_plugin_type_id, SYNAPSE_TYPE_ACTIVATABLE, &synapse_activatable_info);
		g_type_add_interface_static (synapse_ssh_plugin_type_id, SYNAPSE_TYPE_ITEM_PROVIDER, &synapse_item_provider_info);
		g_once_init_leave (&synapse_ssh_plugin_type_id__volatile, synapse_ssh_plugin_type_id);
	}
	return synapse_ssh_plugin_type_id__volatile;
}


static void _vala_synapse_ssh_plugin_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SynapseSshPlugin * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYNAPSE_TYPE_SSH_PLUGIN, SynapseSshPlugin);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	switch (property_id) {
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		case SYNAPSE_SSH_PLUGIN_ENABLED:
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		g_value_set_boolean (value, synapse_activatable_get_enabled ((SynapseActivatable*) self));
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		break;
#line 2010 "ssh-plugin.c"
		default:
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		break;
#line 2016 "ssh-plugin.c"
	}
}


static void _vala_synapse_ssh_plugin_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SynapseSshPlugin * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYNAPSE_TYPE_SSH_PLUGIN, SynapseSshPlugin);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
	switch (property_id) {
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		case SYNAPSE_SSH_PLUGIN_ENABLED:
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		synapse_activatable_set_enabled ((SynapseActivatable*) self, g_value_get_boolean (value));
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		break;
#line 2032 "ssh-plugin.c"
		default:
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 26 "/home/heider/github/synapse/src/plugins/ssh-plugin.vala"
		break;
#line 2038 "ssh-plugin.c"
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



